### PR TITLE
Remove infrastructure outputs from `.env` on `azd down`

### LINKED ISSUE #2217: [Issue] Maybe 'azd down' should remove KEY_VAULT* from .env ?
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
azd version 0.9.0-beta.2 (commit afa7ac6e839be8304b86b3df6b8525a97e48a532)

**Describe the bug**

I just completely took down my resources using 'azd down'. I then ran 'azd up' and got deployment failed:

ERROR: deployment failed: failing invoking action 'provision', planning deployment: planning infrastructure provisioning: creating parameters file: substituting command output inside parameter file: reading secret 'POSTGRESPASSWORD' from vault 'relecloudca5zjvr7-vault': getting key vault secret: Get "https://relecloudca5zjvr7-vault.vault.azure.net/secrets/POSTGRESPASSWORD/?api-version=7.3": dial tcp: lookup relecloudca5zjvr7-vault.vault.azure.net: no such host

I presume that's because my .env still has values for AZURE_KEY_VAULT_NAME and AZURE_KEY_VAULT_ENDPOINT. Perhaps calling 'azd down' should remove those values from the .env file?

I will manually do it, which should work.

**To Reproduce**

On a repo with ACA support, try azd up, azd down and then azd up:
https://github.com/pamelafox/azure-django-postgres-aca-fork

**Expected behavior**

I expect it to start from scratch after I've down'ed it all.

**Environment**

Mac OS X M1 VS Code

### PR DESCRIPTION
**Pull request by ellismg**
The tool had logic to this, but it had been broken for a while due to
a change in how `Environment.Save()` worked. In #1667 we made a change
such that when you save an environment, we would merge in new values
from the existing .env file into the file we were saving, in case the
.env file had been modified by an external hook.

However, that logic did not take into account that we may have
intentionally removed some values (to explicitly delete them) and if
they already existed in the `.env` files, they should be removed as
part of the save operation.

To address this, we now track the deletes that we have preformed so we
can replay them during saving.

To prevent regressing again we also add an end to end test.

Fixes #2217

### CODE REVIEW

**Comment by ellismg** [comment]
This builds on top of some work that @weikanglim started (and kudos to him for discovering the actual issue).  @weikanglim, I was a little worried about cases where we might do a delete and then add the value back, but would end up dropping it in a Save later, so I made some additional modifications to remove things from the deleted item tracker on a Set, and added an additional test there.

File: cli/azd/cmd/down.go [hunk 1]
```diff
@@ -114,21 +114,10 @@ func (a *downAction) Run(ctx context.Context) (*actions.ActionResult, error) {
...
 	destroyOptions := provisioning.NewDestroyOptions(a.flags.forceDelete, a.flags.purgeDelete)
-	destroyResult, err := infraManager.Destroy(ctx, destroyOptions)
-	if err != nil {
+	if _, err = infraManager.Destroy(ctx, destroyOptions); err != nil {
 		return nil, fmt.Errorf("deleting infrastructure: %w", err)
 	}
 
-	// Remove any outputs from the template from the environment since destroying the infrastructure
-	// invalidated them all.
-	for outputName := range destroyResult.Outputs {
```
Comment (ellismg) [inline cli/azd/cmd/down.go:124]: This logic is also present in the provisioning manager (it was likely duplicated when we first built that component) so there removal here is just removing an extra copy of the code that would be a no-op.

Comment (ellismg) [reply cli/azd/cmd/down.go:124]: ref: https://github.com/Azure/azure-dev/blob/8230e0298e2a30b8d1956268b93ed402be04ab7e/cli/azd/pkg/infra/provisioning/manager.go#L99-L118

File: cli/azd/pkg/environment/environment.go [hunk 2]
```diff
@@ -177,6 +181,7 @@ func (e *Environment) LookupEnv(key string) (string, bool) {
 // does not exist. [Save] should be called to ensure this change is persisted.
 func (e *Environment) DotenvDelete(key string) {
```
Comment (wbreza) [inline cli/azd/pkg/environment/environment.go:182]: Can we rename these `DotXXX` methods?  I know we use the `dotenv` package behind the scenes but as a consumer of the `Environment` struct we don't care or need to know.  I would prefer to see something more generic like `DeleteValue(...)` and `SetValue(...)`

File: cli/azd/cmd/down.go [hunk 3]
```diff
@@ -114,21 +114,10 @@ func (a *downAction) Run(ctx context.Context) (*actions.ActionResult, error) {
...
-		a.env.DotenvDelete(outputName)
-	}
-
-	if err := a.env.Save(); err != nil {
-		return nil, fmt.Errorf("saving environment: %w", err)
-	}
-
```
Comment (wbreza) [inline cli/azd/cmd/down.go:131]: Don't we still need these to delete the values?

File: cli/azd/pkg/environment/environment.go [hunk 4]
```diff
@@ -51,6 +51,10 @@ type Environment struct {
 	// dotenv is a map of keys to values, persisted to the `.env` file stored in this environment's [Root].
 	dotenv map[string]string
 
+	// dotEnvDeleted keeps track of deleted keys to be reapplied before a merge operation
+	// happens in Save
+	dotenvDeleted map[string]struct{}
```
Comment (wbreza) [inline cli/azd/pkg/environment/environment.go:56]: Similar to other comment, can we just call this `deletedItems` or `deletedValues` ?

File: cli/azd/cmd/down.go (hunk 3 above)
Comment (ellismg) [reply cli/azd/cmd/down.go:131]: > Don't we still need these to delete the values?

Added a comment after I opened the PR to explain what was going on here, but likely raced with your feedback.  We have this code in two places now, in both the provisioning manager and in down.go itself.  This is just removing the copy in down, since the work has already been doing in the provisioning manager's destroy function.

File: cli/azd/pkg/environment/environment.go (hunk 2 above)
Comment (ellismg) [reply cli/azd/pkg/environment/environment.go:182]: I do like these new names better, I will do this in a follow up PR since it will touch more stuff.

File: cli/azd/pkg/environment/environment.go (hunk 4 above)
Comment (ellismg) [reply cli/azd/pkg/environment/environment.go:56]: This I'll fix now since it's local.

File: cli/azd/pkg/environment/environment.go [hunk 5]
```diff
@@ -188,6 +195,7 @@ func (e *Environment) Dotenv() map[string]string {
 // called to ensure this change is persisted.
 func (e *Environment) DotenvSet(key string, value string) {
 	e.dotenv[key] = value
+	delete(e.deletedKeys, key)
```
Comment (weikanglim) [inline cli/azd/pkg/environment/environment.go:198]: Nice catch here

**Review by weikanglim — APPROVED** [review]
LGTM.

**Comment by ellismg** [comment]
/check-enforcer override

The failure in azure-dev - cli (PublishIntegration Publish_For_PR) is not due to this issue and we see it in main as well, I think it is due to some infrastructure issues with how we are getting kubectl.  I am going to open a separate PR to try to address this.
