### PR TITLE
apply app configuration purge

### LINKED ISSUE #248: `azd down` should purge App Configuration Service
**Output from `azd version`**
`azd version 0.1.0-beta.3 (commit 77ab01c3bcf40d12852d543506ecbb935a779f81)`

**Output from `az version`** 
```js
{
  "azure-cli": "2.38.0",
  "azure-cli-core": "2.38.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "containerapp": "0.3.5",
    "log-analytics": "0.2.2",
    "rdbms-connect": "1.0.2"
  }
}
```

**Describe the bug**
After running `azd down --force --purge --no-prompt` I'm finding that the "Azure App Configuration Service" resource was not purged.

**To Reproduce**
1. add an Azure App Configuration Service as a bicep resource
```
resource appConfigSvc 'Microsoft.AppConfiguration/configurationStores@2022-05-01' = {
  name: '${resourceToken}-appconfig'
  location: location
  sku: {
    name: 'Standard'
  }
}
```
3. `azd provision --no-prompt`
4. `azd down --force --purge --no-prompt`

**Expected behavior**
Expected the same behavior as provided for Key Vault so I can use `azd` in a nightly build that will create and then tear down resources without conflict.

**Environment**
- azd runs from GH workflow
```
      - name: Azure Dev Down
        run: azd down --force --purge --no-prompt
        env:
          AZURE_ENV_NAME: ${{ secrets.AZURE_NIGHTLY_ENV_NAME }}
          AZURE_LOCATION: ${{ secrets.AZURE_LOCATION }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
```

**Additional context**
Can work around the issue with a deployment script. Something like...

*yourScriptName.sh*
```sh
deletedAppConfigSvc=$(az appconfig list-deleted --query "[?starts_with(name, '$resourceToken')].name" -o tsv)

if [[ ${#deletedAppConfigSvc} -gt 0 ]]; then
  az appconfig purge --name $deletedAppConfigSvc --yes
else
  echo "Nothing to purge"
fi
```

*bicep resource*
```
resource app_config_svc_purge 'Microsoft.Resources/deploymentScripts@2020-10-01' = {
  name: 'app_config_svc_purge'
  location: location
  kind:'AzureCLI'
  properties: {
    azCliVersion: '2.37.0'
    retentionInterval: 'P1D'
    scriptContent: loadTextContent('yourScriptName.sh')
    arguments:'--resourceToken \'${resourceToken}\''
  }
}
```

### PR DESCRIPTION
**Pull request by hemarina**
Fix #248 
Apply the choice to ask users if they want to purge app configuration stores, using `armappconfiguration` go package, when running `azd down`.

### CODE REVIEW

File: cli/azd/pkg/tools/azcli/appconfig.go [hunk 1]
```diff
@@ -0,0 +1,83 @@
...
+}
+
+type AzCliAppConfigSecret struct {
+	Id    string `json:"id"`
+	Name  string `json:"name"`
+	Value string `json:"value"`
+}
+
+func (cli *azCli) GetAppConfig(ctx context.Context, subscriptionId string, resourceGroupName string, configName string) (*AzCliAppConfig, error) {
+	client, err := cli.createAppConfigClient(ctx, subscriptionId)
```
Comment (vhvb1989) [inline cli/azd/pkg/tools/azcli/appconfig.go:28]: might be good to call the client `appConfigStoresClient`, as that's the client we are creating.
It gives a hint about the resource and operation that it will fetch from the service

File: cli/azd/pkg/tools/azcli/appconfig.go [hunk 2]
```diff
@@ -0,0 +1,83 @@
...
+
+	return &AzCliAppConfig{
+		Id:       *config.ID,
+		Name:     *config.Name,
+		Location: *config.Location,
+		Properties: struct {
+			EnablePurgeProtection bool "json:\"enablePurgeProtection\""
+		}{
+			EnablePurgeProtection: convert.ToValueWithDefault(config.Properties.EnablePurgeProtection, false),
+		},
```
Comment (vhvb1989) [inline cli/azd/pkg/tools/azcli/appconfig.go:46]: Can we update the model `AzCliAppConfig` and make the `Properties` type to be non-inline?

That way we don't need to duplicate the inline-declaration here.  We would just something like 
Properties: AzCliAppConfigProperties {
    EnablePurgeProtection: config.Properties.EnablePurgeProtection
}

Why do we need the `convert.ToValueWithDfault` ??  

According to the REST ref, `config.Properties.EnablePurgeProtection` is default to `false` (https://learn.microsoft.com/en-us/rest/api/appconfiguration/stable/configuration-stores/get?tabs=HTTP#definitions)
Are you getting `nil` instead of false?

File: cli/azd/pkg/tools/azcli/appconfig.go [hunk 3]
```diff
@@ -0,0 +1,83 @@
...
+	if err != nil {
+		return err
+	}
+
+	poller, err := client.BeginPurgeDeleted(ctx, configName, location, nil)
+	if err != nil {
+		return fmt.Errorf("starting purging app configuration: %w", err)
+	}
+
+	_, err = poller.PollUntilDone(ctx, nil)
```
Comment (vhvb1989) [inline cli/azd/pkg/tools/azcli/appconfig.go:61]: Do you know how much does it usually take this to complete?

File: cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go [hunk 4]
```diff
@@ -301,6 +301,13 @@ func (p *BicepProvider) Destroy(
 				return
 			}
 
+			asyncContext.SetProgress(&DestroyProgress{Message: "Getting AppConfigurations to purge", Timestamp: time.Now()})
```
Comment (ellismg) [inline cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go:304]: It looks like the service uses "App Configuration" with a space.  Same for "Key Vault", maybe we should do the same in our user facing messages here?

**Review by vhvb1989 — APPROVED** [review]

File: cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go [hunk 5]
```diff
@@ -534,6 +546,110 @@ func (p *BicepProvider) purgeKeyVaults(
...
+		p.console.Message(ctx, output.WithWarningFormat(appConfigWarning))
+
+		err := asyncContext.Interact(func() error {
+			purgeAppConfigs, err := p.console.Confirm(ctx, input.ConsoleOptions{
+				Message: fmt.Sprintf(
+					"Would you like to %s delete these App Configurations instead, allowing their names to be reused?",
+					output.WithErrorFormat("permanently"),
+				),
+				DefaultValue: false,
+			})
```
Comment (wbreza) [inline cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go:605]: Question about adding yet another prompt/question for the user.  Instead of asking them to purge keyvaults, then purge app configs... Consider grouping all purgable resources into a single prompt??

@puicchan @savannahostrowski  ??

Comment (savannahostrowski) [reply cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go:605]: https://github.com/Azure/azure-dev/issues/248#issuecomment-1278131763 Replied here!

File: cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go [hunk 6]
```diff
@@ -412,6 +419,81 @@ func (p *BicepProvider) destroyResourceGroups(
...
+		items = "App Configurations"
+		itemsWarning = fmt.Sprintf(""+
+			"\nThis operation will delete %d App Configurations. These %s have soft delete enabled "+
+			"allowing them to be recovered for a period \n"+
+			"of time after deletion. During this period, their names may not be reused.\n"+
+			"You can use argument --purge to skip this confirmation.\n\n",
+			len(appConfigs), items)
+	}
+
+	if items != "" && !options.Purge() {
```
Comment (wbreza) [inline cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go:457]: Consider inverting this if statement and moving to the top of the function to short circuit the function.  When we don't have any items to purge we can quickly exit.  I worry about maintaining this method, etc when we add new resource types in the future.

File: cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go [hunk 7]
```diff
@@ -412,6 +419,81 @@ func (p *BicepProvider) destroyResourceGroups(
 	return nil
 }
 
+func (p *BicepProvider) purgeItems(
+	ctx context.Context,
+	asyncContext *async.InteractiveTaskContextWithProgress[*DestroyResult, *DestroyProgress],
+	keyVaults []*azcli.AzCliKeyVault,
+	appConfigs []*azcli.AzCliAppConfig,
```
Comment (wbreza) [inline cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go:426]: I think this is fine, but I wonder if we could create an interface for all `Purgeable` resources and have a single list of resources that we operate on.

**Review by wbreza — APPROVED** [review]
This looks good but I do have a couple suggestions to improve the maintainability of this purge capability.
