### PR TITLE
Change AKS service spec 'targetPort' from int to string

### LINKED ISSUE #2270: Service deployment to AKS failure on verification step due to Redis targetPort tag being assigned as string.
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
```bash
 azd version 0.9.0-beta.2 (commit afa7ac6e839be8304b86b3df6b8525a97e48a532)
```

**Describe the bug**

When deploying Redis on an AKS cluster and redeploying services through azd cli on the same namespace, the step that verifies if the deployment was made correctly fails, causing the command to interrupt.

```bash
# Deploy services again (either through *azd up* or *azd deploy*)
azd deploy [--debug]
...
...
  (x) Failed: Deploying service public-api-service

ERROR: failed deploying service 'public-api-service': failing invoking action 'deploy', failed retrieving service endpoints, failed waiting for resource, failed waiting for resource, failed unmarshalling resources JSON, json: cannot unmarshal string into Go struct field Port.items.spec.ports.targetPort of type int
```

After investigation, it seems that azd expects the `json` output from the AKS services to have targetPorts assigned to integer values only, whereas through redis deployment, this value is a literal string called `redis` and the ports are sorted at pod level

**To Reproduce**
A reproducible setup was created in [this repository](https://github.com/julioalex-rezende/azd-redis-aks). Instructions are included in the README file. 

**Expected behavior**
There shouldn't be any error on deployment. Especially because the deployment itself was successful, and the failure is on the verification step.

**Environment**
Information on your environment:
    * Language name and version
    * IDE and version: Visual Studio Code 1.78.2

**Additional context**

Things to notice: 
- deployment of services works correctly and fails only on the validation step
- command fails during JSON parsing when verifying deployment (`kubectl -get svc -n <environment_name> -json`)
- this interrupts the command, thus following services are not deployed 
- if we get the Redis manifest, make changes to targetPorts, and then deploy with `kubectl apply`, deployment with azd does not complain anymore. 
- this issue was found with Redis deployment, but any deployment that does the same with the targetPorts will probably result in the same issue

It's possible to check the JSON file with the following command:
```bash
kubectl get service --namespace <namespace> -o json
```
For all Redis-related services (redis-headless, redis-master, redis-replicas) the value for ports.TargetPort is a literal string. That's the cause of conflict with `azd`
```json
"spec": {
    ...
    "ports": [
        {
            "name": "tcp-redis",
            "port": 6379,
            "protocol": "TCP",
            "targetPort": "redis"
        }
    ],
    ...
}
```

Looking at [`azd` source code](https://github.com/Azure/azure-dev/blob/473ce2409aaffaf1f6988c3324969bf2cdc962f2/cli/azd/pkg/tools/kubectl/models.go#L110), `targetPort` field is specified as integer:
```go
type Port struct {
	Port       int    `json:"port"`
	TargetPort int    `json:"targetPort"`
	Protocol   string `json:"protocol"`
}
```

### PR DESCRIPTION
**Pull request by wbreza**
Fixes #2270

`targetPort` can reference a port or well known service name

**From the docs**
Number or name of the port to access on the pods targeted by the service. Number must be in the range 1 to 65535. Name must be an IANA_SVC_NAME. If this is a string, it will be looked up as a named port in the target Pod's container ports. If this is not specified, the value of the 'port' field is used (an identity map). This field is ignored for services with clusterIP=None, and should be omitted or set equal to the 'port' field. 

https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service

### CODE REVIEW

File: cli/azd/pkg/tools/kubectl/models.go [hunk 1]
```diff
@@ -107,7 +107,7 @@ type ServiceStatus struct {
 
 type Port struct {
 	Port       int    `json:"port"`
-	TargetPort int    `json:"targetPort"`
+	TargetPort string `json:"targetPort"`
```
Comment (ellismg) [inline cli/azd/pkg/tools/kubectl/models.go:110]: Are there cases where just a number is on the wire instead of a string representing a number?  From all the k8s docs, it looks like in most examples a raw number (not a string) is used in the manifest, so I'm not sure if we are going to run into cases where a raw number might come across.

**Review by ellismg — COMMENTED** [review]
Just wondering if we have to support the case where targetPort on the wire is still just a raw number.  Hard for me to understanding what the k8s semantics are here from just looking at examples (or perhaps in this case it doesn't matter because the go json deserializer is smart enough to map the wire number to a string type?

File: cli/azd/pkg/tools/kubectl/models.go (hunk 1 above)
Comment (wbreza) [reply cli/azd/pkg/tools/kubectl/models.go]: You are right :) I needed to update the struct to `any` (aka `interface{}`).  Added tests to confirm the unmarshalling.

File: cli/azd/pkg/tools/kubectl/models.go [hunk 2]
```diff
@@ -107,7 +107,7 @@ type ServiceStatus struct {
 
 type Port struct {
 	Port       int    `json:"port"`
-	TargetPort int    `json:"targetPort"`
+	TargetPort any    `json:"targetPort"`
```
Comment (weikanglim) [inline cli/azd/pkg/tools/kubectl/models.go:110]: nit: Can we add a comment here for future readers, to avoid a potential misunderstanding that `TargetPort` should be a strongly-typed value?

File: cli/azd/pkg/tools/kubectl/models_test.go [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+
+import (
+	"encoding/json"
+	"fmt"
+	"testing"
+
+	"github.com/stretchr/testify/require"
+)
+
+func Test_Port_TargetPort_Unmarshalling(t *testing.T) {
```
Comment (weikanglim) [inline cli/azd/pkg/tools/kubectl/models_test.go:11]: Happy to see this test to demonstrate the failing case and make the output contact known, but curious if adding a comment may serve the same purpose. I certainly would have a double-take when changing `any` to `int` due to the failing test for example, but the comment would have alluded at that early enough before the change was made.

Alternatively, perhaps a comment that suggests `port: redis` is a well-known real-world test case may help bring concreteness.

Not sure what type of coding styles our team prefers.

**Review by weikanglim — APPROVED** [review]

**Review by ellismg — APPROVED** [review]
