### PR TITLE
check for "python" OR "py" on windows to verify python cli installation

### LINKED ISSUE #1623: [Issue] Getting Python CLI not installed, when Python is installed.
I have python installed via winget.

azd looks for 'py' in path.

winget install doesn't include 'py'

So it is failing with this command: 

image

should we fall back to looking for python or python3?

### PR DESCRIPTION
**Pull request by hemarina**
fix #1623 
I installed python 3.10 with winget but not able to reproduce the same issue. I realize that the latest winget is using "py.exe" where this issue is caused if other winget is using "python.exe". Adding a check for either "python" or "py" to verify python cli installation.

### CODE REVIEW

File: cli/azd/pkg/tools/python/python.go [hunk 1]
```diff
@@ -120,6 +121,9 @@ func (cli *PythonCli) CreateVirtualEnv(ctx context.Context, workingDir, name str
 
 func pythonExe() string {
 	if runtime.GOOS == "windows" {
+		if _, err := osexec.LookPath("py"); err != nil {
```
Comment (weikanglim) [inline cli/azd/pkg/tools/python/python.go:124]: Whenever we try to use an `error` to mean "not just any error, but a specific type of error" such as `NotFoundError`, we should try to find a matching `error` we can use to do the error check.

If we don't, we end up with a condition called silent failures. Silent failures is how software frustrates users and both developers, when things went wrong, but instead of the program erroring out correctly when the fault is detected, we left things running without actually providing a recovery.

The example here would be that a filesystem read failed while trying to look up "py". `err` is not `nil`, and is a file system error. We would have simply skipped `py`, and said that the user wanted `python`. The user is equally confused at what happened. The user submits the logs, and we wouldn't have figured it out either.

Anyways, that was a long-winded way to show why it's important to practice specific error handling. `golang` is nice that the error handling is part of the return result, and forces both the consumer and library author to think about the contract.

**Review by weikanglim — CHANGES_REQUESTED** [review]
@hemarina The implementation to do it as part of `pythonExe()` seems okay to me. The extra cost of doing `LookPath` per CLI command call is negligible. I just had a small suggestion on error handling... I've left out the advice I have but not a lot of details yet, let me know if you run into any issues.

File: cli/azd/pkg/tools/python/python.go [hunk 2]
```diff
@@ -118,10 +128,25 @@ func (cli *PythonCli) CreateVirtualEnv(ctx context.Context, workingDir, name str
...
+		for _, py := range pyString {
+			found, err = tools.ToolInPath(py)
+			if found && err == nil {
+				return py, found, nil
+			}
+		}
+		return "", found, err
 	} else {
-		return "python3"
+		found, err := tools.ToolInPath("python3")
```
Comment (vhvb1989) [inline cli/azd/pkg/tools/python/python.go:146]: Let's do the same for linux and use ["python3", "python"] in that order.
That would also allow folks using devcontainers to find python... as it is installed as a feature using `python-is-python3`

**Review by vhvb1989 — APPROVED** [review]
This is good for now.
But I don't really like how we need to call `checkPath()` for every method (hence, check the environment every time).

I think we could improve this with `sync.once` and with state inside the tool to hold the `name` of the binary one time and then re-use it.

It would be also convenient to support ENV VARS to set the binary paths for the tools used by azd. For example, `AZD_PYTHON_BIN`.  This will allow folks to choose what to use instead of depending on azd-detection.

But this can be done in the future.

File: cli/azd/pkg/tools/python/python.go [hunk 3]
```diff
@@ -119,13 +128,25 @@ func (cli *PythonCli) CreateVirtualEnv(ctx context.Context, workingDir, name str
...
 
-func pythonExe() string {
+func checkPath() (string, bool, error) {
+	var found bool
+	var err error
 	if runtime.GOOS == "windows" {
-		if _, err := osexec.LookPath("py"); err != nil {
-			return "python"
+		// py for https://peps.python.org/pep-0397
+		pyString := [2]string{"py", "python"}
```
Comment (weikanglim) [inline cli/azd/pkg/tools/python/python.go:136]: Should comment here: `// order is important. we want to resolve 'py', if available, first`

File: cli/azd/pkg/tools/python/python.go [hunk 4]
```diff
@@ -119,13 +128,25 @@ func (cli *PythonCli) CreateVirtualEnv(ctx context.Context, workingDir, name str
...
+
+		for _, py := range pyString {
+			found, err = tools.ToolInPath(py)
+			if found && err == nil {
```
Comment (weikanglim) [inline cli/azd/pkg/tools/python/python.go:140]: `found` should always imply `err == nil`?

File: cli/azd/pkg/tools/python/python.go [hunk 5]
```diff
@@ -119,13 +128,25 @@ func (cli *PythonCli) CreateVirtualEnv(ctx context.Context, workingDir, name str
 	return nil
 }
 
-func pythonExe() string {
+func checkPath() (string, bool, error) {
```
Comment (weikanglim) [inline cli/azd/pkg/tools/python/python.go:131]:
```suggestion
func checkPath() (pyString string, found bool, err error) {
```

Comment (weikanglim) [reply cli/azd/pkg/tools/python/python.go:131]: Makes it easier to read what the return values are, especially for 3 return values.

File: cli/azd/pkg/tools/python/python.go [hunk 6]
```diff
@@ -119,13 +128,25 @@ func (cli *PythonCli) CreateVirtualEnv(ctx context.Context, workingDir, name str
...
+		pyString := [2]string{"py", "python"}
+
+		for _, py := range pyString {
+			found, err = tools.ToolInPath(py)
+			if found && err == nil {
+				return py, found, nil
+			}
 		}
-		return "py" // https://peps.python.org/pep-0397
+		return "", found, err
```
Comment (weikanglim) [inline cli/azd/pkg/tools/python/python.go:144]: I think this ends up returning `nil` error if not found? And so the consumers that only check if `err != nil` won't correctly detect when the tool isn't in PATH?

**Review by ellismg — APPROVED** [review]
LGTM - Thanks for adding this fix for windows folks who don't have `py` per PEP-0397!

**Review by weikanglim — APPROVED** [review]
