### PR TITLE
tracing: add usage attributes for extension installs and runs

### LINKED ISSUE #5937: extensions: telemetry for failing cases may not be reported
I'm not seeing traces for failed extension commands show up in our logs.

### PR DESCRIPTION
**Pull request by weikanglim**
Add usage events and attributes for extension installs (`ext.install`) and runs (`ext.run`).

Expose both `Annotations` and `DisableTroubleshooting` in the action descriptor/options since that was needed.

Fixes #5937 
Contributes towards #5872

### CODE REVIEW

**Review by rajeshkamal5050 — APPROVED** [review]

File: cli/azd/cmd/root.go [hunk 1]
```diff
@@ -379,7 +379,9 @@ func NewRootCmd(
 	root.
 		UseMiddleware("debug", middleware.NewDebugMiddleware).
 		UseMiddleware("ux", middleware.NewUxMiddleware).
-		UseMiddleware("error", middleware.NewErrorMiddleware).
+		UseMiddlewareWhen("error", middleware.NewErrorMiddleware, func(descriptor *actions.ActionDescriptor) bool {
+			return !descriptor.Options.DisableTroubleshooting
```
Comment (wbreza) [inline cli/azd/cmd/root.go:383]: I really like this because sometimes the error troubleshooting just doesn't make sense for "all" errors :)

File: cli/azd/pkg/extensions/manager.go [hunk 2]
```diff
@@ -489,6 +497,10 @@ func (m *Manager) Install(
 		return nil, fmt.Errorf("failed to save user config: %w", err)
 	}
 
+	span.SetAttributes(
+		fields.ExtensionId.String(extension.Id),
+		fields.ExtensionVersion.String(selectedVersion.Version))
```
Comment (wbreza) [inline cli/azd/pkg/extensions/manager.go:502]: Should we consider capturing the extension source name?

**Review by vhvb1989 — APPROVED** [review]

File: cli/azd/cmd/root.go (hunk 1 above)
Comment (weikanglim) [reply cli/azd/cmd/root.go:383]: I get that sentiment. I kept it consistent with what we already had for telemetry.

However, briefly noting that this isn't my personal preference. If you squint closely at how the error middleware is constructed, we already have a list of errors that we're filtering out. I'd personally would be much in favor of using the command path/metadata as a filtering, with a single source of truth.

File: cli/azd/pkg/extensions/manager.go (hunk 2 above)
Comment (weikanglim) [reply cli/azd/pkg/extensions/manager.go:502]: Thanks for the suggestion. I looked into this briefly, but left it as-is for now. Feel free to log an issue if we'd like to pursue further.

I did note the following that left me undecided:
- If we were to do this, we would have to hash the extension source name, since we wouldn't a private registry like `mySecretCompanyProject` to show up in our telemetry.
- Extension source name is a great approximation, however it isn't always accurate? A user could have easily renamed `azd2` to point to the same official registry. It seems that using a more natural key like `Location` would be ideal, but I didn't quite find where to do this.
