### PR TITLE
Ensure directory has user "execute" permissions so it is accessible

### LINKED ISSUE #1691: [Issue] azd cannot access ~/.azd/config.json after macOS upgrade
- [ ] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:

**Describe the bug**
Breaking this issue out of [another conversation](https://github.com/Azure/azure-dev/issues/1673#issuecomment-1459988539).

**To Reproduce**

1. Install older version of `azd` 
2. Run some `azd` commands which results in a `~/.azd/config.json` file being created
3. Upgrade MacOS from ____ to Ventura 13.2.1
4. Use the uninstall script to uninstall `azd` then run the install script to install `azd@latest` 
5. Run `azd up` in an appropriate situation 

Actual: access denied error to `~/.azd/config.json`

image

**Expected behavior**

`azd up` works

**Environment**
Information on your environment:
    * Apple M1

**Additional context**

### PR DESCRIPTION
**Pull request by danieljurek**
Fixes #1691 

I spotted this behavior on a mac after an upgrade in the course of doing other work. The fix for now is to ensure that the directory has the "x" bit set for the user so that it's accessible to the user. At this point I'm not entirely sure why an outside process is resetting this bit during OS upgrades. It would seem that the upgrade is determining that this directory should not be accessible. 

There is a [`repairHomePermissions` tool on macOS](https://eclecticlight.co/2020/03/28/apple-has-changed-resetting-permissions-again/) which can be run in recovery mode. Running that tool does not change these file permissions. We'd need to test an OS upgrade directly in detail to learn more.

### CODE REVIEW

File: cli/azd/pkg/config/manager_test.go [hunk 1]
```diff
@@ -39,3 +42,40 @@ func Test_SaveAndLoadEmptyConfig(t *testing.T) {
 	require.NoError(t, err)
 	require.NotNil(t, existingConfig)
 }
+
+func Test_DirectoryPermissions(t *testing.T) {
+	if runtime.GOOS != "linux" && runtime.GOOS != "darwin" {
+		// Run this test only on Linux/macOS
+		return
```
Comment (weikanglim) [inline cli/azd/pkg/config/manager_test.go:49]: Semantically, maybe `t.Skip("non-linux, darwin system")` is more correct? This change will report the test as "skipped" on `Windows`, instead of "success" (since no error occurred)

File: cli/azd/pkg/config/manager_test.go [hunk 2]
```diff
@@ -39,3 +42,40 @@ func Test_SaveAndLoadEmptyConfig(t *testing.T) {
...
+	}
+
+	getPermissions := func(t *testing.T, path string) fs.FileMode {
+		info, err := os.Stat(path)
+		require.NoError(t, err)
+
+		return info.Mode().Perm()
+	}
+
+	testDir, err := os.MkdirTemp(os.TempDir(), "azd_config_dir_test*")
```
Comment (weikanglim) [inline cli/azd/pkg/config/manager_test.go:59]: It's very common to create temp directories in tests, that `t *testing.T` offers: `testDir := t.TempDir()` as a convenience function

File: cli/azd/pkg/config/manager.go [hunk 3]
```diff
@@ -109,7 +110,28 @@ func GetUserConfigDir() (string, error) {
 		configDirPath = filepath.Join(homeDir, configDir)
 	}
 
-	err := os.MkdirAll(configDirPath, osutil.PermissionDirectory)
+	err := os.MkdirAll(configDirPath, osutil.PermissionDirectoryOwnerOnly)
```
Comment (weikanglim) [inline cli/azd/pkg/config/manager.go:113]: Haven't really thought through the permission change here... We've been pretty relaxed in stamping directories with `755` in the past, `700` seems right here, but I'm not sure what may break... @ellismg @vhvb1989 @wbreza ?

File: cli/azd/pkg/config/manager_test.go (hunk 1 above)
Comment (weikanglim) [reply cli/azd/pkg/config/manager_test.go:49]: Actually, I noticed that we did not have previous code coverage here. Why don't we only assert the directory permissions for nix, and make this the general test case for the function to correctly set up the directory?

File: cli/azd/pkg/config/manager_test.go [hunk 4]
```diff
@@ -39,3 +42,40 @@ func Test_SaveAndLoadEmptyConfig(t *testing.T) {
 	require.NoError(t, err)
 	require.NotNil(t, existingConfig)
 }
+
+func Test_DirectoryPermissions(t *testing.T) {
```
[the remark this answers is not in the document]
Comment (weikanglim) [reply cli/azd/pkg/config/manager_test.go:46]: Actually, should we go the other way and make this a general test for `Test_GetUserConfigDir`?

File: cli/azd/pkg/config/manager.go (hunk 3 above)
Comment (danieljurek) [reply cli/azd/pkg/config/manager.go:113]: I think 700 is a reasonable default here for the current user. We are more restrictive in our file permissions in other places, but those are where sensitive information is being cached: https://github.com/Azure/azure-dev/blob/main/cli/azd/pkg/auth/manager.go#L86 


I would expect that we'd want the same permissions in `~/.azd` to begin with.

File: cli/azd/pkg/config/manager.go [hunk 5]
```diff
@@ -106,10 +107,31 @@ func GetUserConfigDir() (string, error) {
...
+	if runtime.GOOS == "linux" || runtime.GOOS == "darwin" {
+		info, err := os.Stat(configDirPath)
+		if err != nil {
+			return configDirPath, err
+		}
+
+		permissions := info.Mode().Perm()
+		if permissions&0100 == 0 {
+			// Ensure user execute permissions
+			err := os.Chmod(configDirPath, permissions|100)
```
Comment (ellismg) [inline cli/azd/pkg/config/manager.go:130]:
```suggestion
			err := os.Chmod(configDirPath, permissions|0100)
```

File: cli/azd/pkg/config/manager.go (hunk 3 above)
Comment (ellismg) [reply cli/azd/pkg/config/manager.go:113]: I think either choice is reasonable (looking at my mac for example, it seems like many tools will use 0755).  I explicitly denied group and world access to the auth related as a best practice and defense in depth thing.

In practice, I think it would be fine to not grant group and world access to anything we create under `~` (I think it's safe to assume that if HOME resolves to something it resolves to a thing that the current user has access to, and so we don't need to worry about group and world permissions being the thing that grants us access).

File: cli/azd/pkg/config/manager.go (hunk 5 above)
Comment (ellismg) [reply cli/azd/pkg/config/manager.go]: We might just want to create a constant of this mask, given that it's easy for us to forget the leading 0 and only some of the time the linter catches us and tells us that we were likely doing something wrong.

File: cli/azd/pkg/config/manager_test.go [hunk 6]
```diff
@@ -39,3 +42,75 @@ func Test_SaveAndLoadEmptyConfig(t *testing.T) {
 	require.NoError(t, err)
 	require.NotNil(t, existingConfig)
 }
+
+func Test_GetUserConfigDir(t *testing.T) {
+
+	// Setup temp directory for use in tests, delete after creation to validate
+	// folder creation
+	testDir := t.TempDir()
+	os.Remove(testDir)
```
Comment (weikanglim) [inline cli/azd/pkg/config/manager_test.go:51]: Surprised to see the linter not catch this.. `os.Remove()` will return `error` if the removal fails

File: cli/azd/pkg/config/manager_test.go [hunk 7]
```diff
@@ -39,3 +42,75 @@ func Test_SaveAndLoadEmptyConfig(t *testing.T) {
...
+	t.Cleanup(func() { os.RemoveAll(testDir) })
```
Comment (weikanglim) [inline cli/azd/pkg/config/manager_test.go:52]: not needed; `t.TempDir()` will automatically do this for you

File: cli/azd/pkg/config/manager.go (hunk 3 above)
Comment (danieljurek) [reply cli/azd/pkg/config/manager.go:113]: Defense in depth issue opened -- https://github.com/Azure/azure-dev/issues/1991
