### PR TITLE
invalidate deployment state based on resource group existence checks

### LINKED ISSUE #3771: [Issue] azd up should consider whether the resource group exists before opting not to create it
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**

1fastapi-azure-function-apim % azd version
azd version 1.8.0 (commit 8246323c2472148288be4b3cbc3c424bd046b985)

**Describe the bug**
I ran `azd up` on a resource group that I probably deleted at some point. I got this error:

```
fastapi-azure-function-apim % azd env select fastapi-azf-apim
fastapi-azure-function-apim % azd up

Packaging services (azd package)

  (✓) Done: Packaging service api
  - Package Output: /var/folders/nq/2sq7jzp17tl97sgxzbptr2d80000gn/T/fastapi-azure-function-apim-api-azddeploy-1713804018.zip

SUCCESS: Your application was packaged for Azure in 5 seconds.

Provisioning Azure resources (azd provision)
Provisioning Azure resources can take some time.

Subscription: ca-pamelafox-demo-test (32ea8a26-5b40-4838-b6cb-be5c89a57c16)
Location: East US

  (-) Skipped: Didn't find new changes.

SUCCESS: There are no changes to provision for your application.

Deploying services (azd deploy)

  (x) Failed: Deploying service api

ERROR: getting target resource: getting default resource groups for environment: fastapi-azf-apim: resource not found: 0 resource groups with prefix or suffix with value: 'fastapi-azf-apim'

ERROR: error executing step command 'deploy --all': getting target resource: getting default resource groups for environment: fastapi-azf-apim: resource not found: 0 resource groups with prefix or suffix with value: 'fastapi-azf-apim'
```

**To Reproduce**

You probably need to run azd up, then delete the RG in Portal, then run again (with no Bicep change)

**Expected behavior**

It should have provisioned.

**Environment**
Information on your environment: Mac OSX M1 Terminal

**Additional context**

To workaround, I will call `azd provision --no-state`

### PR DESCRIPTION
**Pull request by weikanglim**
This change factors in quick resource-group existence checks as heuristics to the deployment state calculation prior to skipping the deployment. 

With this change, when resource groups are deleted outside of azd, `azd provision` will detect this and continue with provisioning without skipping.

The resource group check leverages the most lightweight possible  HTTP `HEAD` call to the relevant ARM endpoint, and is measured to add ~100ms for a single resource group. Given that most deployments likely have 1-2 resource groups, it is then expected that the overall latency increase is <0.2 seconds overall.

Note that only resource groups **created** by the deployment are checked for. Existing resource groups associated to resources deployed into are not factored in.

Fixes #3771
Would supersede #5667

### CODE REVIEW

**Comment by JeffreyCA** [comment]
Would this also fix https://github.com/Azure/azure-dev/issues/6207? There's a related PR https://github.com/Azure/azure-dev/pull/6267 that I wasn't sure about either...

File: cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go [hunk 1]
```diff
@@ -588,8 +588,29 @@ func (p *BicepProvider) Deploy(ctx context.Context) (*provisioning.DeployResult,
...
-		deploymentState, err := p.deploymentState(ctx, planned, deployment, currentParamsHash)
-		if err == nil {
+		deploymentState, stateErr := p.deploymentState(ctx, planned, deployment, currentParamsHash)
+		if stateErr == nil {
+			// As a heuristic, we also check the existence of all resource groups
+			// created by the deployment to validate the deployment state.
+			// This handles the scenario of resource group(s) being deleted outside of azd,
+			// which is quite common.
+			// This check adds ~100ms per resource group to the deployment time.
+			for _, res := range deploymentState.Resources {
```
Comment (vhvb1989) [inline cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go:598]: Should this be recursive?  In case `Resources` contains a resource type deployment which contains rg?

Comment (weikanglim) [reply cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go:598]: Great question! Recursion isn't necessary here. The `outputResources` property from ARM already contains all resource(s) created from the current and nested deployments.

**Comment by rajeshkamal5050** [comment]
@weikanglim will this be the new behavior?

When rg is manually deleted, `azd provision` will error `resource group foo no longer exists, invalidating deployment state`? are we also `invalidating deployment state`? did not see any code for that. If yes, can we also handle the same for when doing `azd down` question which @JeffreyCA had too?

**Comment by weikanglim** [comment]
@rajeshkamal5050 The new behavior is as follows:

When resource groups are deleted outside of azd, `azd provision` will detect this and continue with provisioning **without skipping**.

@JeffreyCA I left a comment on #6207 to fix the underlying behavior without changing `azd down`.

**Review by JeffreyCA — APPROVED** [review]
