### PR TITLE
Revert "Add --fail-on-prompt flag for strict non-interactive mode"

### LINKED ISSUE #7718: Preflight warnings fail in agent sessions because auto-enabled --fail-on-prompt blocks confirmation
- [ ] Make sure you've installed the latest version using [instructions](https://github.com/Azure/azure-dev?tab=readme-ov-file#installupgrade-azure-developer-cli)

**Output from `azd version`**

```text
azd version 0.0.0-dev.0 (commit 0000000000000000000000000000000000000000) (stable)
```

**Describe the bug**

When local preflight emits **warnings** during `azd provision`, agent-detected sessions now fail instead of following the preflight warning flow.

The regression appears to come from the recent agent-detection change that auto-enables `--fail-on-prompt`. The local preflight warning path still calls `console.Confirm(...)`, and in strict mode that returns:

```text
interactive prompt not allowed in strict mode (--fail-on-prompt)
```

That turns a warning-only preflight result into a hard provisioning failure.

**To Reproduce**

1. Start from `cli/azd/test/functional/testdata/samples/storage` and copy it to a temp directory.
2. Update `infra/resources.bicep` to add Azure AI deployments that force the `ai_model_quota` preflight warning:

```diff
--- cli/azd/test/functional/testdata/samples/storage/infra/resources.bicep
+++ /tmp/azd-storage-repro/infra/resources.bicep
@@
 param environmentName string
 param location string = resourceGroup().location
+param gptModelName string = 'gpt-4o'
+param gptModelVersion string = '2024-08-06'
+@allowed(['Standard', 'GlobalStandard'])
+param gptDeploymentType string = 'GlobalStandard'
+param gptDeploymentCapacity int = 99999
+param embeddingModelName string = 'text-embedding-3-small'
+param embeddingDeploymentCapacity int = 99999
 var tags = { 'azd-env-name': environmentName }
 var resourceToken = toLower(uniqueString(subscription().id, environmentName, location))
@@
 resource storage 'Microsoft.Storage/storageAccounts@2022-05-01' = {
   name: 'st${resourceToken}'
   location: location
@@
   }
 }
+
+resource aiServices 'Microsoft.CognitiveServices/accounts@2024-10-01' = {
+  name: 'ai-${resourceToken}'
+  location: location
+  sku: {
+    name: 'S0'
+  }
+  kind: 'AIServices'
+  properties: {
+    customSubDomainName: 'ai-${resourceToken}'
+    publicNetworkAccess: 'Enabled'
+  }
+}
+
+resource gptDeployment 'Microsoft.CognitiveServices/accounts/deployments@2024-10-01' = {
+  parent: aiServices
+  name: gptModelName
+  properties: {
+    model: {
+      format: 'OpenAI'
+      name: gptModelName
+      version: gptModelVersion
+    }
+  }
+  sku: {
+    name: gptDeploymentType
+    capacity: gptDeploymentCapacity
+  }
+}
+
+resource embeddingDeployment 'Microsoft.CognitiveServices/accounts/deployments@2024-10-01' = {
+  parent: aiServices
+  name: embeddingModelName
+  properties: {
+    model: {
+      format: 'OpenAI'
+      name: embeddingModelName
+    }
+  }
+  sku: {
+    name: 'GlobalStandard'
+    capacity: embeddingDeploymentCapacity
+  }
+  dependsOn: [gptDeployment]
+}
```

3. Initialize the sample and set the required env/config values:

```bash
AZD=/path/to/cli/azd/azd
TMPDIR=$(mktemp -d /tmp/azd-storage-XXXXXX)
cp -R cli/azd/test/functional/testdata/samples/storage/. "$TMPDIR"/

# Apply the resources.bicep change above

ENV_NAME=azd-repro-001
AZD_CONFIG_DIR=$(mktemp -d /tmp/azd-config-XXXXXX)
export AZD_CONFIG_DIR
export NO_COLOR=1

"$AZD" config set auth.useAzCliAuth true
"$AZD" config set defaults.subscription faa080af-c1d8-40ad-9cce-e1a450ca5b57
"$AZD" config set defaults.location eastus2

cd "$TMPDIR"
"$AZD" init -e "$ENV_NAME" --no-prompt
"$AZD" env set AZURE_SUBSCRIPTION_ID faa080af-c1d8-40ad-9cce-e1a450ca5b57
"$AZD" env set AZURE_LOCATION eastus2
"$AZD" env set MY_ARRAY '["item1","item2"]'
"$AZD" env set MY_OBJECT '{"key":"value"}'
"$AZD" env config set infra.parameters.secureValue ''
```

4. Run the control case with agent detection disabled:

```bash
printf 'n\n' | AZD_DISABLE_AGENT_DETECT=1 "$AZD" -e "$ENV_NAME" provision
```

This shows the quota warnings, prompts for confirmation, and after declining exits cleanly with:

```text
SUCCESS: Provisioning was cancelled.
```

5. Run the strict/agent case:

```bash
GITHUB_COPILOT_CLI=true "$AZD" -e "$ENV_NAME" provision
```

This shows the same warnings, then fails with:

```text
ERROR: deployment failed: error deploying infrastructure: prompting for preflight confirmation: interactive prompt not allowed in strict mode (--fail-on-prompt): "Preflight validation found warnings that may cause the deployment to fail. Do you want to continue?" -- provide the value via command-line flags or environment variables
```

**Expected behavior**

Preflight warnings should not become a hard deployment error solely because agent detection auto-enabled `--fail-on-prompt`.

If prompting is not allowed, `azd provision` should either:

1. Preserve the current `--no-prompt` default-confirmation behavior for this warning path, or
2. Abort cleanly as a skipped/cancelled deployment instead of surfacing `error deploying infrastructure`

**Environment**

- OS: macOS (Darwin)
- Repo SHA: `6d92708087fda71819fe3965b25c7ce68286b373`
- azd binary: local dev build from `cli/azd/azd`

**Additional context**

- The behavior difference lines up with these paths:
  - `cli/azd/cmd/auto_install.go` — agent detection auto-enables `FailOnPrompt`
  - `cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go` — preflight warnings call `console.Confirm(...)`
  - `cli/azd/pkg/input/asker.go` — `failOnPrompt` returns an error, while `noPrompt` uses the default confirmation value
- I used an isolated `AZD_CONFIG_DIR` with `auth.useAzCliAuth=true` during repro because my local built-in `azd` token was stale. That was only to get past an unrelated auth problem; the preflight regression itself is independent of auth mode.

### PR DESCRIPTION
**Pull request by weikanglim**
Reverts Azure/azure-dev#7394

Fixes #7718
Contributes towards #7390

### CODE REVIEW

File: cli/azd/internal/grpcserver/prompt_service.go [hunk 1]
```diff
@@ -215,14 +194,6 @@ func (s *promptService) MultiSelect(
 }
 
 func (s *promptService) Prompt(ctx context.Context, req *azdext.PromptRequest) (*azdext.PromptResponse, error) {
-	if req == nil || req.Options == nil {
-		return nil, status.Error(codes.InvalidArgument, "request and options are required")
```
Comment (jongio) [inline cli/azd/internal/grpcserver/prompt_service.go:219]: Nit: this revert also removes the nil-argument guard (`req == nil || req.Options == nil`) from `Prompt()` that was added in #7394 as a drive-by fix. The other three methods (`Confirm`, `Select`, `MultiSelect`) all have theirs. Might be worth re-adding separately.

**Review by jongio — APPROVED** [review]
Clean revert, fixes the blocker. One minor note below.

**Review by spboyer — APPROVED** [review]

**Comment by rajeshkamal5050** [comment]
Merged main and fixed the build. PR #7701 (skip empty console messages in JSON mode) landed after this branch was created — it added a test calling NewConsole with the failOnPrompt param. Removed that extra arg to match the reverted signature.

Tests pass locally. @spboyer @jongio can you re-approve?

**Review by JeffreyCA — APPROVED** [review]
