### PR TITLE
Fix `azd pipeline config` in codespaces

### LINKED ISSUE #948: [Issue] `azd pipeline config` cannot set AZURE_CREDENTIALS from Codespaces
Feel free to close if we are tracking this elsewhere. This is the output I get in Codespaces when I run `pipeline config`. 

Note that I forked the template and then opened the Codespace.

```
Using pipeline provider: GitHub
Creating or updating service principal az-dev-10-21-2022-15-48-46.

Configuring repository savannahostrowski/codespaces-test.

Setting AZURE_CREDENTIALS GitHub repo secret.

Error: failed setting AZURE_CREDENTIALS secret: failed running gh secret set exit code: 1, stdout: , stderr: failed to fetch public key: HTTP 403: Resource not accessible by integration (https://api.github.com/repos/savannahostrowski/codespaces-test/actions/secrets/public-key)
: exit status 1

 *  The terminal process "/bin/bash '-c', 'azd pipeline config'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 
```

### PR DESCRIPTION
**Pull request by weikanglim**
Problem: When `GITHUB_TOKEN` variable is set in codespaces, GitHub CLI will always attempt to use `GITHUB_TOKEN`, which fails to set repository-level secrets. This is due to tokens generated in codespaces not having the ability to manage repository secrets (this is a technical limitation of codespaces).

As a holistic fix that is not specific to codespaces, we simply detect if GitHub CLI is using an environment variable token source (`GITHUB_TOKEN` or `GH_TOKEN`), and if we fail setting secrets due to authorization errors, we simply configure GitHub CLI to ignore the environment variables (by hiding these environment variables when invoking the command) and proceed with logging in.

This type of authorization failure detection + forcing auth mode can be extended to other types of API calls for GitHub CLI in the future.

With this change, running `azd pipeline config` prompts the user to login if credentials are not yet stored on disk in the codespaces container, or otherwise it simply uses the user's oauth token instead of the limited scope PAT token to perform repo-level secrets modifications.

Fixes #948

### CODE REVIEW

File: cli/azd/pkg/tools/github/github.go [hunk 1]
```diff
@@ -84,25 +101,43 @@ func (cli *ghCli) InstallUrl() string {
...
+// The source of the auth token used by `gh` CLI
+type AuthTokenSource int
+
+const (
+	TokenSourceFile AuthTokenSource = iota
+	// See isEnvVarTokenSourceRegex for example token env vars
+	TokenSourceEnvVar
+)
+
+func (cli *ghCli) CheckAuth(ctx context.Context, hostname string) (CheckAuthResult, error) {
```
Comment (vhvb1989) [inline cli/azd/pkg/tools/github/github.go:119]: Should it be `GetAuthStatus` or something like that?   The verb `Check` is usually for returning just a `bool` value, similar to `Is` or `Has`

File: cli/azd/pkg/tools/github/github.go [hunk 2]
```diff
@@ -223,12 +257,65 @@ func (cli *ghCli) GitHubActionsExists(ctx context.Context, repoSlug string) (boo
...
+func (cli *ghCli) newRunArgs(args ...string) exec.RunArgs {
+	runArgs := exec.NewRunArgs("gh", args...)
+	if cli.overrideTokenEnv != nil {
+		runArgs = runArgs.WithEnv(cli.overrideTokenEnv)
+	}
+
+	return runArgs
+}
+
+func (cli *ghCli) runAuthenticated(ctx context.Context, runArgs exec.RunArgs) (exec.RunResult, error) {
```
Comment (vhvb1989) [inline cli/azd/pkg/tools/github/github.go:281]: do we have a `run` alone or `runNoAuth` ?   or why are we describing the way `run` works ?

File: cli/azd/pkg/commands/pipeline/github_provider.go [hunk 3]
```diff
@@ -305,6 +305,43 @@ func (p *GitHubCiProvider) name() string {
...
+	console input.Console,
+	repoSlug string) error {
+	// The actual scope for repository-level secrets is simply the `repo` scope in GitHub.
+	// Thus, listing secrets has the same access level permissions as writing secrets
+	// and can be used for probing secrets authorization.
+	err := ghCli.ListSecrets(ctx, repoSlug)
+
+	if err != nil {
+		return fmt.Errorf("listing secrets: %w", err)
+	} else if errors.Is(err, github.ErrUserNotAuthorized) {
```
[the remark this answers is not in the document]
Comment (weikanglim) [reply cli/azd/pkg/commands/pipeline/github_provider.go:322]: You're definitely right and I'm confused how this worked

File: cli/azd/pkg/tools/github/github.go (hunk 1 above)
Comment (weikanglim) [reply cli/azd/pkg/tools/github/github.go:119]: Makes sense

File: cli/azd/pkg/tools/github/github.go [hunk 4]
```diff
@@ -223,12 +257,65 @@ func (cli *ghCli) GitHubActionsExists(ctx context.Context, repoSlug string) (boo
...
+func (cli *ghCli) ForceConfigureAuth(authMode AuthTokenSource) {
+	if authMode == TokenSourceFile {
+		for _, tokenEnvVarName := range TokenEnvVars {
+			cli.overrideTokenEnv = append(cli.overrideTokenEnv, fmt.Sprintf("%v=", tokenEnvVarName))
+		}
+	} else { // authMode == TokenSourceEnvVar
+		// GitHub CLI will always use environment variables first.
+		// Therefore, we simply need to clear our environment context override to force environment variable usage.
+		cli.overrideTokenEnv = nil
+	}
```
Comment (vhvb1989) [inline cli/azd/pkg/tools/github/github.go:269]:
```suggestion
	if authMode == TokenSourceFile {
	        for _, tokenEnvVarName := range TokenEnvVars {
		        cli.overrideTokenEnv = append(cli.overrideTokenEnv, fmt.Sprintf("%v=", tokenEnvVarName))
	        }
		return
	}
	// GitHub CLI will always use environment variables first.
	// Therefore, we simply need to clear our environment context override to force environment variable usage.
	cli.overrideTokenEnv = nil	
```

File: cli/azd/pkg/tools/github/github.go [hunk 5]
```diff
@@ -223,12 +257,65 @@ func (cli *ghCli) GitHubActionsExists(ctx context.Context, repoSlug string) (boo
 	return true, nil
 }
 
+func (cli *ghCli) ForceConfigureAuth(authMode AuthTokenSource) {
```
Comment (vhvb1989) [inline cli/azd/pkg/tools/github/github.go:260]: Will this happen per command-run?  or is it persisted to the ghCli ?

It would not be good if we are leaving the ghCli with the overridden settings.  So, hopefully this is per-command run. Otherwise, we need to undo the override on `azd pipeline config` defer

File: cli/azd/pkg/tools/github/github.go (hunk 4 above)
Comment (vhvb1989) [reply cli/azd/pkg/tools/github/github.go:269]: This is just a ni.  Feel free to ignore..  It is just me that I don't like the `else` and I'd would try to avoid it if possible

File: cli/azd/pkg/tools/github/github.go (hunk 5 above)
Comment (weikanglim) [reply cli/azd/pkg/tools/github/github.go:260]: No, it's temporal per-command run. Technically, it's per lifetime of a `ghCli` object instance -- so we can decide inside `azd` invocation.

File: cli/azd/pkg/tools/github/github.go (hunk 4 above)
Comment (weikanglim) [reply cli/azd/pkg/tools/github/github.go:269]: Conceptually, I think pattern-matching is what we want here. It's not a validation with early exists..

**Review by vhvb1989 — APPROVED** [review]
