### PR TITLE
Fixes service config handlers referencing stale components

### LINKED ISSUE #3499: Issue for `Kustomize for AKS`
**Describe the issue:**
According to [support-for-helm-and-kustomize-for-aks-service-target](https://devblogs.microsoft.com/azure-sdk/azure-developer-cli-azd-february-2024-release/#support-for-helm-and-kustomize-for-aks-service-target) test.
Update `azure.yaml`, run `azd up`, get error as follow:
image
Manually adding `AZURE_RESOURCE_GROUP` to env, rerun `azd up` get error as follow:
image

How to obtain the follow folder `./kustomize/base`?
image
**Repro Steps:**

1. Login in with command: `azd auth login` and `azd config set alpha.aks.kustomize on`.
2. Execute command: `azd init -t todo-nodejs-mongo-aks -b staging` and update `azure.yaml`.
3. Run `azd up`.

**Environment:**
- Template: todo-nodejs-mongo-aks.
- Azd version : 1.7.0-beta.1-daily  (commit https://github.com/Azure/azure-dev/commit/81f3efd1049889762d01ca46a35630005b45f0b5)

**Expected behavior:**
Run `azd up` can pass.

@rajeshkamal5050    for notification.

### PR DESCRIPTION
**Pull request by wbreza**
Resolves #3499 

Fixes an issue where an event handler bound in one command within an `up` workflow could incorrectly fire when the event is raised in another command.

## Why is this happening?

The `project.ProjectConfig` instance has a singleton lifetime which means the same instance was shared between commands within an `up` workflow.  Some of our service targets (ex. AKS) registers event handler such as `postprovision` during its initialization process.  This event registration is stored within the `ProjectConfig` mentioned above.

This was causing multiple event handlers to be registered for the service target and some of them were referencing scoped components from other commands.  Transient service target AKS was referencing scoped environment from previous commands.

When the `postprovision` event was finally raised it now contained event handlers from the `azd package` command of the workflow in addition to event handlers registered during `azd provision` command.  This was causing the event handler from referencing stale scoped components like the environment.

## How was this fixed

To resolve this `project.ProjectConfig` was changed to a lifetime scope which means that a new instance will be created for each command within a workflow.  The previous fix of depending on Lazy + the hook fixes allow us to move this to a scoped lifetime.

The middleware runner is now created/used during the scoped command allowing it to be removed from the container all together.

This also allows the removal of a weird work around in which needed to check for double registrations the hooks middleware.

### CODE REVIEW

File: cli/azd/pkg/infra/provisioning/manager.go [hunk 1]
```diff
@@ -82,7 +82,7 @@ func (m *Manager) Deploy(ctx context.Context) (*DeployResult, error) {
 		m.console.StopSpinner(ctx, "Didn't find new changes.", input.StepSkipped)
 	}
 
-	if err := m.UpdateEnvironment(ctx, m.env, deployResult.Deployment.Outputs); err != nil {
+	if err := m.UpdateEnvironment(ctx, deployResult.Deployment.Outputs); err != nil {
 		return nil, fmt.Errorf("updating environment with deployment outputs: %w", err)
 	}
```
Comment (wbreza) [inline cli/azd/pkg/infra/provisioning/manager.go:87]: `env` function param no longer required since it should always be leveraging the internal `env`.

File: cli/azd/pkg/ext/event_dispatcher.go [hunk 2]
```diff
@@ -41,6 +41,16 @@ func (ed *EventDispatcher[T]) AddHandler(name Event, handler EventHandlerFn[T])
...
 	events := ed.handlers[name]
+	newHandler := fmt.Sprintf("%v", handler)
+
+	// Ensure the handler is not already registered
+	for _, ref := range events {
+		existingHandler := fmt.Sprintf("%v", ref)
+		if existingHandler == newHandler {
+			return nil
+		}
+	}
```
Comment (wbreza) [inline cli/azd/pkg/ext/event_dispatcher.go:52]: Ensures that an event handler is never incorrectly registered more than one time.  This can happen when multiple services of the same type exist within an azd project.

Comment (ellismg) [reply cli/azd/pkg/ext/event_dispatcher.go]: Cool trick!  What does `fmt.Sprintf("%v", handler)` end up producing?  Is it some compiler generated name?

**Review by ellismg — APPROVED** [review]
Nice simplification and cleanup here and happy to see it fixes the bug as well!

File: cli/azd/pkg/ext/event_dispatcher.go (hunk 2 above)
Comment (wbreza) [reply cli/azd/pkg/ext/event_dispatcher.go]: I ended up rolling this back because it was not needed.. but basically just gets the pointer address as a string that could be used for comparisons.

However it didn't work exactly as intended since functions are passed by value - so even a function passed in from 2 different struct instances was returning the same value which was not intended.
