### PR TITLE
Fix login error when running `azd up`

### LINKED ISSUE #1566: Azd up shows invalid error in a loop when you need to `azd login` first
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
@paulyuk ➜ .../ai/text_summarization/python/function_app (main) $ azd version
azd version 0.6.0-beta.2 (commit c4a201e55a13eba77f9037b296a90e0f81b00dbe)
in a codespace 

New behavior / regression I'm seeing in codespaces shows wrong error message when not logged in.

1) Create a new codespace, or open one that has been asleep for a while, e.g. this one:  https://github.com/Azure-Samples/function-csharp-ai-textsummarize
2) azd up 

result 

@paulyuk ➜ .../ai/text_summarization/python/function_app (main) $ azd up
? Please enter a new environment name: quickpythoncheck Initializing a new project (azd init) 
? Please enter a new environment name:(in a loop) 

expected

A clear message "you need to 'azd login' "

### PR DESCRIPTION
**Pull request by weikanglim**
User not being logged in was not seeing the immediate "not logged in" error when running `azd up`. User also saw multiple environment prompts.

To fix this:
1. Refactored `ensureLogin` from being a middleware to being a `guard`, which fixes `up` not triggering `init`'s login prerequisite, and makes it easier to manage an action without having to think about command-layer changes.
2. Modified `hook` middleware's environment consumption to never prompt. This avoids user being prompted twice: once by the middleware, and again by the command. This could happen anytime the user cancels or the prompt errors out.

Fixes #1566

### CODE REVIEW

File: cli/azd/cmd/container.go [hunk 1]
```diff
@@ -209,17 +211,28 @@ func registerCommonDependencies(container *ioc.NestedContainer) {
...
 			return lazy.NewLazy(func() (*environment.Environment, error) {
-				_, err := lazyAzdContext.GetValue()
+				azdCtx, err := lazyAzdContext.GetValue()
 				if err != nil {
 					return nil, err
 				}
 
-				var env *environment.Environment
-				err = container.Resolve(&env)
+				environmentName := envFlags.environmentName
```
Comment (weikanglim) [inline cli/azd/cmd/container.go:224]: @wbreza Do you feel better about this change? Hooks will end up not triggering the environment prompt.

However, I'm not sure if the `post-up` hook actually reloads the environment. I looked at the code and it seemed that it wouldn't.

Comment (weikanglim) [reply cli/azd/cmd/container.go:224]: Looks like this is indeed an existing issue. Will create an issue for it.

File: cli/azd/cmd/env.go [hunk 2]
```diff
@@ -276,6 +275,7 @@ type envNewAction struct {
 func newEnvNewAction(
 	azdCtx *azdcontext.AzdContext,
 	userProfileService *azcli.UserProfileService,
+	_ auth.EnsureLoginGuard,
```
Comment (vhvb1989) [inline cli/azd/cmd/env.go:278]:
```suggestion
	auth.EnsureLoginGuard,
```

File: cli/azd/cmd/init.go [hunk 3]
```diff
@@ -108,6 +109,7 @@ type initAction struct {
 func newInitAction(
 	accountManager account.Manager,
 	userProfileService *azcli.UserProfileService,
+	_ auth.EnsureLoginGuard,
```
Comment (vhvb1989) [inline cli/azd/cmd/init.go:112]:
```suggestion
	auth.EnsureLoginGuard,
```

File: cli/azd/pkg/auth/guard.go [hunk 4]
```diff
@@ -0,0 +1,19 @@
...
+	if err != nil {
+		return EnsureLoginGuard{}, err
+	}
+
+	_, err = EnsureLoggedInCredential(ctx, cred)
+	if err != nil {
+		return EnsureLoginGuard{}, err
+	}
+
+	return EnsureLoginGuard{}, nil
```
Comment (vhvb1989) [inline cli/azd/pkg/auth/guard.go:18]: why do we want to return empty struct?  

Isn't this actually a `EnsureCredentialLoggedIn` which should return the credential or a true/false?

Comment (weikanglim) [reply cli/azd/pkg/auth/guard.go:18]: The constructor returns `T` if success, `err` if failure.

Maybe we need to rename this to `LoggedinGuard` instead of `EnsureLoginGuard`

File: cli/azd/cmd/init.go (hunk 3 above)
Comment (weikanglim) [reply cli/azd/cmd/init.go:112]: Does this actually work? We're not consuming a dependency; we're including a side-effect constructor parameter.

Comment (vhvb1989) [reply cli/azd/cmd/init.go:112]: Looks like it gives: `mixed named and unnamed parameters`.  I though we could mix it for input.  neverminded then

File: cli/azd/pkg/auth/guard.go (hunk 4 above)
Comment (vhvb1989) [reply cli/azd/pkg/auth/guard.go:18]: What I mean is, we are adding `T` as a dependency for actions like `Init`. But the action does not care about `T` beyond the fact that it can be created...

Then, creating the `T` depends on creating `manager *Manager`, because `T` will get the `crededential` from the manager and check that it is logged in.

So, what an action like `init` really needs is to know that there is a logged in credential. And we are using the logic to create a `T` dependency as the way to know this.  Which I don't think is convenient.

If what the action (like init), really needs is a `logged in credential`, then make the `T` to be either the credential, or an struct that contains the `logged in credential`.  Otherwise, it's odd to see a dependency to be a dependency but to actually be ignored, right... (why is it a dependency then...)

Comment (weikanglim) [reply cli/azd/pkg/auth/guard.go:18]: It's used for creating a side-effect as a `Guard`. I don't know what we want to pass back to `init`... It doesn't actually need the `credential`. It simply needs the `Guard` to fail-fast. Removing the code would have the command still working. It is simply added to create early validation.

Comment (ellismg) [reply cli/azd/pkg/auth/guard.go:18]: This feels like a good implementation of this pattern to me.  It feels very idiomatic to use the discard as we do here https://github.com/Azure/azure-dev/pull/1570/files#diff-cd0cee372992ad11f4b9477111cf0e3025989cb13454ec6a2d3a140f0b8c81bbR112 to express that we only care about the side-effects of the component being injected, similar to when we import packages to just their `init()` methods.  I think `LoggedInGuard` is a good name.  I like the `Guard` suffix to express this pattern.

File: cli/azd/cmd/env.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (weikanglim) [reply cli/azd/cmd/env.go:278]: It's to move validation logic closer to the `action`. The `command` layer should mostly contain presentational stuff. Having it at the command layer results in having an `action` working for the individual case, but not when it is referenced by some other command (think aliases and composite).

File: cli/azd/pkg/auth/guard.go (hunk 4 above)
Comment (vhvb1989) [reply cli/azd/pkg/auth/guard.go]: Can we use a more general pattern here?  like a `factory` or `builder` to produce the `initAction` ?
Then, any number of `guards` or pre-conditions are implemented within the `object producer` and not as an input for the actual `object`.

**Review by ellismg — APPROVED** [review]
LGTM - I personally like the approach of solving this via the injected guard instead of via middleware, I think it makes the code easier to reason about locally.

File: cli/azd/cmd/env.go [hunk 5]
```diff
@@ -276,6 +275,7 @@ type envNewAction struct {
 func newEnvNewAction(
 	azdCtx *azdcontext.AzdContext,
 	userProfileService *azcli.UserProfileService,
+	_ auth.LoggedInGuard,
```
Comment (vhvb1989) [inline cli/azd/cmd/env.go:278]: I am concern about this...  I think this is not a scalable approach..  Do we need to keep adding `Guards structs` as inputs for the constructor?
What if we need to return an error containing the result of all the `guards`?   

What about adding a `type AuthGuard func() error` and changing this line to be `authGuard AuthGuard`.

Then the first lines of `newEnvNewAction` like:
```
if err := authGuard(); err != nil {
   return err
}
```

then use `auth.LoggedInGuard` as the input here, to run the validation.  And register it to the IoC container as the lazy way to create `AuthGuard` .

Comment (weikanglim) [reply cli/azd/cmd/env.go:276]: > What if we need to return an error containing the result of all the guards?

Let's deal with that if we need that flexibility. I can't imagine when we would not want `LoggedInGuard` to not return `not logged in`, and instead wanted `not logged in | and something else failed`. The tradeoff is more boilerplate vs. flexibility. Neither of those are tradeoffs that we can correctly value, since we don't know the exact requirements.

File: cli/azd/pkg/auth/guard.go (hunk 4 above)
Comment (weikanglim) [reply cli/azd/pkg/auth/guard.go]: I'm going to land this for now so that we correctly fix `login` errors for `azd up` for the next release.

I'd be happy to talk to you @vhvb1989 to figure out the design here. I suspect it comes down to minute differences that won't actually impact us. And if we need to make changes here, it'd be a few lines of code that we could easily adjust to.

> Then, any number of guards or pre-conditions are implemented within the object producer and not as an input for the actual object.

This is actually the current behavior. You can examine this by noticing that you are able to construct an `action` with the default `LoggedInGuard` struct and it works correctly. The `producer` is the one that is performing the pre-validation.

Abstractly, adding the guard to the constructor is the same as defining a dependency. However, the dependency is only used for side-effects and not actually to be used as a component. This is no different than how constructing a normal struct would work -- not all options are stored as instance variables in the constructed struct.
