### PR TITLE
Extensions: Adds execute permissions to extension binary artifact during installation

### LINKED ISSUE #4901: Extension commands not working in Linux environments
After installing `microsoft.azd.demo` in a Linux Dev Container, none of the `azd demo` commands are working:

Image

Upon further inspection inside `~/.azd/extensions/microsoft.azd.demo`, the binary appears to be missing execute permissions. Running `chmod +x` on the binary appears to fix the issue:

Image

### PR DESCRIPTION
**Pull request by wbreza**
Resolves #4901

### CODE REVIEW

File: cli/azd/pkg/extensions/manager.go [hunk 1]
```diff
@@ -426,6 +427,11 @@ func (m *Manager) Install(ctx context.Context, id string, options *FilterOptions
 
 		targetPath := filepath.Join(targetDir, entryPoint)
 
+		// Need to set the executable permission for the binary
+		if err := os.Chmod(targetPath, osutil.PermissionExecutableFile); err != nil {
```
Comment (vhvb1989) [inline cli/azd/pkg/extensions/manager.go:431]: should we add a note about this only applies to Linux?

**Review by vhvb1989 — APPROVED** [review]

**Review by JeffreyCA — APPROVED** [review]
Thanks for fixing this!
