### PR TITLE
fix bug on dotnet target port for empty result or message after config

### LINKED ISSUE #3657: handle dotnet publish output with extra messages
source: https://teams.microsoft.com/l/message/19:b03568be02b5407cbdf49203a1b5af68@thread.tacv2/1712338055409?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=f2e0b0b6-f130-46fa-8ec6-2ef4a7168ed2&parentMessageId=1712338055409&teamName=.NET%20Aspire&channelName=Azure%20Deployment&createdTime=1712338055409

azd runs `dotnet publish` and parses the output to get the targetPort from it.
If the output from stdout contains more than the json response, the json marshaller fails.

Fix the azd parsing logic to remove anything after the end of json response.  For example, split the stdout with `\n\r\n\r` and take only the first element, assuming there's always an empty line after the json response, like

```
{
  "someJson": 1234
}

some extra response
```

### PR DESCRIPTION
**Pull request by hemarina**
fix #3657

### CODE REVIEW

**Review by vhvb1989 — APPROVED** [review]

**Review by rajeshkamal5050 — CHANGES_REQUESTED** [review]
Don't think this is a blocker for 1.8.0. Let's merge after tomorrows release.

File: cli/azd/pkg/tools/dotnet/dotnet.go [hunk 1]
```diff
@@ -205,18 +206,31 @@ func (cli *dotNetCli) PublishContainer(
...
 	var configOutput responseContainerConfiguration
 
+	// make sure result only contains json config output
+	result = strings.Split(result, "\n\r\n\r")[0]
+
+	// if empty string or there's no config output
+	if result == "" || !strings.Contains(result, "{\"config\":") {
+		return 0, &azcli.ErrorWithSuggestion{
+			Err: fmt.Errorf("empty dotnet configuration output"),
+			Suggestion: fmt.Sprintf("project '%s' isn't enabled for container support. To enable SDK "+
```
Comment (rajeshkamal5050) [inline cli/azd/pkg/tools/dotnet/dotnet.go:228]: `EnableSdkContainerSupport ` Could be one of the reasons for an empty dotnet config? Should we also surface the error from the dotnet command too?

**Review by rajeshkamal5050 — APPROVED** [review]
