### PR TITLE
Deventer context / config fix

### LINKED ISSUE #3366: ADE projects with `platform: deventer` should set platform configuration
If platform type is set to `devcenter` in the azure.yaml then azd should automatically leverage all the devcenter platform components including provision provider.

```yaml
# azure.yaml

name: todo-nodejs-mongo-aca
metadata:
    template: todo-nodejs-mongo-aca@0.0.1-beta
services:
    api:
        project: ./src/api
        host: containerapp
        language: js
    web:
        project: ./src/web
        host: containerapp
        language: js
platform:
    type: devcenter # <- this should be enough to init devcenter mode
    config:
        catalog: Example
        environmentDefinition: XXX
        name: XXX
```

**Expected**
When devcenter is set in the azure.yaml, this should enable devcenter mode and provision via devcenter provision provider

**Actual**
Standard IaC (bicep) provision provider is invoked

**Workaround**
Set devcenter mode globally by running `azd config set platform.type devcenter`

### PR DESCRIPTION
**Pull request by wbreza**
Resolves #3366 

This fixes an issue where the ADE configuration was not being refreshed during `azd init` or `azd provision` command while prompting and collecting the required ADE configuration metadata.

### CODE REVIEW

File: cli/azd/cmd/container.go [hunk 1]
```diff
@@ -179,13 +179,13 @@ func registerCommonDependencies(container *ioc.NestedContainer) {
 	})
 
 	// Azd Context
-	container.MustRegisterSingleton(azdcontext.NewAzdContext)
+	container.MustRegisterSingleton(func(lazyAzdContext *lazy.Lazy[*azdcontext.AzdContext]) (*azdcontext.AzdContext, error) {
```
Comment (wbreza) [inline cli/azd/cmd/container.go:182]: @ellismg I believe these changes get us closer to what you were seeing where we will be better off resolving the instance from the shared lazy instead of the other way around.

File: cli/azd/pkg/devcenter/environment_store.go [hunk 2]
```diff
@@ -174,7 +177,19 @@ func (s *EnvironmentStore) Reload(ctx context.Context, env *environment.Environm
...
+		}
+	}
+
+	if s.config.EnvironmentType != "" {
+		if err := env.Config.Set(DevCenterEnvTypePath, s.config.EnvironmentType); err != nil {
+			return err
+		}
+	}
+
+	return s.local.Save(ctx, env)
```
Comment (wbreza) [inline cli/azd/pkg/devcenter/environment_store.go:192]: Allows local environment configuration to update the project/env type if not already set.

File: cli/azd/pkg/devcenter/platform.go [hunk 3]
```diff
@@ -45,7 +45,7 @@ func (p *Platform) IsEnabled() bool {
 // ConfigureContainer configures the IoC container for the devcenter platform components
 func (p *Platform) ConfigureContainer(container *ioc.NestedContainer) error {
 	// DevCenter Config
-	container.MustRegisterSingleton(func(
+	container.MustRegisterTransient(func(
```
Comment (wbreza) [inline cli/azd/pkg/devcenter/platform.go:48]: Since the ADE config is now registered as a transient we must update the consumers of the config as well so that a new fresh config can be constructed with all the updated metadata.

File: cli/azd/cmd/container.go (hunk 1 above)
Comment (vhvb1989) [reply cli/azd/cmd/container.go:182]: Is it OK to think that, whenerver a `azdcontext.AzdContext` is requested from the container, the container will first create a lazy[AzdContext] to gets the azdContext from?  

Can you help me understand:
- When do I want to inject an AzdContext v/s a Lazy[AzdContext].  I feel like, with this change, everything is updated to use Lazy[AzdContext] ?  (becase AzdContext is becoming a pointer to a lazy[AzdContext]) ?

Comment (wbreza) [reply cli/azd/cmd/container.go:182]: The use case is to still use the standard `AzdContext` to be injected in most situations.  The only times we should be using the lazy is for the conditions where the AzdContext may not yet be available and need to be re-evaluated later in the component.

The idea here is that our IoC container will take a nil return and cache it for future resolutions.  This isn't ideal and for the components like AzdContext, ProjectConfig and other similar constructs if we depend on the Lazy[T] then it will allow the resolver to always return the same lazy value that may or not have a value.  Then when the lazy does return a valid value other callers will have the correct instance.  I will create a couple unit tests to illustrate this point.

File: cli/azd/cmd/container_test.go [hunk 4]
```diff
@@ -0,0 +1,88 @@
...
+)
+
+func Test_Lazy_Project_Config_Resolution(t *testing.T) {
+	ctx := context.Background()
+	container := ioc.NewNestedContainer(nil)
+	ioc.RegisterInstance(container, ctx)
+
+	registerCommonDependencies(container)
+
+	// Register the testing lazy component
```
Comment (weikanglim) [inline cli/azd/cmd/container_test.go:20]: YMMV, but if we wanted a more direct test, we could validate `Lazy[*project.ProjectConfig].GetValue() == *project.ProjectConfig` by resolving these instances directly without introducing the additional `testLazyComponent` and `testConcreteComponent`.

Comment (wbreza) [reply cli/azd/cmd/container_test.go:20]: Yes - that would be more straight forward but wanted the test to resolve via the IoC container that more closely aligns to how components take dependencies on these components.
