### PR TITLE
Fix flaky test `TestDefaultDockerOptions`

### LINKED ISSUE #204: [Issue] transient failure during release pipeline run
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `release pipeline`** 
```
Error Trace:          framework_service_docker_test.go:73 
Error:                   Not equal: 
                            expected: "Building docker image" 
                            actual  : "" 

                            Diff: 
                            --- Expected 
                            +++ Actual 
                            @@ -1 +1 @@ 
                            -Building docker image 
                            + 
Test: TestDefaultDockerOptions 
--- FAIL: TestDefaultDockerOptions (0.02s)
```

**Describe the bug**
The pipeline run should not fail since PR passed all tests and merged. Error traced from `TestDefaultDockerOptions` under `framework_service_docker_test.go`.

**To Reproduce**
Manually run [release pipeline](https://dev.azure.com/azure-sdk/internal/_build?definitionId=4643) on main.

**Expected behavior**
Could someone investigate this transient failure to validate if this is not hiding larger issues?

**Environment**
Information on your environment:
    * Language name and version
    * IDE and version : [e.g. Visual Studio 16.3]

### PR DESCRIPTION
**Pull request by weikanglim**
Add synchronization to remove non-determistic assertions.

Fixes #204

Verified that the test still passes with introduced delay (it was failing before)
```golang
go func() {
		for value := range progress {
                        time.Sleep(10 * time.Seconds) // Add delay to verify determistic program
			status = value
			progressMessages = append(progressMessages, value)
		}
		done <- struct{}{}
	}()
```

### CODE REVIEW

File: cli/azd/pkg/project/framework_service_docker_test.go [hunk 1]
```diff
@@ -54,23 +54,27 @@ services:
...
-			status = value
+			progressMessages = append(progressMessages, value)
 		}
+		done <- struct{}{}
 	}()
 
 	framework := NewDockerProject(service.Config, &env, docker, internalFramework)
 	res, err := framework.Package(ctx, progress)
+	close(progress)
+	<-done
```
Comment (vhvb1989) [inline cli/azd/pkg/project/framework_service_docker_test.go:72]: could this be a death lock? 
 for example, if `framework.Package()` never sends a message, would we still be able to exit the blocking for-range on the top to call `done <- struct{}{}` ??

I wonder if we should better use `sync.WaitGroup` and use 2 routines here. One that calls `framerowk.Package` and another one that do the `for-range` to handle messages???

**Review by vhvb1989 — APPROVED** [review]

File: cli/azd/pkg/project/framework_service_docker_test.go (hunk 1 above)
Comment (weikanglim) [reply cli/azd/pkg/project/framework_service_docker_test.go:72]: No. The `for-range` loop on the channel is terminated by us closing the channel here, not by the number of messages sent. So the case for 0 messages is the same for n. 
1. The goroutine for-range on channel blocks waiting for a message.
2. If a message gets sent, it's processed. If not, it blocks waiting for a message.
3. When the channel is closed (guaranteed here on 71), the goroutine for-range stops iteration.
4. The goroutine sends the `done` message.
5. We wait for the `done` message as a signal that the goroutine is done.
6. We continue execution.
