### PR TITLE
Include external command output in errors in all cases

### LINKED ISSUE #2197: Running bicep fails in a completely blank ubuntu container
Use this dockerfile: 

```Dockerfile
FROM ubuntu

# Add basic requirements
RUN apt update && apt install -y curl git

# Install Node (required for azd commands to work)
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - &&\
    apt-get install -y nodejs

# Install azd 
RUN curl -fsSL https://aka.ms/install-azd.sh | bash

# Produces the bicep error
RUN mkdir azd-test \
    && cd azd-test \
    && azd init --template Azure-Samples/todo-nodejs-mongo \
    && azd provision

```

Error message: 

```
#0 2.026 Downloading Bicep
#0 4.821
#0 4.821 ERROR: creating provisioning manager: error creating infra provider: error creating provider for type 'bicep' : checking bicep version: signal: aborted
```

Running the downloaded bicep gets you: 

```
Process terminated. Couldn't find a valid ICU package installed on the system. Please install libicu using your package manager and try again. Alternatively you can set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support. Please see https://aka.ms/dotnet-missing-libicu for more information.
...
```

And this can be solved by setting the environment variable 

```
DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
```

It might make sense for us to do this directly in our code if we envision running in this kind of environment.

### PR DESCRIPTION
**Pull request by ellismg**
Previously, we only added the output from standard out and standard error in cases where the command we ran called exit() cleanly. In other cases, we would not include this information.

This did not work well in practice, for example, dotnet applications will exit via a signal (`SIGABRT`) if `libicu` is not installed on a linux machine, after printing very helpful text to standard error, which we would not include.

This changes our logic so that we always include this output, when we have it. So instead of:

```
ERROR: initializing provisioning manager: initializing infrastructure provider: failed resolving IaC provider 'bicep': checking bicep version: signal: aborted
```

To (the much longer, but much more helpful):

```
ERROR: initializing provisioning manager: initializing infrastructure provider: failed resolving IaC provider 'bicep': checking bicep version: signal: aborted, stdout: , stderr: Process terminated. Couldn't find a valid ICU package installed on the system. Please install libicu (or icu-libs) using your package manager and try again. Alternatively you can set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support. Please see https://aka.ms/dotnet-missing-libicu for more information.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode+Settings..cctor()
   at System.Globalization.GlobalizationMode+Settings.get_Invariant()
   at System.Globalization.GlobalizationMode.get_Invariant()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CultureInfo.get_CurrentCulture()
   at System.Globalization.NumberFormatInfo.get_CurrentInfo()
   at System.Reflection.AssemblyNameParser.ParseVersion(System.String)
   at System.Reflection.AssemblyNameParser.Parse()
   at System.Reflection.AssemblyNameParser.Parse(System.ReadOnlySpan`1<Char>)
   at System.Reflection.AssemblyName.ParseAsAssemblySpec(Char*, Void*)
   at System.RuntimeTypeHandle.<GetTypeByNameUsingCARules>g____PInvoke|80_0(UInt16*, System.Runtime.CompilerServices.QCallModule, System.Runtime.CompilerServices.ObjectHandleOnStack)
   at System.RuntimeTypeHandle.<GetTypeByNameUsingCARules>g____PInvoke|80_0(UInt16*, System.Runtime.CompilerServices.QCallModule, System.Runtime.CompilerServices.ObjectHandleOnStack)
   at System.RuntimeTypeHandle.GetTypeByNameUsingCARules(System.String, System.Runtime.CompilerServices.QCallModule, System.Runtime.CompilerServices.ObjectHandleOnStack)
   at System.RuntimeTypeHandle.GetTypeByNameUsingCARules(System.String, System.Reflection.RuntimeModule)
   at System.Reflection.CustomAttributeTypedArgument.ResolveType(System.Reflection.RuntimeModule, System.String)
   at System.Reflection.CustomAttributeTypedArgument..ctor(System.Reflection.RuntimeModule, System.Reflection.CustomAttributeEncodedArgument)
   at System.Reflection.RuntimeCustomAttributeData.get_ConstructorArguments()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetDynamicallyAccessedMemberTypes(System.Type)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.ValidateTrimmingAnnotations(System.Type, System.Type[], System.Type, System.Type[])
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.Populate()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory..ctor(System.Collections.Generic.ICollection`1<Microsoft.Extensions.DependencyInjection.ServiceDescriptor>)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(System.Collections.Generic.ICollection`1<Microsoft.Extensions.DependencyInjection.ServiceDescriptor>, Microsoft.Extensions.DependencyInjection.ServiceProviderOptions)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(Microsoft.Extensions.DependencyInjection.IServiceCollection, Microsoft.Extensions.DependencyInjection.ServiceProviderOptions)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(Microsoft.Extensions.DependencyInjection.IServiceCollection)
   at Microsoft.Extensions.Logging.LoggerFactory.Create(System.Action`1<Microsoft.Extensions.Logging.ILoggingBuilder>)
   at Bicep.Cli.Program.CreateLoggerFactory(Bicep.Cli.IOContext)
   at Bicep.Cli.Program.ConfigureServices(Bicep.Cli.IOContext)
   at Bicep.Cli.Program..ctor(Bicep.Cli.IOContext, System.Action`1<Microsoft.Extensions.DependencyInjection.IServiceCollection>)
   at Bicep.Cli.Program+<Main>d__3.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Bicep.Cli.Program+<Main>d__3, bicep, Version=0.17.0.0, Culture=neutral, PublicKeyToken=null]](<Main>d__3 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[Bicep.Cli.Program+<Main>d__3, bicep, Version=0.17.0.0, Culture=neutral, PublicKeyToken=null]](<Main>d__3 ByRef)
   at Bicep.Cli.Program.Main(System.String[])
   at Bicep.Cli.Program.<Main>(System.String[])
```

Fixes #2197

### CODE REVIEW

**Comment by ellismg** [comment]
Interested in your thoughts on this one, @weikanglim.  It seems like even in the case of non `exit()` style process termination, the standard our and standard error strings are going to be useful to have.  We did log this information under `--debug` already, so it was possible to get at it, it just was less discoverable for users.

File: cli/azd/pkg/exec/util_test.go [hunk 1]
```diff
@@ -144,7 +144,7 @@ func TestError(t *testing.T) {
 
 	var exitErr *ExitError
 	require.ErrorAs(t, err, &exitErr)
-	require.Contains(t, exitErr.Error(), "exit code: 2, stdout:")
+	require.ErrorContains(t, exitErr, "exit status 2, stdout:")
```
Comment (weikanglim) [inline cli/azd/pkg/exec/util_test.go:147]: This was one part I left in when I did the error code refactoring work, because:
1. Exit code seems like the more intuitive term over exit status.
2. We want a greppable error message that shows that a tool error occurred. This may be useful for our support engineers. I was explaining to current engineers this way: "If there is an 'exit code' in the error text, it means the failure happened in a third-party tool"

Reverting back to "exit code: 2" gets us number 1, but curious how we can solve number 2, given that we're expanding to include non-exit code errors. Maybe it sits at a higher level, where we do "running tool <x>"? or the likes?

Comment (ellismg) [reply cli/azd/pkg/exec/util_test.go:147]: Thanks, the context here is helpful.  I will go back to making the implementation of our ExitError use "exit code" and not "exit status" when that is the reason for exit.  The grepabilty argument makes sense to me, I'll include a note in a comment.

Comment (ellismg) [reply cli/azd/pkg/exec/util_test.go]: @weikanglim made a change here, let me know what you think.

**Review by weikanglim — APPROVED** [review]
