### PR TITLE
Fix duplicated output for spinner updates in non-tty scenarios

### LINKED ISSUE #3254: Duplicate output from the spinner when the console is a not a terminal
When running `azd` under a dumb terminal (i.e. in CI, when the output is redirected to a file, or by setting `AZD_DEBUG_FORCE_NO_TTY`) we end up duplicating output from the spinner, and you see logs like this:

```
Analyzing Aspire Application (this might take a moment...)
Analyzing Aspire Application (this might take a moment...)
 
Provisioning Azure resources (azd provision)
Provisioning Azure resources can take some time.
 
Initialize bicep provider
Initialize bicep provider
Reading subscription and location from environment...
Reading subscription and location from environment...
Subscription: Azure SDK Developer Playground (faa080af-c1d8-40ad-9cce-e1a450ca5b57)
Location: East US 2
 
Creating a deployment plan
Comparing deployment state
Comparing deployment state
Comparing deployment state
  (-) Skipped: Didn't find new changes.
 
SUCCESS: There are no changes to provision for your application.
Analyzing Aspire Application (this might take a moment...)
Analyzing Aspire Application (this might take a moment...)
 
Deploying services (azd deploy)
 
Deploying service apiservice
Deploying service apiservice (Publishing .NET project)
Deploying service apiservice (Publishing .NET project)
Deploying service apiservice (Logging in to registry)
Deploying service apiservice (Logging in to registry)
Deploying service apiservice (Pushing container image)
Deploying service apiservice (Pushing container image)
Deploying service apiservice (Updating container app)
Deploying service apiservice (Updating container app)
Deploying service apiservice (Fetching endpoints for container app service)
Deploying service apiservice (Fetching endpoints for container app service)
Deploying service apiservice (Fetching endpoints for container app service)
  (✓) Done: Deploying service apiservice
  - Endpoint: https://apiservice.internal.politecoast-a4a22abf.eastus2.azurecontainerapps.io/
 
Deploying service webfrontend
Deploying service webfrontend (Publishing .NET project)
Deploying service webfrontend (Publishing .NET project)
Deploying service webfrontend (Logging in to registry)
Deploying service webfrontend (Logging in to registry)
Deploying service webfrontend (Pushing container image)
Deploying service webfrontend (Pushing container image)
Deploying service webfrontend (Updating container app)
Deploying service webfrontend (Updating container app)
Deploying service webfrontend (Fetching endpoints for container app service)
Deploying service webfrontend (Fetching endpoints for container app service)
Deploying service webfrontend (Fetching endpoints for container app service)
  (✓) Done: Deploying service webfrontend
  - Endpoint: https://webfrontend.politecoast-a4a22abf.eastus2.azurecontainerapps.io/
 
 
SUCCESS: Your application was deployed to Azure in 1 minute 19 seconds.
You can view the resources created under the resource group rg-matell-aspire-vsserver in Azure Portal:
https://portal.azure.com/#@/resource/subscriptions/faa080af-c1d8-40ad-9cce-e1a450ca5b57/resourceGroups/rg-matell-aspire-vsserver/overview
```

Note that some lines are not duplicated, because they are written directly instead of by the spinner.

@weikanglim mentioned to me that he bumped into this when attempting to implement an accessible UX for `azd` and thinks this is happening because the spinner registers `.Message()` as a data update, which will `paint()` once. And calling `.Start()` always triggers a `paint()` and a link to some of the yacspin code: https://github.com/theckman/yacspin/blob/94bad55b335440e123c27d15d1b288841dc96f6e/spinner.go#L692-L724

We should try to fix this issue so that consumers of our output stream don't have to debounce output.

### PR DESCRIPTION
**Pull request by weikanglim**
The spinner library we're using triggers a paint update when any data update occurs in non-tty scenarios. This unfortunately results in a lot of unexpected extra output in non-tty scenarios.

With this change, we sidestep the issues here by being more careful on how we use the spinner and add tests to verify the desired behavior. Perhaps down the line we could consider addressing this cleanly with our own spinner implementation.
 
Fixes #3254

Post-change output:
image
image

### CODE REVIEW

**Review by ellismg — APPROVED** [review]
LGTM - Thanks for the fix here!

File: cli/azd/pkg/input/console.go [hunk 1]
```diff
@@ -711,6 +700,33 @@ func NewConsole(noPrompt bool, isTerminal bool, w io.Writer, handles ConsoleHand
 	return c
 }
 
+// IsTerminal returns true if the given file descriptors are attached to a terminal,
+// taking into account of environment variables that force TTY behavior.
+func IsTerminal(stdoutFd uintptr, stdinFd uintptr) bool {
+	// User override to force non-TTY behavior
+	if os.Getenv("AZD_DEBUG_FORCE_NO_TTY") == "1" {
```
Comment (ellismg) [inline cli/azd/pkg/input/console.go:707]: FWIW - if we want to use `ParseBool` here, totally happy with that - the reason it was `== 1` was this was one of the first debug environment flags we added, and I had forgotten about the `ParseBool` pattern.  If anyone was wondering why we were slightly inconsistent here.

Comment (weikanglim) [reply cli/azd/pkg/input/console.go]: Sure!
