### PR TITLE
Fixes running python scripts with virtual environment activation

### LINKED ISSUE #3927: Error initializing AI project
When attempting to run `azd deploy` with a project that contains a `host: ai.endpoint` the user receives an error when initializing the AI project

**Error:**
```bash
ERROR: failed deploying service 'chat': flow operation failed: failed to run Python script: exit code: 1, stdout: , stderr: Traceback (most recent call last):
  File "C:\Users\xxxxx\.azd\bin\ai\pf_client.py", line 8, in <module>
    from promptflow.azure import PFClient
ModuleNotFoundError: No module named 'promptflow.azure'
````

It appears that the python virtual environment is not be activated correct since the `requirements.txt` file correctly contains the referenced module.

### PR DESCRIPTION
**Pull request by wbreza**
Fixes an issue activating python virtual environment within Windows.

Resolves #3927

This basically aligns both Windows & Posix implementations with the `RunList(...)` function with a slightly different environment activation command.

### CODE REVIEW

File: cli/azd/pkg/tools/python/python.go [hunk 1]
```diff
@@ -110,40 +109,23 @@ func (cli *PythonCli) Run(
...
-	if runErr != nil {
-		return nil, fmt.Errorf("failed to run Python script: %w", runErr)
+	runCmd := strings.Join(append([]string{pyString}, args...), " ")
+	// We need to ensure the virtual environment is activated before running the script
+	commands := []string{envActivationCmd, runCmd}
+	runArgs := exec.NewRunArgs("").WithCwd(workingDir)
+	runResult, err := cli.commandRunner.RunList(ctx, commands, runArgs)
+
+	if err != nil {
+		return nil, fmt.Errorf("failed to run Python script: %w", err)
```
Comment (vhvb1989) [inline cli/azd/pkg/tools/python/python.go:128]: should it say `failed to activate python virtual environment` ?

**Review by vhvb1989 — APPROVED** [review]
