### PR TITLE
Fixes Federated credentials conflict in Github Pipelines

### LINKED ISSUE #1482: Azd pipeline config - github provider - Federated credential - 409 conflict
Azd fails when trying to set up federated credential for a new repository using `main` as federated credential if the credential already exists

vivazqu@ubuntu22:~/workspace/build/pp$ azdd pipeline config --principal-name viva-fooo

Configure your azd pipeline

  (✓) Done: Checking current directory for Git repository
  (✓) Done: Creating or updating service principal viva-fooo

ERROR: failed configuring authentication: failed creating federated credential: POST https://graph.microsoft.com/v1.0/applications/bdec736f-4453-4545-abd9-2a87a8631f0a/federatedIdentityCredentials
--------------------------------------------------------------------------------
RESPONSE 409: 409 Conflict
ERROR CODE: Request_MultipleObjectsWithSameKeyValue
--------------------------------------------------------------------------------
{
  "error": {
    "code": "Request_MultipleObjectsWithSameKeyValue",
    "message": "FederatedIdentityCredential with name main already exists.",
    "innerError": {
      "date": "2023-02-02T21:29:38",
      "request-id": "d60c4453-57cc-4363-b006-d1c69fc1e732",
      "client-request-id": "d60c4453-57cc-4363-b006-d1c69fc1e732"
    }
  }
}
--------------------------------------------------------------------------------

Repro:

```to repro:

azdd pipeline config --principal-name a-name-for-principal

then

azdd pipeline config --principal-name a-name-for-principal --remote-name extraremote

*When azd ask if you want to create a new private repo, select yes
```

### PR DESCRIPTION
**Pull request by wbreza**
Minor fixes for `Github` pipeline provider

- Resolves #1482 - Create unique federated credential name

### CODE REVIEW

File: cli/azd/pkg/commands/pipeline/github_provider.go [hunk 1]
```diff
@@ -719,6 +722,17 @@ func (p *GitHubCiProvider) configurePipeline(
...
+	if githubToken != "" {
+		console.Message(ctx,
+			fmt.Sprintf(
+				"%s\n%s",
+				output.WithWarningFormat("WARNING: A value was detected for the 'GITHUB_TOKEN' environment variable."),
+				"Having this variable set can interfere with GitHub integration if not properly configured.",
+			),
+		)
+	}
+
```
Comment (vhvb1989) [inline cli/azd/pkg/commands/pipeline/github_provider.go:735]: You can remove this...

What we do in azd is to detect this env var and remove it from the env when running `gh cli` commands.

I am working on a fix to improve that approach,, as we are currenly only doing it when trying to set a secret.. but it should be right from the beggining... as `azd pipeline config` requires more elevated permissions than the ones granted to the GITHUB_TOKEN

**Review by vhvb1989 — APPROVED** [review]
