### PR TITLE
Store numeric values with leading zeros in `.env` correctly

### LINKED ISSUE #2307: azd env refresh alters numeric string value in .env file
**Output from `azd version`**
azd version 1.0.0 (commit ed2244cb62e7940ec5aceb3b68ea49158272dd7e)

**Describe the bug**
azd env refresh alters numeric string value in .env file

**To Reproduce**

1. Define a variable in the .env file. For instance: `AZURE_SUFFIX="01"`
2. Run the command: `azd env refresh`

**Expected behaviour**
I expect the `AZURE_SUFFIX` value to remain as `"01"` after running the command.

**Actual behaviour**
However, after running the command, the value of `AZURE_SUFFIX` is changed to `1`, effectively removing the leading zero.

### PR DESCRIPTION
**Pull request by ellismg**
The package we are using for storing values in a `.env` file has some surprising behavior where numeric like values are stored as unquoted strings with any leading zero dropped (since the value is round tripped via `strconv.Atoi` and then `fmt.Sprintf` with a `%d` format directive.

This leads to issues where if you have a bicep file that does something like:

```bicep
output NUMBER_WITH_LEADING_ZERO string = '01'
```

The value stored in the `.env` file will be just `1` instead of `01`.

This change addresses this issue by detecting the case and ensuring that we store the raw value in the .env file (after wrapping it with quotes).

Fixes #2307

### CODE REVIEW

**Review by wbreza — APPROVED** [review]
That is a weird quirk.  Thanks for the fix.

File: cli/azd/pkg/environment/environment.go [hunk 1]
```diff
@@ -269,11 +269,28 @@ func (e *Environment) Save() error {
...
+		return fmt.Errorf("saving .env: %w", err)
+	}
+	defer envFile.Close()
+
+	// Write the contents (with a trailing newline, and sync the file, as godotenv.Write)
+	if _, err := envFile.WriteString(marshalled + "\n"); err != nil {
+		return fmt.Errorf("saving .env: %w", err)
+	}
+
+	_ = envFile.Sync() // intentionally ignore error, as godotenv.Write does.
```
Comment (weikanglim) [inline cli/azd/pkg/environment/environment.go:292]: Doesn't `godotenv.Write` return the error from `Sync()`, but not from `Close()`? reading [here](https://github.com/joho/godotenv/blob/e3b6eee84d15b0fa274078565ca46591f5e08876/godotenv.go#L159)

File: cli/azd/pkg/environment/environment.go [hunk 2]
```diff
@@ -337,3 +354,33 @@ func (e *Environment) Environ() []string {
...
 	return envVars
 }
+
+// fixupUnquotedDotenv is a workaround for behavior in how godotenv.Marshal handles numeric like values.  Marshaling
+// a map[string]string to a dotenv file, if a value can be successfully parsed with strconv.Atoi, it will be written in
+// the dotenv file without quotes and the value written will be the value returned by strconv.Atoi. This can lead to dropping
+// leading zeros from the value that we persist.
+//
+// For example, given a map with the key value pair ("FOO", "01"), the value returned by godotenv.Marshal will have a line
+// that looks like FOO=1 instead of FOO=01 or FOO="01".
```
Comment (weikanglim) [inline cli/azd/pkg/environment/environment.go:364]: We chose `FOO="01"` instead of `FOO=01` here. I'm not sure if there are implications between the two choices, but maybe good to elaborate here.

**Review by weikanglim — APPROVED** [review]
Thanks for fixing a tricky bug!

File: cli/azd/pkg/environment/environment.go (hunk 1 above)
Comment (ellismg) [reply cli/azd/pkg/environment/environment.go:292]: You are correct that they are doing that now.  I was looking at the code we referenced (v1.4.0) inside VS Code (using the go to definition feature to look at the source in the module cache) and so I [saw something different](https://github.com/joho/godotenv/blob/v1.4.0/godotenv.go#L150-L166)

Given that upstream has moved forward, I'll move to this.  It's much nicer anyway.

File: cli/azd/pkg/environment/environment.go (hunk 2 above)
Comment (ellismg) [reply cli/azd/pkg/environment/environment.go:364]: I'll add something to explain why I made the somewhat arbitrary choice here.  Looking at the history of the project, they used to always just wrap all strings with quotes, and then moved away for that for numbers.  I think that the leading zeros that have a semantic meaning bias us towards using quotes here.
