### PR TITLE
Detect and update environment changes

### LINKED ISSUE #1714: env variables created in preprovision script are not passed to provision
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:
azd version 0.7.0-beta.1 (commit 9ce71659f7688d0dc3dda8b84e5accedca58cf01)

**Describe the bug**
I am setting an env var in a preprovision script called `MY_PUBLIC_IP`
I am reading that env var in main.parameters.json 
```
    "myPublicIp": {
      "value": "${MY_PUBLIC_IP}"
    },
```

and passing it to main.bicep
```
@description('My public IP address')
param myPublicIp string
```

Then on to a bicep module during provisioning in the `allowedSingleIPs` param:
```
module postgresServer 'core/database/postgresql/flexibleserver.bicep' = {
  name: postgresServerName
  scope: resourceGroup
  params: {
    name: '${prefix}-postgresql'
    location: location
    tags: tags
    sku: {
      name: 'Standard_B1ms'
      tier: 'Burstable'
    }
    storage: {
      storageSizeGB: 32
    }
    version: '14'
    administratorLogin: postgresUser
    administratorLoginPassword: databasePassword
    activeDirectoryAuth: 'Enabled'
    databaseNames: [ postgresDatabaseName ]
    allowAzureIPsFirewall: true
    allowedSingleIPs: [ myPublicIp ]
    aadAdmin: aadAdmin
  }
}

```

However, when I look at the Inputs in the Deployment Center in the Portal, the value is blank:
image

Other values I am passing from env vars that are created when the azd env is created, are able to be passed through, but new ones I create in a preprovision script are not.

**To Reproduce**
See instructions above

**Expected behavior**
If I create an env var in a pre provision script, I expect to be able to reference it in the main.parameters.json and use it in my provision step.

**Environment**
Information on your environment:
    * Language name and version
    * IDE and version : [e.g. Visual Studio 16.3]

### PR DESCRIPTION
**Pull request by wbreza**
Fixes #1714 

- [x] Ensure that azd environment is updated before and after hook executions.
- [x] Ensures azd environment is synchronized across lazy and non-lazy instances

### CODE REVIEW

File: cli/azd/pkg/environment/environment.go [hunk 1]
```diff
@@ -132,40 +147,6 @@ func (e *Environment) Getenv(key string) string {
 	return os.Getenv(key)
 }
 
-// Reloads environment variables and configuration
-func (e *Environment) Reload() error {
```
Comment (wbreza) [inline cli/azd/pkg/environment/environment.go:136]: Moved to private `reload` method moved to bottom of file.

File: cli/azd/pkg/environment/environment.go [hunk 2]
```diff
@@ -256,3 +230,114 @@ func (e *Environment) Environ() []string {
...
+
+	// Don't setup the watcher if the .env file doesn't exist yet
+	envFilePath := filepath.Join(e.Root, azdcontext.DotEnvFileName)
+	if _, err := os.Stat(envFilePath); errors.Is(err, os.ErrNotExist) {
+		return nil
+	}
+
+	watcher, err := fsnotify.NewWatcher()
+	if err != nil {
+		return fmt.Errorf("failed creating file watcher, %w", err)
```
Comment (weikanglim) [inline cli/azd/pkg/environment/environment.go:247]:
```suggestion
		return fmt.Errorf("failed creating file watcher: %w", err)
```

File: cli/azd/pkg/environment/environment.go [hunk 3]
```diff
@@ -256,3 +230,114 @@ func (e *Environment) Environ() []string {
...
+	// Watch for changes to the environment file
+	go func() {
+		var mutex sync.Mutex
+		var timer *time.Timer
+		waitFor := 100 * time.Millisecond
+
+		for {
+			select {
+			case event, ok := <-e.watcher.Events:
+				if !ok || !event.Has(fsnotify.Write) {
```
Comment (weikanglim) [inline cli/azd/pkg/environment/environment.go:265]: Being more defensive here: it seems that we should terminate the `goroutine` if `!ok`? It means the channel was closed, and there isn't room for recovery even if we continued waiting.

Comment (weikanglim) [reply cli/azd/pkg/environment/environment.go:265]: We should also log when the channel is closed.

File: cli/azd/pkg/environment/environment.go [hunk 4]
```diff
@@ -256,3 +230,114 @@ func (e *Environment) Environ() []string {
...
+					newTimer.Stop()
+
+					mutex.Lock()
+					timer = newTimer
+					mutex.Unlock()
+				}
+
+				timer.Reset(waitFor)
+			case err := <-e.watcher.Errors:
+				log.Printf("error watching environment file: %s\n", err.Error())
```
Comment (weikanglim) [inline cli/azd/pkg/environment/environment.go:299]:
```suggestion
				log.Printf("non-terminating error while watching environment file: %s\n", err.Error())
```

File: cli/azd/pkg/environment/environment.go [hunk 5]
```diff
@@ -256,3 +230,114 @@ func (e *Environment) Environ() []string {
...
+	watcher, err := fsnotify.NewWatcher()
+	if err != nil {
+		return fmt.Errorf("failed creating file watcher, %w", err)
+	}
+
+	if err := watcher.Add(envFilePath); err != nil {
+		return fmt.Errorf("failed watching environment file '%s', %w", envFilePath, err)
+	}
+
+	e.watcher = watcher
```
Comment (weikanglim) [inline cli/azd/pkg/environment/environment.go:254]: Consider adding a mutex to avoid multiple a goroutine leaked from concurrent `Save` calls.

File: cli/azd/pkg/environment/environment.go [hunk 6]
```diff
@@ -256,3 +230,114 @@ func (e *Environment) Environ() []string {
...
+						// This is primarily used to support unit test scenarios so we can avoid adding
+						// arbitrary sleeps timers into the test code.
+						if e.reloadCallback != nil {
+							e.reloadCallback()
+						}
+
+						log.Println("environment reloaded")
+
+						mutex.Lock()
+						timer = nil
```
Comment (weikanglim) [inline cli/azd/pkg/environment/environment.go:287]: Do we need to reset this to `nil`? Wouldn't this this be equivalent to calling `timer.Reset`?

File: cli/azd/pkg/environment/environment.go [hunk 7]
```diff
@@ -256,3 +230,114 @@ func (e *Environment) Environ() []string {
...
+			case event, ok := <-e.watcher.Events:
+				if !ok || !event.Has(fsnotify.Write) {
+					continue
+				}
+
+				// Dedup multiple write events that happen within a short window
+				// A single file write can spawn multiple OS level write events
+				if timer == nil {
+					newTimer := time.AfterFunc(math.MaxInt64, func() {
+						if err := e.reload(); err != nil {
```
Comment (weikanglim) [inline cli/azd/pkg/environment/environment.go:273]: This seems like it could be problematic in some cases, where we no longer observe read errors. Also, now that `reload` is done as a separate goroutine, the wide usage of `e.Values` or `e.Config` is no longer thread-safe.

**Review by weikanglim — CHANGES_REQUESTED** [review]
Overall, the direction (if we want to head down this path of real-time notifications) and implementation makes sense to me, although we need to be careful around thread-safetyness and errors with this path. I was able to look at the core implementation logic and it seemed reasonable.

Before heading this direction though, I'm wondering if we can get out of supporting real-time, out-of-process file notifications. It seems that both `azd` and user should not guarantee that such a mechanism works as a way to communicate `env` file changes.

One observation I have is that the current issue being reported, is due to `hooks` being treated as part of the internal execution flow, and I'd personally prefer a model that attempts to isolate that. In an isolated model, a hook execution should behave as-if `azd` process had handed control back to the OS/user, and only invoked after the script has completed. And thus, the `environment` file should be reloaded before and after script execution. The cost of reloading from disk is minimal and I think is doable. Let's chat more with the team about this and see how we feel. I'm not opposed to the current implementation either, although I worry about the increasing complexity we find ourselves in as a CLI application.

File: cli/azd/pkg/environment/environment.go (hunk 7 above)
Comment (weikanglim) [reply cli/azd/pkg/environment/environment.go:273]: The difference is that we've not made guarantees on `environment` being safe for concurrent user, and we have somewhat limited this exposure (inline with `golang` guidelines) to avoid goroutines. If we ran a race detector, I'd suspect that we don't actually see concurrent modifications of `env` happening in our current codebase.

This feature directly introduces `goroutines` within `environment` itself that is susceptible to races. I'd hence prefer if we wanted to go down this path, we should redesign `environment` with thread-safety in mind. I'm worried that this will come back to bite us in subtle ways.

Comment (wbreza) [reply cli/azd/pkg/environment/environment.go:273]: I've addressed some of your feedback but I am not worried about this issue.  I much prefer an active reload strategy where we detect that a change was made over a passive strategy that we need to manually instrument throughout the code base wherever a reload opportunity could happen.

This addresses #1714 and previous issues #1628 that was resolved with PR #1667.  This is a much cleaner strategy in my opinion and we can address any future concurrency issues in the future if they are ever needed.

File: cli/azd/pkg/environment/environment.go [hunk 8]
```diff
@@ -256,3 +231,123 @@ func (e *Environment) Environ() []string {
...
+						// This is primarily used to support unit test scenarios so we can avoid adding
+						// arbitrary sleeps timers into the test code.
+						if e.reloadCallback != nil {
+							e.reloadCallback()
+						}
+
+						log.Println("environment reloaded")
+
+						mutex.Lock()
+						timer = nil
```
Comment (ellismg) [inline cli/azd/pkg/environment/environment.go:297]: I'm worried that there might be some subtle race here, given that the read of `timer` on L281 is not guarded by a mutex as well.

It seems like there could be a case where we get an event that the file has been written and handling that event could run concurrently with the goroutine managed by the timer created by `time.AfterFunc` which is runner the worker function we have in L283 to L298.

In that would, is it possible for us to see that timer is non nil on L281, and take the branch to line 307, but before calling `timer.Reset` get suspended while the worker function continues to execute which has the side effect of setting timer to nil when it completes its job of read loading the environment?  If so, would that mean that when the other goroutine wakes up and tries to call `timer.Reset` timer is now nil and we would crash?

**Review by ellismg — COMMENTED** [review]
I'm having some trouble understanding if this is truly safe or not as I struggle to work through all the interleavings of the goroutine that is handling the reads from the watcher channel and the goroutine spawned by the timer when it is actually time to do the re-load.

Similar to @weikanglim's feedback, I think it's conceptually simpler if we don't use watching here (which brings in all these concurrency concerns) and instead take the strategy of just forcing a reload in the hooks case when a hook returns.  I feel like that makes it easier for us to understand exactly when the state of the system changes, even if it means a little extra thought at development time when we are dealing with external components.

File: cli/azd/pkg/azdo/service_connection.go [hunk 9]
```diff
@@ -81,7 +81,7 @@ func CreateServiceConnection(
 	ctx context.Context,
 	connection *azuredevops.Connection,
 	projectId string,
-	azdEnvironment environment.Environment,
+	azdEnvironment *environment.Environment,
```
[the remark this answers is not in the document]
Comment (ellismg) [reply cli/azd/pkg/azdo/service_connection.go:84]: Good catch!

File: cli/azd/pkg/environment/environment.go (hunk 8 above)
Comment (wbreza) [reply cli/azd/pkg/environment/environment.go]: Rolled back watch fix for now.
