### PR TITLE
bug fix for error handling workflow

### LINKED ISSUE #5712: No detailed error information is reported for azd commands and Bicep syntax errors when LLM alpha feature is enabled for PR#5521
**Describe the issue:**
After enabling `azd config set alpha.llm on`, it was discovered that when an azd command encountered an error, the CLI did not output a specific error message and simply exited, making it difficult to locate and fix the problem. For example:

1. The template name is misspelled.
Running `azd init -t todo-nodejs-mogno-aks -b staging` , due to a misspelling of the template name (it should be `mongo` instead of `mogno`), the CLI does not output a specific error message and simply exits.
Image

2. There is a Bicep file syntax error.
When the `main.bicep` file contains the incorrect format of `param useAPIM bool = 'false'`, running `azd up` also results in no error message and a direct exit.
Image

**Repro Steps:**
1. Run `azd init -t todo-csharp-sql-swa-func -b staging`.
2. Run `azd config set alpha.llm on`.
3. Run `azd auth login`.
4. Modify the parameter definitions in the main.bicep file to incorrect formats.
5. Run `azd up`.

**Environment:**
- OS: Windows, Codespaces, Mac.
- Azd version: azd version 1.19.0-pr.5328305 (commit 7a6ea4496c2367b652e7f236da6ab39bccd1681e).
- Template: `todo-csharp-sql-swa-func `, `todo-java-mongo-aca `, `todo-nodejs-mongo-aca `, `todo-python-mongo`.

**Expected behavior:**
The detailed error messages for azd commands and Bicep syntax errors are reported after enabling LLM alpha features.

@rajeshkamal5050 and @hemarina for notification.

### PR DESCRIPTION
**Pull request by hemarina**
fix #5712

### CODE REVIEW

File: cli/azd/cmd/middleware/ux.go [hunk 1]
```diff
@@ -41,7 +40,7 @@ func (m *UxMiddleware) Run(ctx context.Context, next NextFn) (*actions.ActionRes
 	// Stop the spinner always to un-hide cursor
 	m.console.StopSpinner(ctx, "", input.Step)
 
-	if err != nil && !m.featuresManager.IsEnabled(llm.FeatureLlm) {
+	if err != nil {
```
Comment (hemarina) [inline cli/azd/cmd/middleware/ux.go:43]: This causes the silence failure if errors happened before for loop in ux.go. This condition was fixing a bug on UX printed twice and I confirm that the bug is not hit after removing it.

**Review by weikanglim — APPROVED** [review]
