### PR TITLE
Fix subscription ID being hashed in telemetry

### LINKED ISSUE #1586: [Issue] Hashed subscription IDs in telemetry
We are currently sending all command events with hashed sub IDs

### PR DESCRIPTION
**Pull request by weikanglim**
Subscription IDs shouldn't be hashed. This change fixes that.

Also, adding E2E tests that verify the usage telemetry data being logged to prevent these types of regressions.

Fixes #1586

### CODE REVIEW

File: cli/azd/test/snapshot/snapshot.go [hunk 1]
```diff
@@ -2,6 +2,8 @@
 // Licensed under the MIT License.
 
 // Package snapshot contains adapters that azd uses to create snapshot tests.
+// By default, snapshots are stored under testdata. To change this behavior, customize the config created by
```
Comment (ellismg) [inline cli/azd/test/snapshot/snapshot.go:5]: ❤️

File: cli/azd/test/functional/telemetry_test.go [hunk 2]
```diff
@@ -0,0 +1,197 @@
...
+	err := copySample(dir, "restoreapp")
+	require.NoError(t, err, "failed expanding sample")
+
+	traceFilePath := filepath.Join(dir, "trace.json")
+
+	_, err = cli.RunCommandWithStdIn(
+		ctx,
+		stdinForTests(envName),
+		"restore", "--service", "csharpapptest",
+		"--trace-log-file", traceFilePath)
```
Comment (ellismg) [inline cli/azd/test/functional/telemetry_test.go:120]: Glad this was useful here!

**Review by ellismg — APPROVED** [review]
Love the new test, glad we were able to leverage the OTel stuff in this way.
