### PR TITLE
Update agent fix with user feedback, use SendMessageWithRetry, and classify fixable errors 

### LINKED ISSUE #7104: Revisit UserContextError and MachineContextError categories for fixable errors after Copilot SDK implementation
## Summary

After the Copilot SDK is implemented, we need to revisit the error categorization in `classifyError()` ([cmd/middleware/error.go](https://github.com/Azure/azure-dev/blob/main/cli/azd/cmd/middleware/error.go)) for `UserContextError` and `MachineContextError`.

Currently, errors classified under these two categories are **not** sent for full agentic analysis and automated fix (only `AzureContextAndOtherError` is eligible). However, some of these errors are actually **fixable** by the agent and should be reconsidered once the Copilot SDK provides richer capabilities.

### UserContextError (potentially fixable)
Some user-context errors that could be auto-remediated:
- `auth.ReLoginRequiredError` / `auth.AuthFailedError` — agent could guide or trigger re-authentication
- `auth.ErrNoCurrentUser` / `azapi.ErrAzCliNotLoggedIn` / `azapi.ErrAzCliRefreshTokenExpired` — agent could prompt login flow
- `environment.ErrNotFound` / `environment.ErrNameNotSpecified` / `environment.ErrDefaultEnvironmentNotFound` — agent could help create or select an environment
- `pipeline.ErrAuthNotSupported` / `pipeline.ErrRemoteHostIsNotAzDo` / `pipeline.ErrRemoteHostIsNotGitHub` — agent could suggest configuration changes

### MachineContextError (potentially fixable)
Some machine-context errors that could be auto-remediated:
- `tools.MissingToolErrors` — agent could suggest or run install commands
- `tools.ErrSemver` (version mismatch) — agent could suggest upgrade commands
- `maven.ErrPropertyNotFound` — agent could help fix Maven configuration

## Action Items
- [ ] Review each error in `UserContextError` and `MachineContextError` categories
- [ ] Determine which errors the Copilot SDK agent can realistically fix or guide the user through
- [ ] Introduce a sub-classification (e.g., `Fixable` vs `NonFixable`) or promote fixable errors to `AzureContextAndOtherError`
- [ ] Update `classifyError()` logic and corresponding tests in `error_test.go`

## Context
- Error classification: `cli/azd/cmd/middleware/error.go` (lines 55-116)
- Tests: `cli/azd/cmd/middleware/error_test.go`
- The three categories today: `AzureContextAndOtherError` (agentic fix), `MachineContextError` (local env), `UserContextError` (user config/auth)

### PR DESCRIPTION
**Pull request by hemarina**
- fix #7104 
- add user feedback input prompt after fix

This pull request refactors the error handling middleware to introduce a clearer distinction between "fixable" and "non-fixable" errors, and adds a new "Fix this error" troubleshooting option. It updates the logic for classifying errors, modifies the user interaction flow, and improves the templates and tests to reflect these changes.

**Error classification and handling:**

- Replaces the previous `classifyError` function with `fixableError`, which determines if an error is fixable by the agent. The logic for what constitutes a fixable error has been updated, and the error classification now directly controls whether agent-driven troubleshooting is offered. [[1]](diffhunk://#diff-5294771c77c06b46393aa790a35b195d4691bc96e73ab05f94c002d5cebd0ca9L92-R96) [[2]](diffhunk://#diff-5294771c77c06b46393aa790a35b195d4691bc96e73ab05f94c002d5cebd0ca9L132-R108)
- The middleware now skips agent troubleshooting for errors that are not fixable, preventing unnecessary prompts for errors that cannot be automatically resolved.

**User interaction and troubleshooting options:**

- Adds a new troubleshooting category, `categoryFix`, allowing users to directly request an agent-driven fix for an error. Updates the prompt and selection logic to include this new category. [[1]](diffhunk://#diff-5294771c77c06b46393aa790a35b195d4691bc96e73ab05f94c002d5cebd0ca9R121-R122) [[2]](diffhunk://#diff-5294771c77c06b46393aa790a35b195d4691bc96e73ab05f94c002d5cebd0ca9L411-R397) [[3]](diffhunk://#diff-5294771c77c06b46393aa790a35b195d4691bc96e73ab05f94c002d5cebd0ca9R414-L430)
- Updates the troubleshooting flow to use the new fix category, including bypassing the "Would you like to fix this?" prompt if the user has already selected "Fix this error." [[1]](diffhunk://#diff-5294771c77c06b46393aa790a35b195d4691bc96e73ab05f94c002d5cebd0ca9L278-R277) [[2]](diffhunk://#diff-5294771c77c06b46393aa790a35b195d4691bc96e73ab05f94c002d5cebd0ca9L310-R301)

**Templates and agent prompts:**

- Updates the `fix.tmpl` template to call an additional tool (`azd_provision_common_error`) before troubleshooting and adds a step for user feedback after the fix is applied. [[1]](diffhunk://#diff-cecdb2b1454e469f679f41b794018f93ea3e02ec69a0092932e4685f719360bdL10-R11) [[2]](diffhunk://#diff-cecdb2b1454e469f679f41b794018f93ea3e02ec69a0092932e4685f719360bdR21-R23)
- Updates the `explain.tmpl` template to clarify the instructions for the agent, ensuring no fix steps are proposed in the explanation-only mode.
- Removes the obsolete `troubleshoot_fixable.tmpl` template.

**Testing updates:**

- Refactors and expands tests to cover the new `fixableError` logic, ensuring all error types are properly classified as fixable or not, and updates tests to reflect the new troubleshooting flow and constants. [[1]](diffhunk://#diff-0b3fc39a1670d55af0252fdc8377bb09306454eedb56312918c2ffffd54a120cL260-R376) [[2]](diffhunk://#diff-0b3fc39a1670d55af0252fdc8377bb09306454eedb56312918c2ffffd54a120cR406) [[3]](diffhunk://#diff-4a99eed98c14b99365ca33d458d24c06fab45b114baf0ab2f51dd6e889aa8980L970-R978)
- Updates imports in test files to match new error classification logic.

**Code cleanup:**

- Removes unused imports related to error types that are no longer referenced in the new error classification logic. [[1]](diffhunk://#diff-5294771c77c06b46393aa790a35b195d4691bc96e73ab05f94c002d5cebd0ca9L26-L27) [[2]](diffhunk://#diff-5294771c77c06b46393aa790a35b195d4691bc96e73ab05f94c002d5cebd0ca9L38-L39)

### CODE REVIEW

**Review by vhvb1989 — APPROVED** [review]

File: cli/azd/cmd/middleware/error.go [hunk 1]
```diff
@@ -266,55 +241,67 @@ func (e *ErrorMiddleware) Run(ctx context.Context, next NextFn) (*actions.Action
...
+			span.SetStatus(codes.Error, "agent.send_message.failed")
 			return nil, err
 		}
 
-		span.SetStatus(codes.Ok, "agent.fix.completed")
-		e.displayUsageMetrics(ctx, fixResult)
+		span.SetStatus(codes.Ok, fmt.Sprintf("agent.%s.completed", category))
+		e.displayUsageMetrics(ctx, agentResult)
+
+		if category != categoryFix {
```
Comment (jongio) [inline cli/azd/cmd/middleware/error.go:258]: **[HIGH]** Logic: `previousError` never set when user selects "Fix this error"

When `categoryFix` is selected, `previousError = originalError` (line 293) is skipped because it's inside this block. On the next loop iteration, the repeat-error detection:

```go
if previousError != nil && originalError.Error() == previousError.Error() {
    attempt++
}
```

...never fires because `previousError` stays nil. The 3-attempt safety limit is bypassed - the loop runs forever when the user picks "Fix this error" + "Retry" on the same error.

Fix: move `previousError = originalError` to just before this `if`, and remove the duplicate from line 293.

Comment (wbreza) [inline cli/azd/cmd/middleware/error.go:258]: **[HIGH]** `previousError` never set for `categoryFix` — retry limit bypassed

Agreeing with @jongio's finding. When the user selects "Fix this error" (`categoryFix`), `previousError = originalError` (line 293) is inside the `if category != categoryFix` block and is never reached. The 3-attempt safety limit relies on `previousError` being non-nil:

```go
if previousError != nil && originalError.Error() == previousError.Error() {
    attempt++
}
```

Since `previousError` stays nil, `attempt` never increments, and the loop runs indefinitely when the same error recurs after "Fix this error" + "Retry".

**Suggested fix:** Move `previousError = originalError` before the `if category != categoryFix` branch so it's set regardless of the selected category.

File: cli/azd/cmd/middleware/error.go [hunk 2]
```diff
@@ -266,55 +241,67 @@ func (e *ErrorMiddleware) Run(ctx context.Context, next NextFn) (*actions.Action
...
 		// Step 1: Category selection — user chooses the troubleshooting scope
 		category, err := e.promptTroubleshootCategory(ctx)
 		if err != nil {
 			span.SetStatus(codes.Error, "agent.category.failed")
 			return nil, fmt.Errorf("prompting for troubleshoot category: %w", err)
 		}
 
+		// No need to return error message again as it is already printed above
+		// just return to the main message loop for next steps
 		if category == categorySkip {
```
Comment (wbreza) [inline cli/azd/cmd/middleware/error.go:238]: **[MEDIUM]** `return nil, nil` changes exit code behavior

This previously returned `actionResult, originalError` (non-zero exit code). Now returns `nil, nil` (zero exit code). The error IS already printed, but scripts/CI pipelines checking `True` or `%ERRORLEVEL%` for failures will silently pass.

The same pattern at line 248 (non-fixable errors) also returns `nil, nil`.

Consider returning `actionResult, originalError` to preserve the non-zero exit code, matching the original behavior. The error won't be double-printed since the middleware has already displayed it.

File: cli/azd/cmd/middleware/error.go [hunk 3]
```diff
@@ -89,38 +85,15 @@ const (
 	UserContextError
 )
 
-// classifyError categorizes an error into one of three buckets:
-// AzureContextAndOtherError, MachineContextError, or UserContextError
-func classifyError(err error) ErrorCategory {
+func fixableError(err error) bool {
```
Comment (wbreza) [inline cli/azd/cmd/middleware/error.go:70]: **[MEDIUM]** Dead code: `ErrorCategory` type and constants

`ErrorCategory` with `AzureContextAndOtherError`, `MachineContextError`, and `UserContextError` are still defined but have zero references after `classifyError` was replaced by `fixableError`. Consider removing them.
