### PR TITLE
Fix `azd down` deletion logic

### LINKED ISSUE #619: `azd down` does not delete an empty resource group environment
This was caught in CI runs as we were leaking resource groups per each test run.

To reproduce:
`go test -v -timeout 30m -run ^Test_CLI_ResourceGroupNameWithoutEnvNameTag$`

Look for the resource group in Portal with the unique hex string created. Notice that this resource group is empty, but still around even though the test runs `azd down` at the end of the test execution.

### PR DESCRIPTION
**Pull request by weikanglim**
Improve `azd down` deletion logic, addressing two issues:

1. Change how resource groups were fetched from an ARM deployment. Previously, we relied on `deployment.DependsOn.ResourceName` to determine resource groups. This did not work for empty resource groups, as described in #619. This change modifies the logic to summarize resource groups based on `deployment.OutputResources` instead. Schema of deployment is documented [here](https://learn.microsoft.com/en-us/rest/api/resources/deployments/get#deploymentpropertiesextended). From observation, it includes all resources across resource groups from a subscription-level deployment. A sanitized example return response for `Microsoft.Resources/deployment` for a subscription-level deployment grabbed from running `azd up` on a ToDo template is available [here](https://gist.github.com/weikanglim/435f0840b92978c4438b2a857dfdb837)
2. Fix the deletion logic, where resource groups that were already deleted, would have caused a failure in deletion. Deletion should be idempotent, and if a resource group is already deleted, it should be ignored.

I had ran into this trying to run `azd provision` and `azd down` on an empty skeleton starter.

Fixes #619

### CODE REVIEW

File: cli/azd/pkg/infra/azure_resource_manager.go [hunk 1]
```diff
@@ -129,10 +130,11 @@ func (rm *AzureResourceManager) GetResourceGroupsForDeployment(
 	// unique set.
 	resourceGroups := map[string]struct{}{}
 
-	for _, dependency := range deployment.Properties.Dependencies {
-		for _, dependent := range dependency.DependsOn {
-			if *dependent.ResourceType == string(AzureResourceTypeResourceGroup) {
-				resourceGroups[*dependent.ResourceName] = struct{}{}
+	for _, resourceId := range deployment.Properties.OutputResources {
```
Comment (weikanglim) [inline cli/azd/pkg/infra/azure_resource_manager.go:133]: I can also keep the existing logic if we're thinking that it may help in corner-cases. Let me know.

**Review by vhvb1989 — APPROVED** [review]

**Comment by weikanglim** [comment]
Going to do some additional testing here once I have some time to test out some scenarios.

**Review by ellismg — APPROVED** [review]
