### PR TITLE
Purge option works with `azd down --force --purge`

### LINKED ISSUE #1018: Only one Key Vault is purged after running AZD down
**Output from `azd version`**
```
azd version 0.3.0-beta.5 (commit 38169d7067ac73dc4e214e6913bee5e5359b8b15)
```

**Output from `az version`** 
```
{
  "azure-cli": "2.41.0",
  "azure-cli-core": "2.41.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "containerapp": "0.3.13",
    "log-analytics": "0.2.2",
    "rdbms-connect": "1.0.4"
  }
}
```

**Describe the bug**
Deployed an app that has 2 Key Vault resources. After running `azd down --no-prompt --force --purge` we're seeing that only one of two KV resources was purged

**To Reproduce**
1. run azd init
2. choose todo-csharp-sql
3. add a 2nd Key Vault instance
```
module keyVault2 './core/security/keyvault.bicep' = {
  name: 'keyvault2'
  params: {
    environmentName: environmentName
    location: location
    principalId: principalId
    keyVaultName: '${toLower(uniqueString(subscription().id, environmentName, location))}kv2'
  }
}
```
4. run azd provision
5. run 'azd down --no-prompt --force --purge'

**Expected behavior**
Expected both vaults to be removed

**Environment**
Information on your environment:
    * PwSh 7.2.7

### PR DESCRIPTION
**Pull request by hemarina**
fix #1018

### CODE REVIEW

File: cli/azd/pkg/infra/provisioning/bicep/bicep_provider_test.go [hunk 1]
```diff
@@ -543,8 +614,9 @@ func prepareDestroyMocks(mockContext *mocks.MockContext) {
 
 	// Purge App configuration
 	mockContext.HttpClient.When(func(request *http.Request) bool {
-		return request.Method == http.MethodPost && strings.Contains(request.URL.Path,
-			"deletedConfigurationStores/ac-123/purge")
+		return request.Method == http.MethodPost && (strings.Contains(request.URL.Path,
```
Comment (ellismg) [inline cli/azd/pkg/infra/provisioning/bicep/bicep_provider_test.go:617]: NIT: Could you see if it is possible to insert the newlines between the boolean operators and not in the `strings.Contains` calls itself?

For example, it might read a little cleaner if we can structure it like this:

```go
return request.Method == http.MethodPost &&
   (strings.Contains(request.URL.Path, "deletedConfigurationStores/ac-123/purge") ||
    strings.Contains(request.URL.Path, "deletedConfigurationStores/ac2-123/purge"))
```

File: cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go [hunk 2]
```diff
@@ -479,13 +479,13 @@ func (p *BicepProvider) purgeItems(
 		if err != nil {
 			return err
 		}
-
-		for _, item := range items {
-			if err := item.purge(); err != nil {
-				return fmt.Errorf("failed to purge %s: %w", item.resourceType, err)
-			}
+	}
+	for _, item := range items {
```
Comment (ellismg) [inline cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go:483]: Let's remember to call this out in the release notes as an issue we fixed, because it is user facing.

File: cli/azd/pkg/infra/provisioning/bicep/bicep_provider_test.go [hunk 3]
```diff
@@ -493,6 +518,29 @@ func prepareDestroyMocks(mockContext *mocks.MockContext) {
 		}, nil
 	})
 
+	mockContext.HttpClient.When(func(request *http.Request) bool {
+		return request.Method == http.MethodGet && strings.Contains(request.URL.Path, "/vaults/kv2-123")
+	}).RespondFn(func(request *http.Request) (*http.Response, error) {
```
Comment (ellismg) [inline cli/azd/pkg/infra/provisioning/bicep/bicep_provider_test.go:523]: Something to consider in the future - since there's a lot of duplication here - we could always add something like:

```go
func respondFnForKeyVault(name string) func(request *http.Request) (*http.Response, error) {
    return func(request *http.Request) (*http.Response, error) {
		keyVaultResponse := armkeyvault.VaultsClientGetResponse{
			Vault: armkeyvault.Vault{
				ID:       convert.RefOf(name ),
				Name:     convert.RefOf(name),
				Location: convert.RefOf("eastus2"),
				Properties: &armkeyvault.VaultProperties{
					EnableSoftDelete:      convert.RefOf(true),
					EnablePurgeProtection: convert.RefOf(false),
				},
			},
		}

		keyVaultBytes, _ := json.Marshal(keyVaultResponse)

		return &http.Response{
			StatusCode: http.StatusOK,
			Body:       io.NopCloser(bytes.NewBuffer(keyVaultBytes)),
		}, nil
    }
}
```

And then do something like:

```go
mockContext.HttpClient.When(func(request *http.Request) bool {
		return request.Method == http.MethodGet && strings.Contains(request.URL.Path, "/vaults/kv2-123")
	}).RespondFn(respondFnForKeyVault("kv2-123")
```

As a way to remove the duplication.

**Review by ellismg — APPROVED** [review]
LGTM!  Excellent sleuthing finding the incorrectly indented code and finding the issue that the test we had before was actually wrong and not validating the purged the key vaults and app configuration resources.

**Review by vhvb1989 — APPROVED** [review]
Add changelog entry please.

File: cli/azd/pkg/infra/provisioning/bicep/bicep_provider_test.go (hunk 3 above)
Comment (wbreza) [reply cli/azd/pkg/infra/provisioning/bicep/bicep_provider_test.go:523]: You may want to do something similar to what I have in https://github.com/Azure/azure-dev/blob/main/cli/azd/test/mocks/graphsdk/mocks.go.

We call these graph mocks in multiple places with multiple values and creating a single method that can handle the variations for testing will allow more cleaner or organized code.

**Review by wbreza — APPROVED** [review]
Looks good - Added some feedback about consolidating your variations of mocks into reusable methods that you can call from multiple tests.
