### PR TITLE
Prefer glibc based Bicep when both musl and glibc are installed

### LINKED ISSUE #2683: [Issue] Bicep installer prefers MUSL variant over glibc
- [ X  ] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
azd version 1.2.0 (commit 99ea7577f0df0df2ba34b677da189fafba18c0f7)

**Describe the bug**
When azd installs its bicep provider, it uses the presence of the MUSL linker on the system to determine whether to install a MUSL based bicep.   See this code here: https://github.com/Azure/azure-dev/blob/ba25a8cdd81cf6b81a1f09c575bdd513eda95a98/cli/azd/pkg/tools/bicep/bicep.go#L167 

I believe this is the same issue in the main Azure CLI as https://github.com/Azure/bicep/issues/5040 which was fixed by only installing the musl-based variant if there is no glibc installed. Could the same fix as made under https://github.com/Azure/azure-cli/pull/23040/files be made here in the developer CLI?  Happy to offer a PR if that would be helpful.

**To Reproduce**
* Install the musl libc toolchain.
* Run `azd up` in a Bicep-based deployment.  Bicep installs but fails to run.

**Expected behavior**

Bicep should be installed for the correct system libc.

**Environment**
WSL Ubuntu 20.04 on Windows 11.

### PR DESCRIPTION
**Pull request by ellismg**
This matches the behavior of the `az` CLI, which uses this same logic. When we orginally implemented this, `az` did not have this special case, it was added later.

Fixes #2683

### CODE REVIEW

File: cli/azd/pkg/tools/bicep/bicep_test.go [hunk 1]
```diff
@@ -137,3 +139,75 @@ func TestNewBicepCliWillUpgrade(t *testing.T) {
 
 	require.Equal(t, []byte(NEW_FILE_CONTENTS), contents)
 }
+
+func Test_preferMuslBicep(t *testing.T) {
```
Comment (ellismg) [inline cli/azd/pkg/tools/bicep/bicep_test.go:143]: Since I thought it was interesting, and I would share it with the team.  I actually generated most of this test with the help of Copilot Chat.  My prompt was:

> Write me a table drive test for the preferMuslBicep function.  There should be three cases, once where the stat call returns true for musl and false for glibc, one where it returns false for musl and true for glibc and one where it returns true for both.  The test should ensure that preferMuslBicep returns the correct value in each case.

I ended up having to make some changes to the generated test, but overall, I was impressed with the sketch that it gave me.

Comment (vhvb1989) [reply cli/azd/pkg/tools/bicep/bicep_test.go:143]: I know that @weikanglim loves the `table drive` tests;  in my case, I don't :)

Is there a way to run each test from the table individually?  

This is of course, a nit, and thank you for sharing the prompt <3.

**Review by vhvb1989 — APPROVED** [review]

File: cli/azd/pkg/tools/bicep/bicep_test.go (hunk 1 above)
Comment (ellismg) [reply cli/azd/pkg/tools/bicep/bicep_test.go:143]: > Is there a way to run each test from the table individually?

Yes, there is.  There are two options:

1. If you are running `go test` by hand, you can use the `-run` flag, to provide a filter for test names.  Since subtests work by appending / and then test name, you could do something like:

```
matell@Matts-Work-MacBook bicep% pwd 
/Users/matell/dd/azure/azure-dev/cli/azd/pkg/tools/bicep
matell@Matts-Work-MacBook bicep%  go test -run Test_preferMuslBicep/musl_preferred .
ok  	github.com/azure/azure-dev/cli/azd/pkg/tools/bicep	0.119s
```

The other option, which is a little more friendly (and makes things easier to debug) is to use the Testing pane in VS Code.  You can go to the package test and then run everything.  At that point, you should see the subtests show up (it has to run once for VS Code to understand what subtests exist) but you can see individual results of any subtest and debug that exact invocation if you want (in this screenshot, I hacked the test so one of the subtests failed):

image

Once you run the tests once in VS, the `Test_preferMuslBicep` will turn into something that can be expanded.  You can right click on any subtest and do a run or debug.

I think this feature in VS Code is new within the last few months, I don't remember it previously being this easy to run individual subtests, but it is pretty nice now!

Hopefully the ergonomics are nice enough that you like table driven tests a little more now 😄.

**Review by wbreza — APPROVED** [review]
