### PR TITLE
Fix error in `deploy` with multiple resource groups

### LINKED ISSUE #689: Error from `azd deploy` if there are two resource groups
**Output from `azd version`**
```bash
azd version 0.2.0-beta.1 (commit 817a81ab44ac788ec2d3050e94ba0138c3a80ac3)
```

**Output from `az version`** 
```bash
{
  "azure-cli": "2.40.0",
  "azure-cli-core": "2.40.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "containerapp": "0.3.5",
    "log-analytics": "0.2.2",
    "rdbms-connect": "1.0.2"
  }
}
```

**Describe the bug**
After running an `azd deploy` I'm seeing an error even though the operation seems to have completed successfully.

In this scenario there are two resource groups deployed by `azd provision` and to inform `azd` how to proceed I'm using the **AZURE_RESOURCE_GROUP** env var to specify the resource group. The error message looks like:

```
Error: discovering resource group from deployment: more than one possible resource group was found. please explicitly specify your resource group in azure.yaml or the AZURE_RESOURCE_GROUP environment variable
```

**To Reproduce**
1. `azd init`
2. Choose a template (I chose todo-csharp-cosmos-sql) 
3. name the environment **mytestenvname**
4. Open `main.bicep` and add the following

```bicep

resource resourceGroup2 'Microsoft.Resources/resourceGroups@2021-04-01' = if (false) {
  name: '${abbrs.resourcesResourceGroups}${name}2'
  location: location
  tags: tags
}

```

5. Run `azd provision`
6. Run `azd env set AZURE_RESOURCE_GROUP rg-mytestenvname`
6. Run `azd deploy --service web`
9. Observe - The web app was deployed but the command returns an error

**Expected behavior**
Expected the deployment to finish without error.

**Environment**
Information on your environment:
    * Ran from bash ubuntu on WSL2

**Additional context**
Started happening after upgrading to 0.2.0-beta.1

### PR DESCRIPTION
**Pull request by weikanglim**
Fixes #689

## Background
As part of Terraform refactor, we had switched the display logic to directly use ARM: `resourceManager.FindResourceGroupForEnvironment`. This misses out on the override abilities that the user can provide through `AZURE_RESOURCE_GROUP` or specifying a `resourceGroup` in `azure.yaml` that helps in resolving multiple resource group cases (which `azd` doesn't currently fully support).

## Changes
- Refactor resource group resolution logic to a central place as `project.GetResourceGroup`. `projectConfig.ResourceGroupName` now always refers to the design-time YAML key defined, `project.ResourceGroupName` refers to the runtime resolved resource group name.
- Move display output of created resources from `deploy` to `provision`. The logic being in `deploy` has always been weird as most code deployments don't actually touch the Azure Resources directly.

Manually tested changes to work.

### CODE REVIEW

File: cli/azd/cmd/up.go [hunk 1]
```diff
@@ -23,7 +26,9 @@ func upCmd(rootOptions *internal.GlobalCommandOptions) *cobra.Command {
 				},
 			},
 			&infraCreateAction{
-				rootOptions: rootOptions,
+				// Delay print final output from infra create
+				finalOutputRedirect: &infaCreateFinalOutput,
```
Comment (weikanglim) [inline cli/azd/cmd/up.go:30]: This is pretty hacky but works for us now. Will be resolved when we remove composite actions in favor of well-defined `Action` class in #625

File: cli/azd/pkg/project/project_config.go [hunk 2]
```diff
@@ -99,30 +98,25 @@ func (pc *ProjectConfig) GetProject(ctx *context.Context, env *environment.Envir
...
-	if pc.ResourceGroupName == "" {
-		// We won't have a ResourceGroupName yet if it hasn't been set in either azure.yaml or AZURE_RESOURCE_GROUP env var
-		// Let's try to find the right resource group for this environment
-		resourceManager := infra.NewAzureResourceManager(*ctx)
-		resourceGroupName, err := resourceManager.FindResourceGroupForEnvironment(*ctx, env)
-		if err != nil {
-			return nil, err
-		}
-		pc.ResourceGroupName = resourceGroupName
+	resourceGroupName, err := GetResourceGroupName(*ctx, pc, env)
```
Comment (weikanglim) [inline cli/azd/pkg/project/project_config.go:101]: There isn't anything that was using `projectConfig.ResourceGroupName` which is why this is safe to refactor to `project.ResourceGroupName`

File: cli/azd/cmd/up.go [hunk 3]
```diff
@@ -38,6 +43,16 @@ func upCmd(rootOptions *internal.GlobalCommandOptions) *cobra.Command {
 				},
 			),
 			&deployAction{rootOptions: rootOptions},
+			// Print the final output from infra create
+			commands.ActionFunc(
+				func(ctx context.Context, cmd *cobra.Command, args []string, azdCtx *azdcontext.AzdContext) error {
```
Comment (ellismg) [inline cli/azd/cmd/up.go:48]: Another possible design would be to create an action that both fetches the resource groups and prints the messages to the console and then make `infra create`'s command implementation a composite action that runs `infraCreateAction` and then this new `printResourceGroupsForProjectAction`, and then instead of having the action func here just have a reference to this new action.

That would let us not have to add `finalOutputRedirect` to the state of `infraCreateAction` which might be nice?

Just a thought - I feel like the `finalOutputRedirect` stuff is a little strange, but I totally understand how you ended up with it.

Comment (weikanglim) [reply cli/azd/cmd/up.go:48]: Creating nested actions definitely removes the parameter, but the final design ends up being convoluted still. I think the example is why moving away from these pipelines in favor of procedural code with #625 is the way to go. I do plan on this being short-lived. I'll be making the first refactor attempt to the simplified `Action` in `up` shortly -- this is meant to be a forcing function for myself to start on that work.

I just wanted to get a bug fix out to address the reported issue, and leaving it in `provision` felt wrong as I was updating the code.

Comment (ellismg) [reply cli/azd/cmd/up.go:48]: Makes sense to me!

**Review by ellismg — APPROVED** [review]
Thanks for the quick fix, @weikanglim, LGTM!
