### PR TITLE
Fix java version check for major-only release

### LINKED ISSUE #1077: [Issue] todo-java-mongo template runs error.
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**

azd version 0.4.0-beta.1 (commit 2bf7a529914d86d8e9f5d7b6f95a4f20a2351e01)

**Output from `az version`** 

```json
{
  "azure-cli": "2.40.0",
  "azure-cli-core": "2.40.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "account": "0.2.5",
    "spring": "1.1.10"
  }
}
```

**Describe the bug**

Command `azd up` get error message.

```bash
$ azd up
Error: required external tools are missing:
 - error checking for external tool Java JDK: converting to semver version fails: Version string empty
```

**To Reproduce**

Just follow [Get started using Azure Developer CLI](https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/get-started?tabs=devcontainer&pivots=programming-language-java).

```bash
$ azd init --template todo-java-mongo
Initializing a new project in /Users/jimmy/...

? Please enter a new environment name: my-rg
? Please select an Azure Subscription to use: my-sub
? Please select an Azure location to use: 42. (US) East US 2 (eastus2)
$ azd up
Error: required external tools are missing:
 - error checking for external tool Java JDK: converting to semver version fails: Version string empty
```

**Expected behavior**

`azd up` works good, no error.

**Environment**

MacOS 12.6

**Additional context**

NodeJS template works good for me.

### PR DESCRIPTION
**Pull request by weikanglim**
- For major release of Java, the version reported by `javac` is a major only version. Example output: `javac 19`. This change fixes our CLI version extraction logic to be more flexible in parsing, allowing: `major`, `major.minor` only formats as well.
- On extremely old versions of Java, (Java 8 and below) `javac --version` is not recognized. This change fixes the error output to be the version check validation failure.

Fixes #1077

### CODE REVIEW

File: cli/azd/pkg/tools/tool.go [hunk 1]
```diff
@@ -60,11 +61,36 @@ func ExecuteCommand(ctx context.Context, cmd string, args ...string) (string, er
...
+	}
+
+	return semver.Version{}, fmt.Errorf("no valid version number found in %s", cliOutput)
+}
+
+func parseUint(s string) uint64 {
+	res, err := strconv.ParseUint(s, 10, 64)
 	if err != nil {
-		return semver, err
+		panic(err)
```
Comment (vhvb1989) [inline cli/azd/pkg/tools/tool.go:93]: Nit. Using log.panic() allow us to set a message with the error

**Review by vhvb1989 — APPROVED** [review]

**Review by wbreza — APPROVED** [review]

File: cli/azd/pkg/tools/tool.go (hunk 1 above)
Comment (weikanglim) [reply cli/azd/pkg/tools/tool.go:93]: Will keep that in mind in the future. Think this is fine as-is given that it shouldn't be possible to get into this panic, and that the integer conversion error should have enough context.
