### PR TITLE
aspire: Do not error when other projects present

### LINKED ISSUE #3024: When running `azd init` on a non-Aspire directory it gives an incorrect error message
_transfered from https://github.com/dotnet/aspire/issues/930_

**Output from `azd version`**
azd version 1.5.0 (commit 012ae734904e0c376ce5074605a6d0d3f05789ee)

**Describe the bug**
When running `azd init` on a solution that has an Aspire app it detects it but kinda gives a wrong helpful error:
`ERROR: only a single Aspire project is supported at this time`

If navigating to the correct AppHost directory and run init it works.  The error is misleading and generates confusion.

**To Reproduce**

1. Create new Aspire blank app from VS
2. Add project, choose Blazor, select Server and WebAssembly for interactive mode from VS
3. Build solution
4. Open CLI and navigate to the solution root
5. `azd init`

**Expected behavior**
A helpful error message indicating that nothing could be found or if detecting an Aspire app but the wrong location, provide a helpful hint to the right location

### PR DESCRIPTION
**Pull request by weikanglim**
This change relaxes the project detection logic during `azd init` to warn for projects unreferenced by the app host.

With this change, for dotnet app detection, we also exclude wasm based projects such as BlazorAssembly as hostable. These projects can be referenced by a Blazor server and act as a library.

Fixes #3024

### CODE REVIEW

File: cli/azd/internal/repository/app_init.go [hunk 1]
```diff
@@ -117,22 +116,52 @@ func (i *Initializer) InitFromApp(
...
-		if len(projects) != 1 {
-			return errors.New("only a single Aspire project is supported at this time")
+	var prjAppHost []appdetect.Project
+	for _, prj := range projects {
+		if prj.Language == appdetect.DotNetAppHost {
+			prjAppHost = append(prjAppHost, prj)
+		}
+	}
+
+	if len(prjAppHost) > 1 {
```
Comment (vhvb1989) [inline cli/azd/internal/repository/app_init.go:126]: nit. Consider braking `InitFromApp()` into more than one single long method.

It's currently hard to see what happens if this condition `if len(prjAppHost) > 1` is false...  the code is hidden and there's a lot going on within this decision. Hopefully we could see smaller logic units to review/spot-possible-bugs easier

File: cli/azd/pkg/tools/dotnet/dotnet.go [hunk 2]
```diff
@@ -204,6 +204,10 @@ func (cli *dotNetCli) SetSecrets(ctx context.Context, secrets map[string]string,
 	return nil
 }
 
+// GetMsBuildProperty uses -getProperty to fetch a property after evaluation, without executing the build.
+//
+// This only works for versions dotnet >= 8, MSBuild >= 17.8.
+// On older tool versions, this will return an error.
```
Comment (vhvb1989) [inline cli/azd/pkg/tools/dotnet/dotnet.go:210]: <3

**Review by vhvb1989 — APPROVED** [review]
