### PR TITLE
Return failed error when logging in

### LINKED ISSUE #2221: login doesn't produce non-zero exit code on failure
1. Login should return non-zero exit code when login fails
2. Login should display appropriate error when login fails and not just "not logged in"

### PR DESCRIPTION
**Pull request by weikanglim**
Previously, when `login` fails, there are cases where "Not logged in, run 'azd auth login' to login" would be printed out, but the returned exit code is zero. This is a problem in CI situations when auth isn't setup correctly, and yet `login` is deemed successful, the CI pipeline proceeds as normal, resulting in user confusion.

This change updates `login` to always exit with non-zero exit code if `login` fails. The code has been refactored so that `--check-status` plays nicely with this implementation.

Fixes #2221

### CODE REVIEW

File: cli/azd/cmd/auth_login.go [hunk 1]
```diff
@@ -254,81 +257,103 @@ func (la *loginAction) Run(ctx context.Context) (*actions.ActionResult, error) {
 			"Next time use `azd auth login`.")
 	}
 
-	if !la.flags.onlyCheckStatus {
-		if err := la.accountSubManager.ClearSubscriptions(ctx); err != nil {
-			log.Printf("failed clearing subscriptions: %v", err)
+	if la.flags.onlyCheckStatus {
+		// In check status mode, we always print the final status to stdout.
+		// We print any non-setup related errors to stderr.
```
Comment (weikanglim) [inline cli/azd/cmd/auth_login.go:262]: @ellismg Slight behavioral change here to print unexpected errors to `stderr`. Is this okay for our editor integrations?

File: cli/azd/cmd/auth_login.go [hunk 2]
```diff
@@ -254,81 +257,103 @@ func (la *loginAction) Run(ctx context.Context) (*actions.ActionResult, error) {
...
+			if err != nil {
+				fmt.Fprintln(la.console.Handles().Stdout, "Not logged in, run `azd auth login` to login to Azure.")
+			} else {
+				fmt.Fprintln(la.console.Handles().Stdout, cLoginSuccessMessage)
+			}
+
+			return nil, nil
+		} else {
+			res := contracts.LoginResult{}
+			if err != nil {
```
Comment (vhvb1989) [inline cli/azd/cmd/auth_login.go:282]: Can you try to avoid the 3rd level of `if-else`  
  1) if la.flags.onlyCheckStatus
  2) if la.formatter.Kind() == output.NoneFormat
  3) if err != nil

No one will die if we just keep adding nested code, but it is typically a `code smell` there.  I would try to make it simpler

**Review by vhvb1989 — APPROVED** [review]

File: cli/azd/cmd/auth_login.go [hunk 3]
```diff
@@ -254,81 +257,103 @@ func (la *loginAction) Run(ctx context.Context) (*actions.ActionResult, error) {
...
-			// Service principals do not typically require subscription caching (running in CI scenarios)
-			// We simply clear the cache, which is much faster than rehydrating.
-			err := la.accountSubManager.ClearSubscriptions(ctx)
-			if err != nil {
-				log.Printf("failed clearing subscriptions: %v", err)
-			}
-		}
+// Verifies that the user has credentials stored,
+// and that the credentials stored is accepted by the identity server (can be exchanged for access token).
+func (la *loginAction) verifyLoggedIn(ctx context.Context) (*azcore.AccessToken, error) {
```
Comment (vhvb1989) [inline cli/azd/cmd/auth_login.go:337]: Should we have new unit tests for this method?

File: cli/azd/cmd/auth_login.go [hunk 4]
```diff
@@ -254,81 +257,103 @@ func (la *loginAction) Run(ctx context.Context) (*actions.ActionResult, error) {
...
+	if la.flags.onlyCheckStatus {
+		// In check status mode, we always print the final status to stdout.
+		// We print any non-setup related errors to stderr.
+		// We always return a zero exit code.
+		token, err := la.verifyLoggedIn(ctx)
+		var loginExpiryError *auth.ReLoginRequiredError
+		if err != nil &&
+			!errors.Is(err, auth.ErrNoCurrentUser) &&
+			!errors.As(err, &loginExpiryError) {
+			fmt.Fprintln(la.console.Handles().Stderr, err.Error())
```
[the remark this answers is not in the document]
Comment (weikanglim) [reply cli/azd/cmd/auth_login.go:269]: It's codified in the expected behavior here: `// We always return a zero exit code.`

File: cli/azd/cmd/auth_login.go (hunk 2 above)
Comment (weikanglim) [reply cli/azd/cmd/auth_login.go:282]: The code smell is that the formatter is a pattern that needs some improvements IMO.

File: cli/azd/cmd/auth_login.go (hunk 3 above)
Comment (weikanglim) [reply cli/azd/cmd/auth_login.go:337]: Do you mean integration/component testing? The function itself is fairly straightforward refactored from existing.

I'll think about how we can test login better though.

Comment (weikanglim) [reply cli/azd/cmd/auth_login.go:337]: I've added explicit tests to `login` using service principal. This was already implicitly tested during the pipeline run, but the changes in this direction is good.

I've also started separating out env variables from the test configuration. The V1 is a minimal change. We may want to refactor Live test config separately in the future, but it was the simplest change to write the test without feeling directly coupled.

File: cli/azd/cmd/auth_login.go (hunk 2 above)
Comment (weikanglim) [reply cli/azd/cmd/auth_login.go]: Simplified the behavior here to read better. Thanks for the suggestion.

File: cli/azd/cmd/auth_login.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (vhvb1989) [reply cli/azd/cmd/auth_login.go:269]: how is that comment helping to understand that not returning after an error is expected?

File: cli/azd/cmd/auth_login.go (hunk 1 above)
Comment (ellismg) [reply cli/azd/cmd/auth_login.go:262]: I just looked and this should be fine - they ignore stderr on these paths today.

File: cli/azd/test/functional/cli_test.go [hunk 5]
```diff
@@ -44,10 +44,52 @@ import (
 	"golang.org/x/exp/slices"
 )
 
-const (
-	testSubscriptionId = "2cd617ea-1866-46b1-90e3-fffb087ebf9b"
-	defaultLocation    = "eastus2"
-)
+// The current running configuration for the test suite.
+var cfg = config{}
```
Comment (ellismg) [inline cli/azd/test/functional/cli_test.go:48]: Love this! ❤️

**Review by ellismg — APPROVED** [review]
LGTM - Happy that we fixed this for the login case, but still have `--check-status` return 0 even when we successfully detect you are logged out :-).
