### PR TITLE
fix bug where windows logic app passed `isLinuxWebApp`

### LINKED ISSUE #4071: Deployment to Windows app service has stopped working in 1.9.4
- [ ] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
1.9.4

**Describe the bug**
Between 1.9.3 and 1.9.4, deployment of a .NET web app to a Windows app service has started failing with the error message

`ERROR: failed deploying service 'web': deploying service web: empty deployment status id`

The code being deployed is from a universal package on the same version as before, so I'm certain it isn't our code change reponsible, since there hasn't been any.

**Expected behavior**
Deployment works

**Environment**
Information on your environment:
    * Language name and version
    * IDE and version : [e.g. Visual Studio 16.3]

**Additional context**

I would imagine this has been introduced by https://github.com/Azure/azure-dev/pull/3965 Add deployment status tracking for linux web apps.

Fixing the installed azd version in the ADO install-azd pipeline component to 1.9.3 fixes the problem.

### PR DESCRIPTION
**Pull request by hemarina**
1. Make sure only linux web app triggers new deployment api. `isLinuxWebApp` checks if `LinuxFxVersion` is not null but there're some ambiguous cases like `Windows Logic App` has empty value for `LinuxFxVersion` and null for `WindowsFxVersion`. Kind `app,linux` check and `LinuxFxVersion` != "" is added for `isLinuxWebApp`.
2. Resource Not Found is hit if service type is not linux web app.
4. If new deployment status api failed due to unsupported types or empty deployment status id, we fall back to original deployment method. 

- fix #4071

### CODE REVIEW

File: cli/azd/pkg/tools/azcli/webapp.go [hunk 1]
```diff
@@ -51,7 +51,8 @@ func (cli *azCli) appService(
 
 func isLinuxWebApp(response *armappservice.WebAppsClientGetResponse) bool {
 	if response.Properties != nil && response.Properties.SiteConfig != nil &&
-		response.Properties.SiteConfig.LinuxFxVersion != nil {
+		response.Properties.SiteConfig.LinuxFxVersion != nil &&
+		*response.Properties.SiteConfig.LinuxFxVersion != "" {
```
Comment (weikanglim) [inline cli/azd/pkg/tools/azcli/webapp.go:55]: I'm wondering what `az` is doing currently. I looked at [azure-cli](https://github.com/search?q=repo%3AAzure%2Fazure-cli+linuxFxVersion&type=code&p=1) and didn't find similar logic that would use this property. I'm wondering if that Logic Apps Standard apps will not have either one of these set correctly, so this still isn't 100% reliable. Unfortunately, we're in a hard place where the server APIs have made it almost near impossible for the client to perform the correct functional behavior in all cases -- and some variation of a "best effort" attempt is needed.

The safest way possible is probably to probe the deployment status endpoint and fall back to zip deployment status in cases of some error (probably a 404). I'd recommend checking the exact logic in az and follow those steps since they've likely been "battle tested" for edge cases.

Once again, I'd like to emphasize that these APIs and how they work present many difficult problems that the client now needs to safeguard against, and always result in some degradation for the user in edge cases. On that front, I sympathize very much with our difficult position of holding the end of the stick.

**Comment by vhvb1989** [comment]
created issue for CI/CD: https://github.com/Azure/azure-dev/issues/4076

You can override this check-enforcer

File: cli/azd/pkg/tools/azcli/webapp.go [hunk 2]
```diff
@@ -51,7 +51,8 @@ func (cli *azCli) appService(
 
 func isLinuxWebApp(response *armappservice.WebAppsClientGetResponse) bool {
 	if response.Properties != nil && response.Properties.SiteConfig != nil &&
-		response.Properties.SiteConfig.LinuxFxVersion != nil {
+		response.Properties.SiteConfig.LinuxFxVersion != nil &&
```
Comment (vhvb1989) [inline cli/azd/pkg/tools/azcli/webapp.go:54]: do we want test cases for this new condition (add a test with a mock response returning empty string for LinuxFxVersion

**Review by vhvb1989 — APPROVED** [review]
