### PR TITLE
rzip: handle symbolic linked directories

### LINKED ISSUE #4715: [Issue] Symlinks ignored when zipping for app service deployment
- [/] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
`azd version 1.11.1 (commit ae08ceba17c7078c547df9ee5f97e9e7ceb2fe53)`

**Describe the bug**
We have the following `azure.yaml`:

```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: ai-document-review
metadata:
  template: ai-document-review@1.0.0
infra:
  provider: terraform
services:
  app:
    project: app/api
    host: appservice
    language: python
    hooks:
      # Build the UI code into the API's www directory.
      prepackage:
        shell: sh
        run: 'task app-build-ui'
  flows:
    project: flows
    host: appservice
    language: python
```

The `app` service is a FastAPI Python application, and it consumes a set of common utils in our monorepo from the top-level directory (in a folder called `common`). To reference these we use a symlink within the `app/api` directory:

Image

When trying to deploy the service with `azd up`, we run into the following challenge:

```
ERROR: error executing step command 'package --all': failed packaging service 'app': open /var/folders/kl/dwz9d6xx5jx9s3ygwtqc5q_c0000gn/T/azd2971955672/common: no such file or directory
```

Which I've tracked down to the copy implementation in the cli:

https://github.com/Azure/azure-dev/blob/88ad9bc2cf8e63ef6e0e6b4577770127a162fc3d/cli/azd/pkg/project/project_utils.go#L54 

It seems it uses [this library](https://github.com/otiai10/copy) and doesn't pass any options for:

```go
OnSymlink func(src string) SymlinkAction
```

Which defaults to ignoring them: https://github.com/otiai10/copy/blob/5ef5923d6ff098ea7a51792c1ec963d04fad9794/copy.go#L307

**To Reproduce**
1. Create new Python App Service `azd` template with an appservice service in the `azure.yaml` config
2. Add `common` folder to root and create dummy util
3. Add symlink to common within `src/api` directory
4. Call the util from the api `main.py`
5. `azd up`

**Expected behavior**
Symlinks should be respected and `Deep` copied, or failing that a new option should be introduced to enable this

**Environment**
- Mac M3, Python 3.12.8

### PR DESCRIPTION
**Pull request by weikanglim**
In our previous implementation of `CreateFromDirectory`, symbolic linked directories were not handled correctly and would result in an `os.Stat` error as describe in #4715. Symbolic linked files were handled with `os.Stat` that follows the target.

This change adds support for symbolic linked directory traversal, and accompanying test suite.

Fixes  #4715, Contributes to #4381

### CODE REVIEW

File: cli/azd/pkg/rzip/rzip.go [hunk 1]
```diff
@@ -6,55 +6,129 @@ package rzip
...
-		}
+	return w.Close()
+}
 
-		f, err := w.CreateHeader(header)
+func addDirRoot(
+	w *zip.Writer,
+	src string) error {
+	return addDir(w, "", src, 0)
+}
```
Comment (wbreza) [inline cli/azd/pkg/rzip/rzip.go:34]: nit: I don't think this would violate our line length rule - any reason for wrapping this function signature?

File: cli/azd/pkg/rzip/rzip.go [hunk 2]
```diff
@@ -6,55 +6,129 @@ package rzip
...
+func addDir(
+	w *zip.Writer,
+	destRoot,
+	src string,
+	symlinkDepth int) error {
+	if symlinkDepth > 40 {
+		// too deep, bail out similarly to the 'zip' tool
+		log.Println("skipping", src, "too many levels of symbolic links")
+		return nil
+	}
```
Comment (wbreza) [inline cli/azd/pkg/rzip/rzip.go:45]: Just curious - Is `40` some well-known number to bail out?

File: cli/azd/pkg/rzip/rzip.go [hunk 3]
```diff
@@ -6,55 +6,129 @@ package rzip
...
 	"os"
 	"path/filepath"
 	"strings"
 )
 
+// CreateFromDirectory creates a zip archive from the given directory recursively,
+// that is suitable for transporting across machines.
+//
+// It resolves any symlinks it encounters.
 func CreateFromDirectory(source string, buf *os.File) error {
```
Comment (wbreza) [inline cli/azd/pkg/rzip/rzip.go:19]: Is this common practice of Java or similar where symlinked folders would exist in some packaged artifact?

**Review by wbreza — APPROVED** [review]
A couple questions but otherwise looks good.

File: cli/azd/pkg/rzip/rzip.go (hunk 1 above)
Comment (weikanglim) [reply cli/azd/pkg/rzip/rzip.go:34]: nothing in particular, just keeping it similar in style with other functions here

File: cli/azd/pkg/rzip/rzip.go (hunk 2 above)
Comment (weikanglim) [reply cli/azd/pkg/rzip/rzip.go:45]: yeah, it's `MAXSYMLINKS` in the linux kernel

File: cli/azd/pkg/rzip/rzip.go (hunk 3 above)
Comment (weikanglim) [reply cli/azd/pkg/rzip/rzip.go:19]: It's most common for python, but generally it can be used for monorepo / referencing source from other repos, #4715 was one example

**Review by vhvb1989 — APPROVED** [review]
