### PR TITLE
Fix `azd up --template` so it can initialize a new project

### LINKED ISSUE #1392: Bug when running azd up with a template.
**Output from `azd version`**
0.5.0-beta.2 (commit 4f95806a0a8f5cb4187267ca75dcff8be71fd95d)

**Describe the bug**
When running `azd up --template todo-nodejs-mongo` in an empty directory I receive an error telling me: "no project exists; to create a new project, run `azd init`."

image

**Expected behavior**
Azd should complete the `azd up` command with the `todo-nodejs-mongo` template.

**Environment**
Information on your environment:
    * VS Code Version: 1.70.2

### PR DESCRIPTION
**Pull request by ellismg**
In #1296 we changed our logic such that we would inject `AzdContext` as a depenecy of our actions, and expect our IoC container to wire things up.

This had the side effect of breaking `azd up --template` to initilize (and then provison and deploy) a new project.

The break comes from the fact that the IoC container will call `NewAzdContext` as part of building the `deploy` and `infraCreate` actions, which need to be created because they are dependencies of the `up` composite action.  However, `NewAzdContext` should not be called before the project has actually been created (which will happen when the `up` composite action calls the `init` action), because it looks for an existing project and if it doesn't find one it fails.

To work around this issue - I've made the infra create and deploy actions explicitly call `NewAzdContext` so the calls can happen at the right time.

A regression test has been added (it's a little hacky because we don't actually care about running the `infra create` or `deploy` parts of `up` in this test, we just want to ensure that we correctly initialized via a template.

Fixes #1392

### CODE REVIEW

File: cli/azd/test/functional/cli_test.go [hunk 1]
```diff
@@ -108,6 +108,42 @@ func Test_CLI_Init_CanUseTemplate(t *testing.T) {
...
+	// running this test in parallel is ok as it uses a t.TempDir()
+	t.Parallel()
+	ctx, cancel := newTestContext(t)
+	defer cancel()
+
+	dir := tempDirWithDiagnostics(t)
+
+	cli := azdcli.NewCLI(t)
+	cli.WorkingDirectory = dir
+	cli.Env = append(os.Environ(), "AZURE_LOCATION=eastus2")
```
Comment (wbreza) [inline cli/azd/test/functional/cli_test.go:123]: Another option would be to create this test in the `actions_test.go`.  We don't really care about the result of the command, only that the is able to be instantiated, right?

Comment (wbreza) [reply cli/azd/test/functional/cli_test.go:123]: In the existing tests we always create an `azure.yaml` - that is why this wasn't caught earlier.

**Review by wbreza — APPROVED** [review]
Change looks good for a hotfix & added some feedback on the test.
We should figure out if we need a long term fix for this that still allow us to inject the `AzdContext` in the commands.

File: cli/azd/test/functional/cli_test.go (hunk 1 above)
Comment (ellismg) [reply cli/azd/test/functional/cli_test.go:123]: > Another option would be to create this test in the actions_test.go. We don't really care about the result of the command, only that the is able to be instantiated, right?

Yeah - I think we would be fine just validating you can create the action.  I'll see if I can do something better in `actions_test.go` and remove this.

**Review by rajeshkamal5050 — DISMISSED** [review]
Can you also add it to changelog and the version.txt. So that we can do a hot fix from main itself.

File: cli/azd/CHANGELOG.md [hunk 2]
```diff
@@ -1,14 +1,10 @@
 # Release History
 
-## 0.5.0-beta.3 (Unreleased)
-
-### Features Added
-
-### Breaking Changes
+## 0.5.0-beta.3 (2023-01-13)
 
 ### Bugs Fixed
```
[the remark this answers is not in the document]
Comment (ellismg) [reply cli/azd/CHANGELOG.md:6]: It is already at `0.5.0-beta.3` (https://github.com/Azure/azure-dev/blob/main/cli/version.txt#L1).  It was updated by the helpful bot earlier today: #1376.  I think I want to keep it as 0.5.0-beta.3 because that's the version we are releasing right?

File: cli/azd/test/functional/cli_test.go (hunk 1 above)
Comment (ellismg) [reply cli/azd/test/functional/cli_test.go:123]: I'm going to keep this end to end test as is now - I think there is some value over doing it in `actions_test.go`, we get better coverage and it is closer to one of our main gestures, so I think I want to keep the test for now.
