### PR TITLE
Fixes issue selected environment with different environment type

### LINKED ISSUE #3861: [Issue] Can't get environment outputs when doing `azd env select` in devcenter mode
In devcenter mode, I do an `azd env select <envname>` and when this occurs, an error is returned and the environment does not get set correctly.

image

### PR DESCRIPTION
**Pull request by wbreza**
Fixes #3861

- [x] Fixes comparison check against the specified ADE environment instead of the currently loaded devcenter configuration
- [x] Fixes an issue when creating new environment it automatically copies the project/environment type of the currently loaded environment instead of allowing the user to select new values on next provision. 

What was happening in the linked issue is that the ARM deployment object was comparing the deployment object tags against the currently loaded devcenter environment instead of the found matching devcenter environment.

### CODE REVIEW

File: cli/azd/pkg/devcenter/manager.go [hunk 1]
```diff
@@ -276,7 +276,7 @@ func (m *manager) LatestArmDeployment(
 		// ARM runner deployments contain the deployment tags for the specific environment
 		isArmDeployment := devCenterOk && strings.EqualFold(*tagDevCenterName, config.Name) &&
 			projectOk && strings.EqualFold(*tagProjectName, config.Project) &&
-			envTypeOk && strings.EqualFold(*tagEnvTypeName, config.EnvironmentType) &&
+			envTypeOk && strings.EqualFold(*tagEnvTypeName, env.EnvironmentType) &&
```
Comment (wbreza) [inline cli/azd/pkg/devcenter/manager.go:279]: The comparison should be between the specified environment type and not the current devcenter config.

File: cli/azd/pkg/devcenter/environment_store.go [hunk 2]
```diff
@@ -154,15 +154,23 @@ func (s *EnvironmentStore) Reload(ctx context.Context, env *environment.Environm
...
-	if s.config.Project != "" {
-		if err := env.Config.Set(DevCenterProjectPath, s.config.Project); err != nil {
-			return err
+	_, hasSubscriptionId := env.LookupEnv(environment.SubscriptionIdEnvVarName)
+	_, hasResourceGroupName := env.LookupEnv(environment.ResourceGroupEnvVarName)
+
+	// We only want to persist the project & environment type after the environment has been provisioned.
+	// This allows creating new environments for different projects and/or environment types for the same env definition
+	// instead of using values from the current environment. (Will prompt user to supply these values on provision)
+	if hasSubscriptionId && hasResourceGroupName {
```
Comment (vhvb1989) [inline cli/azd/pkg/devcenter/environment_store.go:163]: should/could we have test cases for this logic?

**Review by vhvb1989 — APPROVED** [review]
nit. consider adding test cases
