### PR TITLE
Fix `azd env get-values` Check environment exists

### LINKED ISSUE #2567: [azd env get-values] should fail if there's not environment
Running `azd env get-values` from a folder that contains `azure.yaml` but does not contain a folder `.azure` (no env) makes azd to prompt to create a new environment.

I think azd should fail and say there is not an env to get values from.. instead of trying to create a new one

### PR DESCRIPTION
**Pull request by john0isaac**
Closes #2567

I have a question here there are two ways we can solve this either by 
implementing the check in the _pkg\environment\azdcontext\azdcontext.go_ file like I did 
implementing the check in the _pkg\environment\\local_file_data_store.go_ file which is the one that has the line that creates the environment. Line: 88 
image

I think it can be wrapped in a check for the environment directory or maybe removed?
I don't know the implications of removing the line that creates a new environment in the Get environment function so I took the safer approach.

Let me know what you think? @vhvb1989, @jongio 

Output before and after implementation
image

### CODE REVIEW

File: cli/azd/pkg/environment/azdcontext/azdcontext.go [hunk 1]
```diff
@@ -117,8 +121,15 @@ func NewAzdContext() (*AzdContext, error) {
 			searchDir = parent
 		} else if err == nil {
 			// We found our azure.yaml file, and searchDir is the directory
-			// that contains it.
-			break
+			// that contains it now we need to check for the environment .azure file.
+			EnvironmentDirectoryPath := filepath.Join(searchDir, EnvironmentDirectoryName)
```
Comment (jongio) [inline cli/azd/pkg/environment/azdcontext/azdcontext.go:125]: I believe we want to use camel casing for var.

File: cli/azd/pkg/environment/azdcontext/azdcontext.go [hunk 2]
```diff
@@ -89,6 +89,10 @@ var (
 	ErrNoProject = errors.New("no project exists; to create a new project, run `azd init`")
 )
 
+var (
+	ErrNoEnvironment = errors.New("no environment found to get values from")
```
Comment (jongio) [inline cli/azd/pkg/environment/azdcontext/azdcontext.go:93]: We may want to include a helper text like we do with ErrNoProject

Comment (john0isaac) [reply cli/azd/pkg/environment/azdcontext/azdcontext.go:93]: I don't know what is the expected action that should happen after this.
Should I ask the user to run azd init to create a new project?

As the issue states we say that but it doesn't mention what is expected to happen after that.
https://github.com/Azure/azure-dev/issues/2567#issue-1819518704

File: cli/azd/pkg/environment/azdcontext/azdcontext.go [hunk 3]
```diff
@@ -117,8 +121,15 @@ func NewAzdContext() (*AzdContext, error) {
 			searchDir = parent
 		} else if err == nil {
 			// We found our azure.yaml file, and searchDir is the directory
-			// that contains it.
-			break
+			// that contains it now we need to check for the environment .azure file.
+			environmentDirectoryPath := filepath.Join(searchDir, EnvironmentDirectoryName)
```
Comment (vhvb1989) [inline cli/azd/pkg/environment/azdcontext/azdcontext.go:125]: This would only check if `.azure` folder exists, but it the folder is empty, azd would keep asking user to create the environment.

Context:

The root-cause of this issue is coming from the current-design of an environment. 
Azd has `environment.Manager` and calls `LoadOrCreateInteractive(env-name)`, expecting to either load an environment named `env-name` or start the interactive flow to create a new env with env-name.

This design makes sense for some commands like `azd env set foo bar`, or `azd up -e new-env` (b/c having the env creation as part of the flow makes sense for the end goal). But it makes less sense for commands like `azd env get-values` or `azd env select foo` (as there's an expectation on an existing env).

For `azd env select` , the action-command consumes the env-manager and azd-context (instead of a full env), like:

```go
type envSelectAction struct {
	azdCtx     *azdcontext.AzdContext
	envManager environment.Manager
	args       []string
}
```

This allows `azd env select` to return error if the selected env is not found:

image

The help-text, in this case, is recommending user to first run `azd env new env-name`.

IMO, this is a better UX and `azd env get-values` should use the same approach.  And then, as a follow up, I would consider making azd to ask the user if they want to create the env (run `azd env new env-name`) instead of returning the error. But that's an idea to be reviewed by PM/Team first.

@john0isaac , what do you think about making `azd env get-values` to be consistent with what `azd env select` is doing ?  You could reuse same error in that case.

Comment (john0isaac) [reply cli/azd/pkg/environment/azdcontext/azdcontext.go:125]: @vhvb1989 Thank you so much for explaining this.
ok, I will make it behave like `azd env select` to be consistent.

Comment (john0isaac) [reply cli/azd/pkg/environment/azdcontext/azdcontext.go:125]: @vhvb1989 Unfortunately, using the current architecture that's not possible

This is how I implemented your suggestion to match the `azd env select` and as you can see in the terminal my first implementation gets triggered first which raises a bigger issue:
image

The issue here is that whenever we use the `environment.Manager.Get()` it creates a new environment as it calls the `environment.LocalDataStore.Get()` which calls the `azdContext.azdContext.EnvironmentRoot()` which performs multiple functions calls in the _azdContext.go_ that end up executing the `azdContext.azdContext.NewAzdContext()` which triggers the error I have put before creating the environment.

IMO, I think there is something wrong with the flow of events here. because whenever I try to get a current environment it will create a new one which means I can't depend on Get in my implementation. unless we put a check to prevent this from happening.

My first implementation catches all the calls trying to get the current env I get what you say now with the current structure it's going to give the same error when trying to execute any command that relays on `azdContext`, what I think of as a future solution to be implemented later is that we give the same generic error and at each Action in the _env.go_ we append the helper command to the end of the generic error.


The flow of events:
1:
image

2:
image

3:
image

4:
image

5:
image

File: cli/azd/pkg/environment/azdcontext/azdcontext.go (hunk 2 above)
Comment (john0isaac) [reply cli/azd/pkg/environment/azdcontext/azdcontext.go]: done

**Comment by john0isaac** [comment]
I have included an explanation for why I have implemented it like this here  https://github.com/Azure/azure-dev/pull/2840#discussion_r1349924427.

**Comment by john0isaac** [comment]
I have played with it a bit more and found that something is wrong with this function no matter what I do it still prompts the user to create a new environment. (ps. I tried editing the select env text in the same file and it worked but no matter what I do the get-values doesn't reflect my changes)

As you can see in the terminal below after commenting the whole function it still prompts me to create a new env,
image

File: cli/azd/pkg/environment/azdcontext/azdcontext.go (hunk 3 above)
Comment (vhvb1989) [reply cli/azd/pkg/environment/azdcontext/azdcontext.go:125]: @john0isaac , did you remove the `env` from the `envGetValuesAction` , like:

```go
type envGetValuesAction struct {
	azdCtx    *azdcontext.AzdContext
	console   input.Console
	formatter output.Formatter
	writer    io.Writer
	flags     *envGetValuesFlags
       envManager environment.Manager // this is added while env is removed
}
```

Removing `env       *environment.Environment` is the key here, and it looks like your code is still using the `env` on line 555, here:

image

And `env` also needs to be removed from the Constructor here:

```go
func newEnvGetValuesAction(
	azdCtx *azdcontext.AzdContext,
	// env *environment.Environment,  --> Remove!!
	console input.Console,
	formatter output.Formatter,
	writer io.Writer,
	flags *envGetValuesFlags,
) actions.Action {
	return &envGetValuesAction{
		azdCtx:    azdCtx,
		console:   console,
		// env:       env,              --> Remove!!
		formatter: formatter,
		writer:    writer,
		flags:     flags,
	}
}
```

if `env` is an input arg for the Action constructor, azd will create it before calling the action, and that's where you would get the interactive flow.
On the other hand, creating an `envManager environment.Manager` does not create an environment, and calling `Get()` method from the manager returns error (like azd env select).  Or, if there's no error, it returns the environment, which you would use later (instead of `eg.env`)

Comment (john0isaac) [reply cli/azd/pkg/environment/azdcontext/azdcontext.go:125]: I knew it!
Thank you so much for the explanation.
Let me fix this rn.

Comment (john0isaac) [reply cli/azd/pkg/environment/azdcontext/azdcontext.go]: @vhvb1989 done, I have done what you suggested and it works perfectly fine thank you so much for helping me!
image

File: cli/azd/cmd/env.go [hunk 4]
```diff
@@ -514,36 +514,40 @@ func (eg *envGetValuesFlags) Bind(local *pflag.FlagSet, global *internal.GlobalC
...
+		console:    console,
+		envManager: envManager,
+		formatter:  formatter,
+		writer:     writer,
+		flags:      flags,
 	}
 }
 
 func (eg *envGetValuesAction) Run(ctx context.Context) (*actions.ActionResult, error) {
-	err := eg.formatter.Format(eg.env.Dotenv(), eg.writer, nil)
```
Comment (vhvb1989) [inline cli/azd/cmd/env.go:544]: I think this is missing, right?

it should be in the lines below, below the `return nil nil`

File: cli/azd/cmd/env.go [hunk 5]
```diff
@@ -514,36 +514,40 @@ func (eg *envGetValuesFlags) Bind(local *pflag.FlagSet, global *internal.GlobalC
...
+	_, err := eg.envManager.Get(ctx, "")
+	if errors.Is(err, environment.ErrNotFound) {
+		return nil, fmt.Errorf(
+			`"environment does no exist. You can create it with "azd env new"`,
+		)
+	} else if err != nil {
+		return nil, fmt.Errorf("ensuring environment exists: %w", err)
 	}
 
 	return nil, nil
```
Comment (vhvb1989) [inline cli/azd/cmd/env.go:553]:
```suggestion
	env, err := eg.envManager.Get(ctx, "")
	if errors.Is(err, environment.ErrNotFound) {
		return nil, fmt.Errorf(
			`"environment does no exist. You can create it with "azd env new"`,
		)
	} else if err != nil {
		return nil, fmt.Errorf("ensuring environment exists: %w", err)
	}

	return nil, eg.formatter.Format(env.Dotenv(), eg.writer, nil)
```

**Review by vhvb1989 — COMMENTED** [review]
small fix to do the actual call to format() for the positive case.

File: cli/azd/cmd/env.go (hunk 5 above)
Comment (john0isaac) [reply cli/azd/cmd/env.go]: yep, sorry for that I'm a little sleepy 😴

**Review by vhvb1989 — APPROVED** [review]
Thank you very much for your contribution

File: cli/azd/cmd/env.go [hunk 6]
```diff
@@ -514,39 +514,43 @@ func (eg *envGetValuesFlags) Bind(local *pflag.FlagSet, global *internal.GlobalC
...
+		writer:     writer,
+		flags:      flags,
 	}
 }
 
 func (eg *envGetValuesAction) Run(ctx context.Context) (*actions.ActionResult, error) {
-	err := eg.formatter.Format(eg.env.Dotenv(), eg.writer, nil)
-	if err != nil {
-		return nil, err
+	env, err := eg.envManager.Get(ctx, "")
```
Comment (wbreza) [inline cli/azd/cmd/env.go:544]: I feel like we should be pulling the default environment name from the `azdcontext`, `azdContext.GetDefaultEnvironmentName()`  and passing that value to `envManager.Get(ctx, name)` instead of an empty string.

Comment (wbreza) [reply cli/azd/cmd/env.go:544]: I also feel like this same error might also exist on `azd env refresh` command when the environment hasn't been initialized.

**Review by wbreza — COMMENTED** [review]
This is looking good - just a couple suggestions that I'd like to see implemented.

File: cli/azd/cmd/env.go (hunk 6 above)
Comment (john0isaac) [reply cli/azd/cmd/env.go:544]: > I also feel like this same error might also exist on `azd env refresh` command when the environment hasn't been initialized.

@wbreza I don't get your second comment.. do you want me to implement this on the env refresh or are you saying that this error will be triggered when someone tries to run `azd env refresh`.

Comment (john0isaac) [reply cli/azd/cmd/env.go]: > I feel like we should be pulling the default environment name from the `azdcontext`, `azdContext.GetDefaultEnvironmentName()` and passing that value to `envManager.Get(ctx, name)` instead of an empty string.

done ✅

File: cli/azd/cmd/env.go [hunk 7]
```diff
@@ -514,39 +514,44 @@ func (eg *envGetValuesFlags) Bind(local *pflag.FlagSet, global *internal.GlobalC
...
 
 func (eg *envGetValuesAction) Run(ctx context.Context) (*actions.ActionResult, error) {
-	err := eg.formatter.Format(eg.env.Dotenv(), eg.writer, nil)
-	if err != nil {
-		return nil, err
+	name, _ := eg.azdCtx.GetDefaultEnvironmentName()
+	env, err := eg.envManager.Get(ctx, name)
+	if errors.Is(err, environment.ErrNotFound) {
+		return nil, fmt.Errorf(
+			`"environment does no exist. You can create it with "azd env new"`,
```
Comment (wbreza) [inline cli/azd/cmd/env.go:548]:
```suggestion
			`"environment does not exist. You can create it with "azd env new"`,
```

**Review by wbreza — APPROVED** [review]
Minor grammar error otherwise looks great! Thanks for the fix!
