### PR TITLE
GitHub CI Provider: Include current git branch in federated authentication

### LINKED ISSUE #2428: [Issue] Federated credential is set only on main (not other branches)
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**

azd version 1.0.2 (commit 145e046b1ea9394bd4e1b1d539eb32e860d692fb)

**Describe the bug**

To test my azd workflow, I set the push to include my testing branch (cicd). However, when I do that, I get an error:

AADSTS70021: No matching federated identity record found for presented assertion. Assertion Issuer: 'https://token.actions.githubusercontent.com/'. Assertion Subject: 'repo:pamelafox/sample-app-aoai-chatGPT:ref:refs/heads/cicd'. Assertion Audience: 'api://AzureADTokenExchange'. [https://docs.microsoft.com/en-us/azure/active-directory/develop/workload-identity-federation\r\nTrace](https://docs.microsoft.com/en-us/azure/active-directory/develop/workload-identity-federation/r/nTrace) ID: fcbeda46-d5f3-48c6-9058-84408cf47600\r\nCorrelation ID: 031d62c7-6267-4c89-aa09-64364f3235c8\r\nTimestamp: 2023-06-16 16:38:31Z",

I realized that's because the federated credentials are only set up for the main branch and pull_request, per:

https://github.com/Azure/azure-dev/blob/f84dbd154d5b12ce58ff1d475f29d063d9f6cdb9/cli/azd/pkg/pipeline/github_provider.go#L621

So I adjusted my workflow to include pull_request to get it working.

**To Reproduce**

Change azure-dev.yaml to include a non-main branch, push to that branch, see error.

**Expected behavior**

I was hoping it'd work. Maybe the code could check azure-dev.yaml to decide what to make credentials for? If not, maybe it could let the user know that it'll only work on main/pull_request.

**Environment**

CI/CD server, VS Code

### PR DESCRIPTION
**Pull request by wbreza**
Fixes #2428, #2040

Includes the current git branch name when setting up federated credentials for GitHub.

### CODE REVIEW

File: cli/azd/pkg/pipeline/azdo_provider.go [hunk 1]
```diff
@@ -568,7 +568,6 @@ func gitInsteadOfConfig(
 // Push code and queue pipeline
 func (p *AzdoScmProvider) GitPush(
 	ctx context.Context,
-	gitCli git.GitCli,
```
Comment (wbreza) [inline cli/azd/pkg/pipeline/azdo_provider.go:571]: Small unrelated fix.  We don't need the `gitCli` on the function call anymore.

**Review by ellismg — APPROVED** [review]
Nice fix!  LGTM!

File: cli/azd/CHANGELOG.md [hunk 2]
```diff
@@ -5,6 +5,7 @@
 ### Bugs Fixed
 
 - [[2402]](https://github.com/Azure/azure-dev/pull/2279) Support for workload profiles in Azure Container Apps
+- [[2428, 2040]](https://github.com/Azure/azure-dev/pull/2468) Include current git branch in GitHub federated credentials
```
Comment (jongio) [inline cli/azd/CHANGELOG.md:8]: Can we update this to re-use the SP that was already used?

For example.

Let's say I run this on main, then i want to run it on 'dev' branch.  As it is now, I think multiple SPs, Apps, etc.  will be created.  Can we reuse the existing ones?

Comment (vhvb1989) [reply cli/azd/CHANGELOG.md:8]: You can use `--principal-name foo` to re-use a `foo` SP (with some bottom notes).

* If you re-use a SP using client-secret, the secret is rotated and any current repository using that SP is broken, as it has previous credentials

Comment (wbreza) [reply cli/azd/CHANGELOG.md:8]: @jongio - I agree with @vhvb1989 here.  Devs should tell azd with principal to use which would go ahead and then just add the new federated auth credential into the existing identity.  We do store the `AZURE_CLIENT_ID` of the identity in azd env but this may not always be the desired flow in the event they wanted to use different identities for different branches.

Happy to take this as a follow-up change if we change our mind.
