### PR TITLE
fix: resolves #5074

### LINKED ISSUE #5074: [Issue] Unable to deploy to AKS cluster with Microsoft Entra ID authentication and Azure RBAC enabled
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**

```
azd version 1.14.0 (commit c928795c47f27d1e997c217147dc649054ac05c8)
```

**Describe the bug**

Failing to deploy a Helm chart to an AKS cluster with Microsoft Entra ID authentication and Azure RBAC enabled. Getting the following error:

```
Deploying services (azd deploy)

  (x) Failed: Deploying service demo

ERROR: failed deploying service 'demo': helm deployment failed: failed to install helm chart aks-store-demo/aks-store-demo-chart: exit code: 1, stdout: , stderr: Error: Kubernetes cluster unreachable: the server has asked for the client to provide credentials
```

As soon as I remove the configuration for Microsoft Entra ID authentication and Azure RBAC the `azd deploy` is able to successfully log into the cluster and deploy the Helm chart, so there must be something going on with the way azd is configuring the kubeconfig file or something wrong with the way azd uses the access token provided by kubelogin. 

**To Reproduce**
1. `az login`
1. `azd auth login`
1. `azd config set alpha.aks.helm on`
1. `git clone git@github.com:pauldotyu/aks-store-demo.git`
1. `cd aks-store-demo`
1. `azd up`

> NOTE: This uses Terraform for deployment so you must have Terraform installed locally

**Expected behavior**
azd should be able to login to the cluster and deploy the app

**Environment**
Information on your environment:
    * Language name and version
    * IDE and version : [e.g. Visual Studio 16.3]

**Additional context**

### PR DESCRIPTION
**Pull request by pauldotyu**
Resolves #5074 by adding tenant id to kubeconfig convert options when cluster is Azure RBAC enabled or local account is disabled.

### CODE REVIEW

File: cli/azd/pkg/project/service_target_aks.go [hunk 1]
```diff
@@ -606,6 +606,7 @@ func (t *aksTarget) ensureClusterContext(
 		convertOptions := &kubelogin.ConvertOptions{
 			Login:      "azd",
 			KubeConfig: kubeConfigPath,
+			TenantId:   t.env.GetTenantId(),
```
Comment (vhvb1989) [inline cli/azd/pkg/project/service_target_aks.go:609]: tenantId is not ensured to be in the azd-environment.

We have a way to resolve the tenantId for a project here: https://github.com/Azure/azure-dev/blob/main/cli/azd/cmd/auth_token.go#L84

Most cases, it is resolved from the subscription Id, which is ensured to be in the azd-env

Comment (vhvb1989) [reply cli/azd/pkg/project/service_target_aks.go:609]: Let me ping @wbreza as I am not very familiar with the `managedCluster`

**Review by wbreza — APPROVED** [review]
LGTM
