### PR TITLE
Fix `azd completion` help text

### LINKED ISSUE #2846: [Issue] Running `azd completion <shell> --help` does not print help related to installing shell completions
- [  ] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
azd version 1.4.1 (commit 1cbed85cf47ed235b5ed31868eda79619525bfcc)

**Describe the bug**
Under the shell completion section of the [README](https://github.com/Azure/azure-dev#set-up-shell-completion), it says to get instructions for specific shell, run `azd completion <shell> --help` (substituting actual name here as the output is same for each shell).

However, instead of printing specific instructions for installing completions for each shell, the generic help (which can also be viewed with `azd --help` is printed.

**To Reproduce**
1. Open terminal with a shell of your choice
2. Ensure azd is installed.
3. Run `azd --help` and see the output.
4. Now run `azd completion <your shell name> --help` and see the output.

**Expected behavior**
The output of the command `azd completion <your shell name> --help` should provide specific instruction to install completion for that shell and not print the generic help which is the same output as `azd --help`.

**Environment**
Information on your environment:
    * macOS Sonoma with regular terminal
    * zsh version (this came built in): zsh 5.9 (x86_64-apple-darwin23.0)
    * bash version (this came built in): GNU bash, version 3.2.57(1)-release (arm64-apple-darwin23)
    * fish version: fish, version 3.6.1

**Additional context**
This issue is encountered on a fresh install of azd and the system itself. Login process has not been initiated yet, though I don't think it should affect it in anyway.

### LINKED ISSUE #4079: "azd completion bash --help" does not show dedicated help
According to doc  https://github.com/Azure/azure-dev#set-up-shell-completion

"azd completion bash --help" does show dedicated help - but does not - juts genersl cmd line help
"azd completion bash" onloy outrputs completion script without any help as well.

Manual or cmd help is bugg,y either ir

### PR DESCRIPTION
**Pull request by JeffreyCA**
Fixes #2846
Fixes #4079

### `azd --help`
image

### `azd completion --help`
image

### `azd completion bash --help`
image

### `azd completion fish --help`
image

### `azd completion zsh --help`
image

### `azd completion powershell --help`
image

### CODE REVIEW

File: cli/azd/cmd/completion.go [hunk 1]
```diff
@@ -0,0 +1,188 @@
...
+	var err error
+	switch a.shell {
+	case "bash":
+		err = rootCmd.GenBashCompletion(a.cmd.OutOrStdout())
+	case "zsh":
+		err = rootCmd.GenZshCompletion(a.cmd.OutOrStdout())
+	case "fish":
+		err = rootCmd.GenFishCompletion(a.cmd.OutOrStdout(), true)
+	case "powershell":
+		err = rootCmd.GenPowerShellCompletion(a.cmd.OutOrStdout())
```
Comment (vhvb1989) [inline cli/azd/cmd/completion.go]: nit. Make constants from the strings and use them when you add the subcommand and here

File: cli/azd/cmd/root.go [hunk 2]
```diff
@@ -90,8 +90,6 @@ func NewRootCmd(
 		DisableAutoGenTag: true,
 	}
 
-	rootCmd.CompletionOptions.HiddenDefaultCmd = true
```
Comment (vhvb1989) [inline cli/azd/cmd/root.go:93]: Wondering why did we do this in the past....  Would the default command fail if there is not a definition for the command like the one you are adding?

Comment (JeffreyCA) [reply cli/azd/cmd/root.go:93]: > Would the default command fail if there is not a definition for the command like the one you are adding?

There's a separate option `DisableDefaultCmd` for that:

image

I'm not sure why even after removing `HiddenDefaultCmd  = true`, it doesn't show in `azd --help`. Maybe because of how we override the default `--help` text in https://github.com/Azure/azure-dev/blob/69d00310ac3dcf9dc47d71f33aa3f87649a6d02a/cli/azd/cmd/root.go#L471-L473

In any case, the docs suggest this approach to provide a custom implementation: https://github.com/spf13/cobra/blob/main/site/content/completions/_index.md#creating-your-own-completion-command

File: cli/azd/cmd/testdata/TestUsage-azd-completion-powershell.snap [hunk 3]
```diff
@@ -0,0 +1,21 @@
...
+Global Flags
+    -C, --cwd string 	: Sets the current working directory.
+        --debug      	: Enables debugging and diagnostics logging.
+        --docs       	: Opens the documentation for azd completion powershell in your web browser.
+    -h, --help       	: Gets help for powershell.
+        --no-prompt  	: Accepts the default value instead of prompting, or it fails if there is no default.
+
+Examples
+  Install completions for all sessions
+    azd completion powershell >> $PROFILE
```
Comment (weikanglim) [inline cli/azd/cmd/testdata/TestUsage-azd-completion-powershell.snap]: This ends up adding a lot of auto-generated stuff into Profile.ps1. 

```bash
$ azd completion powershell | wc -l          
270
```

Does it make more sense to create a separate script and append the loading instead?

```pwsh
 $ azd completion powershell > $HOME\.azd\completion.ps1
 $ Add-Content $PROFILE "$HOME\.azd\completion.ps1"
```

I saved it to `.azd\completion.ps1" as it seemed like the best place for this type of thing.

**Review by weikanglim — APPROVED** [review]
Love it!

**Review by vhvb1989 — APPROVED** [review]

File: cli/azd/cmd/testdata/TestUsage-azd-completion-powershell.snap (hunk 3 above)
Comment (JeffreyCA) [reply cli/azd/cmd/testdata/TestUsage-azd-completion-powershell.snap]: Updated, thanks for the suggestion - just needed to add a `.` to it:

image
