### PR TITLE
Fix principal tenant resolution and simplify subscription lookup

### LINKED ISSUE #7173: CurrentPrincipalId returns home-tenant oid for guest/B2B users, causing incorrect identity in resource tenant
## Problem

`CurrentPrincipalId` (in `current_principal_id_provider.go`) resolves the current user's object ID by:
1. Calling `LookupTenant(subscriptionId)` → returns `UserAccessTenantId` (the user's **home tenant**)
2. Calling Graph `/me` against that tenant → returns the **home-tenant oid**

For B2B/guest users, the home-tenant oid is **different** from the guest oid in the resource tenant. All callers that use this principal ID to interact with the resource tenant's ARM APIs receive the wrong identity.

## Impact

All callers of `CurrentPrincipalId` are affected:

| Caller | File | Impact |
|---|---|---|
| Preflight role check | `bicep_provider.go:2220` | `assignedTo()` filter uses wrong oid → false positive warning |
| `loadParameters` | `bicep_provider.go:1800` | `AZURE_PRINCIPAL_ID` in ARM params → role assignments target wrong principal |
| bicepparam compile | `bicep_provider.go:1980` | Same as above |
| Terraform provider | `terraform_provider.go:722` | Principal ID in tfvars → wrong identity |
| Key Vault RBAC | `cmd/env.go:612` | Role assignment on Key Vault targets wrong principal |

## Root Cause

`LookupTenant` returns `sub.UserAccessTenantId` (correct for **credential creation**) but callers also use the same tenant for **identity resolution** via Graph `/me`. For guest users:
- Home tenant → Graph `/me` returns `home-oid` (e.g. `4070b897-...`)
- Resource tenant → Graph `/me` returns `guest-oid` (different value)

The `UserAccessTenantId` vs `TenantId` distinction (`account.Subscription` model) is documented as:
- `UserAccessTenantId`: tenant under which the user authenticates (home tenant)
- `TenantId`: tenant that owns the subscription (resource tenant)

## Proposed Fix

`CurrentPrincipalId` (or `GetCurrentPrincipalId`) should resolve the oid in the **resource tenant** context when the principal ID will be used for ARM operations in that tenant. This may require:
1. Calling Graph `/me` against `sub.TenantId` instead of `sub.UserAccessTenantId`, or
2. Extracting the oid from an ARM token scoped to the resource tenant, or
3. Providing both oids and letting callers choose

Care must be taken not to break credential creation flows, which correctly use `UserAccessTenantId`.

## Related

- #7169 (preflight ignoring RBAC Admin role — tactical fix applied separately)

### PR DESCRIPTION
**Pull request by weikanglim**
## Summary

Fix principal ID resolution for guest/B2B scenarios by resolving identities in the subscription's resource tenant, while preserving access-tenant behavior for credential acquisition flows.

### Resolve `AZURE_PRINCIPAL_ID` in the subscription tenant

**What's changing?**  
When azd determines `AZURE_PRINCIPAL_ID`, it now resolves that identity in the tenant that owns the subscription, instead of the tenant you originally signed in through. For guest/B2B users, this means azd uses the correct guest object ID for the subscription tenant.

**Why?**  
This should fix previous failures users may have encountered when azd created RBAC assignments with the wrong principal ID.

### Prefer the ARM token `oid` before calling Microsoft Graph

**What's changing?**  
azd now reads the principal ID from the ARM access token's `oid` claim first, and only calls Microsoft Graph if that claim is unavailable.

**Why?**  
This avoids unnecessary Graph access and improves performance, while keeping the existing fallback behavior for cases where the token does not contain a usable object ID.

## Internal changes

- replace the temporary tenant/context resolver abstractions with `account.SubscriptionResolver`, which returns `*account.Subscription`
- keep `auth token`, monitor, blob storage, and subscription credential flows on `Subscription.UserAccessTenantId`
- update tests and command guidance docs to match the new subscription resolver shape

Fixes #7173

### CODE REVIEW

File: cli/azd/pkg/azsdk/storage/storage_blob_client_test.go [hunk 1]
```diff
@@ -31,19 +31,34 @@ func (m *mockMultiTenantCredentialProvider) GetTokenCredential(
...
+func (m *mockSubscriptionResolver) LookupTenant(
 	ctx context.Context, subscriptionId string) (string, error) {
 	args := m.Called(ctx, subscriptionId)
 	return args.String(0), args.Error(1)
 }
 
+func (m *mockSubscriptionResolver) GetSubscription(
+	ctx context.Context, subscriptionId string,
+) (*account.Subscription, error) {
+	tenantId, err := m.LookupTenant(ctx, subscriptionId)
```
Comment (jongio) [inline cli/azd/pkg/azsdk/storage/storage_blob_client_test.go]: **[MEDIUM]** `GetSubscription` delegates to `LookupTenant`, which isn't part of `SubscriptionResolver`. All test expectations (`On("LookupTenant", ...)`) target this internal bridge method. If someone writes a new test using `On("GetSubscription", ...)`, testify won't match because `Called()` fires inside `LookupTenant`. Consider rewriting the mock to set expectations on `GetSubscription` directly.

File: cli/azd/pkg/azureutil/principal_test.go [hunk 2]
```diff
@@ -0,0 +1,88 @@
...
+		&azcore.ClientOptions{
+			Transport: mockContext.HttpClient,
+		},
+		cloud.AzurePublic(),
+	)
+
+	principalId, err := GetCurrentPrincipalId(*mockContext.Context, userProfile, "resource-tenant")
+	require.NoError(t, err)
+	require.Equal(t, "graph-user-id", principalId)
+}
```
Comment (jongio) [inline cli/azd/pkg/azureutil/principal_test.go:88]: **[LOW]** Both tests cover the success paths (oid present, oid missing + Graph fallback). The `errors.Join` path in principal.go:36-39 - where both token oid extraction and Graph /me fail - isn't tested. Worth adding a test to verify the combined error message is useful for debugging.

**Comment by weikanglim** [comment]
Thanks @vhvb1989 — I took a closer look at the extension impact.

I think this PR can stay core-only. The bug fixed here was in azd core's tenant selection for principal/resource-tenant operations. For extensions, the API surface already exposes both `TenantId` and `UserTenantId`, so this looks like a separate cleanup rather than something we need to scope into #7549.

I opened #7563 to track that follow-up. From the audit so far:
- generated extension templates in Go / JS / .NET should use `UserTenantId` (not `TenantId`) when they create user credentials from `PromptSubscription`
- `extensions/azure.ai.agents/internal/project/agent_identity_rbac.go` looks like a likely resource-tenant/RBAC bug candidate that should be reviewed separately

Most of the other extension call sites I spot-checked look like access-tenant credential acquisition paths and are likely correct.
