### PR TITLE
bicep: remove `main.parameters.json` caching

### LINKED ISSUE #3973: `azd env set` in a hook script doesn't have the variables available in future steps
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:
> azd version 1.9.3 (commit e1624330dcc7dde440ecc1eda06aac40e68aa0a3)

**Describe the bug**

If you use a hook, such as preprovision, to add environment variables to azd using `azd env set`, those variables aren't available until the azd session is restarted (meaning you can't use `azd up`).

We come across this in https://github.com/microsoft/azure-openai-service-proxy/ in which we have to create an Entra ID app registration and then want to push the client id/tenant id to services that azd will deploy.

[Here is the preprovision hook definition](https://github.com/microsoft/azure-openai-service-proxy/blob/main/azure.yaml#L31-L35) and then [here is the script](https://github.com/microsoft/azure-openai-service-proxy/blob/main/infra/scripts/setup-app-registration.sh).

The reason that we rely on this is there is no bicep support for deploying app registrations presently, so we use the Azure CLI to handle it.

Ideally, each step of the azd pipeline would load the `.env` file, even if it's being run through a group command like `azd up`.

### PR DESCRIPTION
**Pull request by weikanglim**
With this change, we remove the in-memory `main.parameters.json` cache.

Backstory: In the old days of `azd`, we introduced in-memory caching for `main.parameters.json` with #3155 to avoid a re-prompt when the user declines the prompt "Save the value in the environment for future use?". We added this as a way to communicate within `azd` that "this value is configured for the current azd process lifetime".

After #3479, we ended up always saving the values to `config.json` and remove the "Save the value in the environment for future use?" prompt. Since then, the in-memory caching just reduces an extra load from disk, but behaviorally act the same.

Fixes #3973, #4310, 

## Verification

Since #4310 is implemented as an internal `preprovision` hook that sets `SERVICE_X_RESOURCE_EXISTS` and shares the same root cause, they would be fixed the same.

I modified our [storage](https://github.com/Azure/azure-dev/blob/3b48ae58706ea4c0feb1943d92caef9b9a24a12e/cli/azd/test/functional/testdata/samples/storage/azure.yaml) sample:
```yaml
name: storage
metadata: 
  template: azd-test/storagetest@v1
hooks:
  preprovision: 
   shell: sh
   run: azd env set INT_TAG_VALUE 500
```

And observed both in Portal and the output that `INT_TAG_VALUE` was successfully set to `500`.

### CODE REVIEW

File: cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go [hunk 1]
```diff
@@ -1922,19 +1916,15 @@ func (p *BicepProvider) ensureParameters(
...
-				configuredParameters[prompt.key] = azure.ArmParameterValue{
-					Value: value,
-				}
 			}
 		}
 	}
 
 	if configModified {
 		if err := p.envManager.Save(ctx, p.env); err != nil {
-			p.console.Message(ctx, fmt.Sprintf("warning: failed to save configured values: %v", err))
```
Comment (weikanglim) [inline cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go:1934]: In case it isn't clear why ignoring this error may not be ideal:

Suppose that `Save()` failed due to flakiness once -- this variable ends up getting re-prompted which is confusing behavior to a user. Straight up failing is better here.

A code [demonstration](https://github.com/Azure/azure-dev/compare/main...weikanglim:weilim/rm-param-cache-failsave-demo?expand=1).

Here's it live:
Screenshot 2024-09-20 at 1 22 38 PM

**Review by wbreza — APPROVED** [review]

**Review by ellismg — APPROVED** [review]

**Review by vhvb1989 — APPROVED** [review]
