### PR TITLE
aspire: Fix invalid bicep when using binding expressions

### LINKED ISSUE #3839: Make it possible to use endpoints to containers, projects or dockerfiles in bicep parameters
Follow up from https://github.com/Azure/azure-dev/pull/3820

The main scenario here is a webhooks. External services that need to call your compute (e.g. Azure event grid, azure web pubsub etc)

```C#
var builder = DistributedApplication.CreateBuilder(args);

var p = builder.AddProject<Projects.WebApplication1>("webapplication1");

var az = builder.AddAzureStorage("storage")
                .WithParameter("z", () => p.GetEndpoint("http"))
                .RunAsEmulator().AddQueues("q1");

builder.Build().Run();
```

Results in 

```bicep
module storage 'storage/storage.module.bicep' = {
  name: 'storage'
  scope: rg
  params: {
    location: location
    principalId: resources.outputs.MANAGED_IDENTITY_PRINCIPAL_ID
    principalType: 'ServicePrincipal'
    z: 'http://webapplication1.internal.{{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN }
  }
}
```

Notice the go template syntax in the bicep. This should just use the bicep value instead of the go template (when in this context).

Instead we want:

```bicep
module storage 'storage/storage.module.bicep' = {
  name: 'storage'
  scope: rg
  params: {
    location: location
    principalId: resources.outputs.MANAGED_IDENTITY_PRINCIPAL_ID
    principalType: 'ServicePrincipal'
    z: 'http://webapplication1.${resources.outputs.AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN}'
  }
}
```

### PR DESCRIPTION
**Pull request by ellismg**
We were not taking the emitType flag into account when generating values for `.host` or `.url` binding expressions and just always emited the yaml format.  This caused invalid bicep generation when a module would have a pramater with a value like
`${project.bindings.https.url}`.

Fixes #3839

### CODE REVIEW

**Comment by ellismg** [comment]
I want to write a small regression test here with a baseline because this stuff is tricky enough, but locally this fixed the issue, so I wanted to get the code change up so I could get privates.

**Comment by ellismg** [comment]
> I want to write a small regression test here with a baseline because this stuff is tricky enough, but locally this fixed the issue, so I wanted to get the code change up so I could get privates.

Added this as a case to an existing test around bicep generation.

**Review by weikanglim — APPROVED** [review]
LGTM! I was worried from the issue description that this would end up being a bigger change. Cool that this ended up being a simple fix, a good indicator of well modeled code.

**Comment by ellismg** [comment]
> LGTM! I was worried from the issue description that this would end up being a bigger change. Cool that this ended up being a simple fix, a good indicator of well modeled code.

I was actually concerned about this too at first, @weikanglim, and a tad nervous because it was a while since I had been in this part of the code.  The groundwork that @vhvb1989 laid when he was doing the bicep module stuff really worked out well here, the emit type pattern felt really nice.  I was actually shocked at first thinking "really, that's all I needed to do?"

File: cli/azd/pkg/apphost/generate.go [hunk 1]
```diff
@@ -1309,6 +1309,24 @@ func (b infraGenerator) evalBindingRef(v string, emitType inputEmitType) (string
 			bindingMappedToMainIngress = true
 		}
 
+		hostNameSuffix := func(external bool) string {
+			var suffix string
+			switch emitType {
+			case inputEmitTypeYaml:
```
Comment (vhvb1989) [inline cli/azd/pkg/apphost/generate.go:1315]: Here is one of details why I usually prefer not using a function inside a function. It is not clear if `inputEmitTypeYaml` is scoped to the parent function or if it is a package global variable =P (at least by the first look at the PR).

Not a blocker, or anything.  I guess these cases might be handled by the compiler similar to macros, avoiding the call-stack.

**Review by vhvb1989 — APPROVED** [review]

File: cli/azd/pkg/apphost/generate.go (hunk 1 above)
Comment (ellismg) [reply cli/azd/pkg/apphost/generate.go:1315]: I am guessing you mean `emitType` (since `inputEmitTypeYaml` is a constant) which is the argument to the outer function we closed over.

I did consider pushing this to top level, but it would mean the call sites got a little longer since we have to thread `emitType` into the call, which is sort of why I prefer this style.

Something else I briefly considered was adding:

```go
func (emitType inputEmitType) hostNameSuffix(external bool) string {
   // ... the implementation is the same as the above ...
}
```

and then at all sites doing: `emitType.hostNameSuffix(binding.External)` but I wasn't sure if that was being too clever for my own good.
